// ═══════════════════════════════════════════════════════════════════
// LOGOS Curriculum — All PhD logic, all 2nd-grade language
// Each unit has 10+ quiz questions for mastery practice
// ═══════════════════════════════════════════════════════════════════

const C = [
// 🌱 SEEDS — The Basics (Units 1-6)

{id:1,realm:"explorer",title:"True or False?",subtitle:"What is a statement?",
story:"Maya found a wise owl in the park. 🦉\n\nThe owl said: \"Some sentences are STATEMENTS. A statement is a sentence that is true or false.\"\n\nMaya asked: \"What about questions?\"\n\n\"Great thinking!\" the owl said. \"Questions are NOT statements. Only sentences that say something true or false count.\"",
realWorld:"🔍 Detectives figure out what is true or false. Doctors decide if 'this patient has a fever' is true or false. You use statements every day!",
learn:[
{type:"concept",title:"What is a Statement?",body:"A statement is a sentence that is TRUE or FALSE.\n\n🟢 \"Dogs have four legs.\" → TRUE\n🔴 \"The moon is made of cheese.\" → FALSE\n\nBoth are statements! One true, one false — but both CLAIM something."},
{type:"concept",title:"What is NOT a Statement?",body:"Some sentences are NOT statements:\n\n❓ \"Is it raining?\" → QUESTION\n👉 \"Sit down!\" → COMMAND\n🌟 \"I wish I could fly!\" → WISH\n😮 \"Wow!\" → REACTION\n\nYou can't say these are true or false!"},
{type:"example",title:"Let's Try Some!",body:"🟢 \"Cats have tails.\" → STATEMENT (true)\n👉 \"Please close the door.\" → NOT a statement\n❓ \"Do you like pizza?\" → NOT a statement\n🔴 \"2 + 2 = 7\" → STATEMENT (false!)\n🌟 \"I hope it snows!\" → NOT a statement"},
{type:"concept",title:"True ≠ Good, False ≠ Bad",body:"A true statement can be sad:\n😢 \"It rained on our picnic.\" → TRUE and sad\n\nA false statement can sound nice:\n😊 \"Everyone is happy.\" → FALSE but nice\n\nLogic only cares: TRUE or FALSE?"},
],
quiz:[
{q:"Which one is a statement?",opts:["\"Close the window!\"","\"Is it Tuesday?\"","\"Cats can fly.\"","\"Wow!\""],answer:2,explain:"\"Cats can fly\" is a statement — it's false! The others are a command, question, and reaction."},
{q:"A statement has to be:",opts:["Always true","Always false","Either true or false","Nice to say"],answer:2,explain:"A statement just has to be true OR false. That's it!"},
{q:"Which is NOT a statement?",opts:["\"Snow is cold.\"","\"2 + 3 = 5\"","\"Please help me.\"","\"Fish swim.\""],answer:2,explain:"\"Please help me\" is a request — not true or false."},
{q:"\"I wish it were summer\" — is this a statement?",opts:["Yes, it is","No — wishes aren't statements"],answer:1,explain:"Wishes say what someone wants, not what is true or false."},
{q:"\"Elephants are tiny.\" — is this a statement?",opts:["No, because it's wrong","Yes! It's a FALSE statement"],answer:1,explain:"Even false sentences are statements!"},
{q:"\"What time is lunch?\" — is this a statement?",opts:["Yes","No — questions aren't statements"],answer:1,explain:"Questions ask something. They don't claim true or false."},
{q:"Which one is a statement?",opts:["\"How tall are you?\"","\"Stop running!\"","\"2 + 2 = 5\"","\"Ouch!\""],answer:2,explain:"\"2 + 2 = 5\" is false, but it IS a statement!"},
{q:"\"Bananas are purple.\" This is:",opts:["Not a statement","A false statement","A true statement","A question"],answer:1,explain:"It claims bananas are purple — that's false! But it IS a statement."},
{q:"\"Dogs are the best!\" — is this a statement?",opts:["Yes — clearly true!","Tricky — it's an opinion, not clearly T/F","No — it's a command"],answer:1,explain:"Opinions are tricky! In strict logic, we prefer clear true/false claims."},
{q:"Which sentence is NOT a statement?",opts:["\"The Earth orbits the Sun.\"","\"Go clean your room!\"","\"7 is an odd number.\"","\"Ice is frozen water.\""],answer:1,explain:"\"Go clean your room!\" is a command — not true or false!"},
],
match:[{left:"\"Dogs bark.\"",right:"✅ Statement (true)"},{left:"\"Did you eat?\"",right:"❓ Question"},{left:"\"Go to bed!\"",right:"👉 Command"},{left:"\"Fish swim.\"",right:"✅ Statement (true)"},{left:"\"I hope it snows.\"",right:"🌟 Wish"},{left:"\"2 + 2 = 7\"",right:"🔴 Statement (false)"},{left:"\"Wow!\"",right:"😮 Reaction"},{left:"\"Penguins can fly.\"",right:"🔴 Statement (false)"}],
sort:{prompt:"Is it a STATEMENT or NOT?",categories:["✅ Statement","❌ Not a Statement"],
items:[{text:"\"The Earth is round.\"",cat:0},{text:"\"Are we there yet?\"",cat:1},{text:"\"7 is bigger than 3.\"",cat:0},{text:"\"Open your books!\"",cat:1},{text:"\"Bananas are purple.\"",cat:0},{text:"\"What a great day!\"",cat:1},{text:"\"Penguins can't fly.\"",cat:0},{text:"\"Yikes!\"",cat:1},{text:"\"Water boils at 100°C.\"",cat:0},{text:"\"Please sit down.\"",cat:1}]}
},

{id:2,realm:"explorer",title:"AND, OR, NOT",subtitle:"The three magic words",
story:"The owl gave Maya three magic words. 🪄\n\n\"AND means BOTH must be true.\"\n\"OR means AT LEAST ONE must be true.\"\n\"NOT just flips true to false!\"\n\nMaya tried: \"So 'I like dogs AND cats' is only true if I really like both?\"\n\n\"Exactly!\" 🦉",
realWorld:"🎮 Games use these! \"Press jump AND duck\" means both. \"Choose sword OR shield\" means pick one. Every computer uses AND, OR, NOT!",
learn:[
{type:"concept",title:"AND — Both Must Be True",body:"\"A AND B\" is only true when BOTH are true.\n\n🟢 AND 🟢 = 🟢\n🟢 AND 🔴 = 🔴\n🔴 AND 🟢 = 🔴\n🔴 AND 🔴 = 🔴\n\nThink: You need BOTH tickets to ride!"},
{type:"concept",title:"OR — At Least One",body:"\"A OR B\" is true when at least one is true.\n\n🟢 OR 🟢 = 🟢\n🟢 OR 🔴 = 🟢\n🔴 OR 🟢 = 🟢\n🔴 OR 🔴 = 🔴\n\nThink: You need at least ONE ticket!"},
{type:"concept",title:"NOT — The Flipper",body:"NOT flips the answer.\n\n🟢 → 🔴 (NOT true = false)\n🔴 → 🟢 (NOT false = true)\n\nIf \"sunny\" is true, \"NOT sunny\" is false.\nIf \"raining\" is false, \"NOT raining\" is true!"},
{type:"example",title:"Practice!",body:"\"I have a dog AND a cat.\"\nDog: yes. Cat: no.\n→ 🔴 FALSE (need BOTH!)\n\n\"I have a dog OR a cat.\"\nDog: yes. Cat: no.\n→ 🟢 TRUE (at least one!)\n\n\"I do NOT have a fish.\"\nFish: no.\n→ 🟢 TRUE (flipped!)"},
],
quiz:[
{q:"\"Warm AND sunny.\" It's warm but NOT sunny. True or false?",opts:["True","False"],answer:1,explain:"AND needs BOTH. Since sunny is false, the whole thing is false."},
{q:"\"Pizza OR pasta.\" You get pizza but no pasta.",opts:["True — OR means either works!","False — need both"],answer:0,explain:"OR is true when at least one is true."},
{q:"NOT (2 + 2 = 4) =",opts:["True","False"],answer:1,explain:"2+2=4 is TRUE. NOT flips it → FALSE."},
{q:"\"Raining OR snowing.\" Neither is happening.",opts:["True","False"],answer:1,explain:"OR needs at least one. Neither = false."},
{q:"\"I like apples AND oranges.\" I like apples but not oranges.",opts:["True","False"],answer:1,explain:"AND needs BOTH to be true."},
{q:"NOT (the sky is green) =",opts:["True!","False"],answer:0,explain:"The sky IS green is false. NOT flips it to true!"},
{q:"\"Sunny AND warm AND dry.\" Sunny, warm, but rainy.",opts:["True","False"],answer:1,explain:"ALL THREE must be true for AND. One false = all false!"},
{q:"\"Tall OR fast OR strong.\" You're strong but not tall or fast.",opts:["True!","False"],answer:0,explain:"OR needs just ONE! Strong counts!"},
{q:"NOT (NOT true) = ?",opts:["True! (double flip!)","False"],answer:0,explain:"Flip once = false. Flip again = true!"},
{q:"\"Happy AND kind.\" You're happy and kind.",opts:["True — both true!","False"],answer:0,explain:"Both are true, so AND gives true! ✅"},
],
match:[{left:"🟢 AND 🟢",right:"🟢 TRUE"},{left:"🟢 AND 🔴",right:"🔴 FALSE"},{left:"🔴 OR 🟢",right:"🟢 TRUE"},{left:"🔴 OR 🔴",right:"🔴 FALSE"},{left:"NOT 🟢",right:"🔴 FALSE"},{left:"NOT 🔴",right:"🟢 TRUE"},{left:"🟢 OR 🟢",right:"🟢 TRUE"},{left:"🔴 AND 🔴",right:"🔴 FALSE"}],
sort:{prompt:"Does it use AND, OR, or NOT?",categories:["AND","OR","NOT"],
items:[{text:"\"I have a dog and a cat.\"",cat:0},{text:"\"I don't like spinach.\"",cat:2},{text:"\"Monday or Tuesday.\"",cat:1},{text:"\"It's not raining.\"",cat:2},{text:"\"Smart and kind.\"",cat:0},{text:"\"Tea or juice?\"",cat:1},{text:"\"Not sleepy yet!\"",cat:2},{text:"\"Tall and fast.\"",cat:0},{text:"\"Red or blue or green.\"",cat:1},{text:"\"Not hungry.\"",cat:2}]}
},

{id:3,realm:"explorer",title:"If-Then Thinking",subtitle:"The most powerful tool!",
story:"\"Here's the biggest tool in ALL of thinking,\" the owl said. 🦉\n\n\"IF something is true, THEN something else follows.\"\n\nMaya's eyes got wide. \"Like Mom says: 'If you clean your room, THEN you can play outside'?\"\n\n\"Exactly! IF-THEN connects a REASON to a RESULT!\"",
realWorld:"🧪 Science: \"If water gets really cold, it turns to ice.\" Cooking: \"If the timer beeps, take cookies out.\" IF-THEN is everywhere!",
learn:[
{type:"concept",title:"What is If-Then?",body:"\"IF A, THEN B\" means:\nWhenever A is true, B must be true too.\n\n🌧️→☔ \"If rain, then umbrella.\"\n📚→✅ \"If study, then pass.\"\n\nIF = reason. THEN = result."},
{type:"concept",title:"When is It Broken?",body:"An If-Then is broken ONLY ONE WAY:\nThe IF happens, but the THEN doesn't.\n\n🌧️ + ☔forgot = BROKEN! 🔴\n🌧️ + ☔brought = KEPT! 🟢\n☀️ + anything = NOT BROKEN! 🟢\n\nNo rain = no promise to break!"},
{type:"example",title:"Test These!",body:"\"If you eat veggies, then you get dessert.\"\n\n🥦+🍰 → KEPT ✅\n🥦+❌ → BROKEN ❌\n❌veggies+🍰 → Not broken ✅\n❌veggies+❌ → Not broken ✅\n\nThe ONLY problem: veggies YES, dessert NO!"},
{type:"concept",title:"The Tricky Part!",body:"If the IF part is FALSE...\nthe whole If-Then is NOT broken!\n\n\"If pigs fly, I'll eat my hat.\"\nPigs don't fly.\nSo this promise is technically KEPT!\n\nYou can only break a promise\nthat got activated!"},
],
quiz:[
{q:"\"If veggies, then dessert.\" Ate veggies, got dessert.",opts:["Kept! ✅","Broken ❌"],answer:0,explain:"IF happened, THEN happened. Promise kept!"},
{q:"\"If veggies, then dessert.\" Ate veggies, NO dessert.",opts:["Kept ✅","Broken! ❌"],answer:1,explain:"IF happened but THEN didn't. Broken!"},
{q:"\"If snow, no school.\" No snow today.",opts:["Broken!","Not broken — no snow = no promise to break"],answer:1,explain:"IF didn't happen, so nothing to break!"},
{q:"If-Then is broken ONLY when:",opts:["IF is false","Both false","IF true but THEN false","Both true"],answer:2,explain:"The ONLY break: IF happens but THEN doesn't."},
{q:"\"If nice, get a sticker.\" Nice + got sticker.",opts:["Kept ✅","Broken ❌"],answer:0,explain:"IF true, THEN true. Kept!"},
{q:"\"If rain, bring umbrella.\" Sunny. No umbrella.",opts:["Kept ✅","Broken ❌"],answer:0,explain:"No rain! No promise to break."},
{q:"\"If pigs fly, I give you a million.\" Pigs don't fly.",opts:["Kept ✅ (pigs didn't fly!)","Broken ❌"],answer:0,explain:"The IF never happened!"},
{q:"\"If homework done, we get ice cream.\" Done. No ice cream.",opts:["Kept","Broken! ❌"],answer:1,explain:"IF happened, THEN didn't. Broken!"},
{q:"\"If unicorn, I scream.\" See unicorn. Scream.",opts:["Kept ✅","Broken ❌"],answer:0,explain:"IF happened, THEN happened. Kept!"},
{q:"\"If alarm, wake up.\" No alarm. Slept in.",opts:["Kept ✅","Broken ❌"],answer:0,explain:"No alarm = no promise activated."},
],
match:[{left:"IF 🟢 THEN 🟢",right:"✅ Kept!"},{left:"IF 🟢 THEN 🔴",right:"❌ Broken!"},{left:"IF 🔴 THEN 🟢",right:"✅ Not broken"},{left:"IF 🔴 THEN 🔴",right:"✅ Not broken"},{left:"Reason",right:"IF part"},{left:"Result",right:"THEN part"}],
sort:{prompt:"KEPT or BROKEN?",categories:["✅ Kept","❌ Broken"],
items:[{text:"If rain→umbrella. Rained, brought it.",cat:0},{text:"If homework→games. Did it, no games!",cat:1},{text:"If sunny→park. Cloudy, stayed home.",cat:0},{text:"If study→pass. Studied, passed!",cat:0},{text:"If clean→allowance. Cleaned, nothing!",cat:1},{text:"If bark→intruder. Dog slept.",cat:0},{text:"If bedtime→brush. Bedtime, didn't brush!",cat:1},{text:"If cold→jacket. Not cold, no jacket.",cat:0},{text:"If practice→improve. Practiced, improved!",cat:0},{text:"If promise→keep. Promised, broke it!",cat:1}]}
},

{id:4,realm:"explorer",title:"Patterns & Predictions",subtitle:"Guessing vs. knowing for sure",
story:"The owl led Maya to a garden. 🌸\n\nFlowers: 🔴🔵🔴🔵🔴...\n\n\"What's next?\" \"Blue!\" said Maya.\n\"That's INDUCTIVE reasoning — examples → guess.\nBut DEDUCTIVE uses a rule → guaranteed answer!\"",
realWorld:"🌤️ Weather people use patterns to guess rain. Scientists use rules to calculate exactly. Both useful — but one gives SURE answers!",
learn:[
{type:"concept",title:"Inductive = Examples → Guess",body:"See examples, make a guess:\n\n🦢 Swan 1: white\n🦢 Swan 2: white\n🦢 Swan 3: white\n→ \"ALL swans are white!\"\n\nBut... black swans exist! 🖤🦢\nInductive = probably right, not guaranteed."},
{type:"concept",title:"Deductive = Rule → Sure Answer",body:"Start with a rule, get a sure answer:\n\n📏 Rule: All dogs are mammals.\n🐕 Fact: Rex is a dog.\n✅ Answer: Rex is a mammal!\n\nIf rule true and fact true,\nanswer MUST be true. 100% sure!"},
{type:"example",title:"Which Type?",body:"\"Bus comes at 8 every day.\nSo bus will come at 8 tomorrow.\"\n→ 🔍 INDUCTIVE (examples → guess)\n\n\"All triangles have 3 sides.\nThis is a triangle.\nSo it has 3 sides.\"\n→ ✅ DEDUCTIVE (rule → sure answer)"},
],
quiz:[
{q:"Every Monday it rains. Predict rain next Monday.",opts:["Deductive","Inductive"],answer:1,explain:"Examples → guess = inductive!"},
{q:"All birds have feathers. Robin is a bird. Robin has feathers.",opts:["Deductive","Inductive"],answer:0,explain:"Rule → sure answer = deductive!"},
{q:"Which gives 100% sure answers?",opts:["Inductive","Deductive"],answer:1,explain:"Deductive gives guaranteed answers!"},
{q:"1, 3, 5, 7, ... What's next?",opts:["9 — pattern!","8","10"],answer:0,explain:"+2 each time = inductive!"},
{q:"All fish live in water. Nemo is a fish. Nemo lives in water.",opts:["Inductive","Deductive"],answer:1,explain:"Rule + fact = sure answer!"},
{q:"I've eaten 10 red apples. All apples must be red!",opts:["Good deduction","Bad induction — green apples exist!"],answer:1,explain:"Examples don't prove ALL!"},
{q:"All squares have 4 sides. This is a square. It has 4 sides.",opts:["Inductive","Deductive"],answer:1,explain:"Rule → guaranteed!"},
{q:"My teacher tests on Fridays. Probably a test this Friday.",opts:["Deductive","Inductive"],answer:1,explain:"Based on pattern, not rule!"},
{q:"All even numbers divide by 2. 16 is even. 16 divides by 2.",opts:["Inductive","Deductive"],answer:1,explain:"Rule + fact = 100% sure!"},
{q:"Met 20 nice Canadians. Canadians must be nice!",opts:["Good deduction","Induction — a guess from examples!"],answer:1,explain:"20 examples doesn't prove ALL!"},
],
match:[{left:"Examples → Rule",right:"Inductive 🔍"},{left:"Rule → Answer",right:"Deductive ✅"},{left:"Probably true",right:"Inductive 🔍"},{left:"Definitely true",right:"Deductive ✅"},{left:"Pattern guess",right:"Inductive 🔍"},{left:"100% sure",right:"Deductive ✅"}],
sort:{prompt:"INDUCTIVE or DEDUCTIVE?",categories:["🔍 Inductive","✅ Deductive"],
items:[{text:"100 sunrises → sun rises daily",cat:0},{text:"All fish swim. Nemo is a fish. Nemo swims.",cat:1},{text:"Snows every winter → snow this winter",cat:0},{text:"All squares have 4 sides. This square has 4.",cat:1},{text:"5 friends like pizza → everyone likes pizza",cat:0},{text:"All cats have whiskers. Luna is a cat.",cat:1},{text:"Always hungry at noon → hungry tomorrow noon",cat:0},{text:"All mammals breathe air. Whale is mammal.",cat:1}]}
},

{id:5,realm:"explorer",title:"Good Arguments",subtitle:"Does the answer really follow?",
story:"\"An ARGUMENT in logic isn't a fight!\" the owl said. 🦉\n\n\"It's REASONS + a CONCLUSION.\"\n\nMaya tried:\n\"All fish live in water.\nGoldie is a fish.\nSo Goldie lives in water!\"\n\n\"Perfect! That's VALID — the conclusion HAS to follow!\"",
realWorld:"📺 Commercials try to convince you with bad arguments. Spotting them is a superpower!",
learn:[
{type:"concept",title:"What is an Argument?",body:"Two parts:\n\n📋 REASONS (premises):\n  All mammals breathe air.\n  Whales are mammals.\n\n🎯 CONCLUSION:\n  So whales breathe air!\n\nReasons + conclusion = argument."},
{type:"concept",title:"Valid = Must Follow",body:"VALID: if reasons true, conclusion MUST be true.\n\n✅ All dogs bark. Rex is a dog. Rex barks.\n(MUST follow!)\n\n❌ All dogs bark. Rex barks. Rex is a dog.\n(Seals bark too! Doesn't follow!)"},
{type:"concept",title:"Sound = Valid + True Reasons 🏆",body:"SOUND = the best kind.\n\nValid but silly:\n  All cats are green. (WRONG!)\n  Fluffy is a cat.\n  So Fluffy is green.\nLogic works — but cats aren't green!\n\nSOUND means logic works AND reasons are true."},
{type:"example",title:"Test Yourself!",body:"\"All birds fly. Penguins are birds. Penguins fly.\"\n→ VALID but NOT SOUND (not all birds fly!)\n\n\"All dogs are mammals. Rex is a dog. Rex is a mammal.\"\n→ VALID and SOUND! 🏆"},
],
quiz:[
{q:"All cats are purple. Tom is a cat. Tom is purple.",opts:["Valid AND true","Valid but silly reasons","Not valid"],answer:1,explain:"Logic works, but cats aren't purple!"},
{q:"All dogs bark. Rex barks. So Rex is a dog. Valid?",opts:["Yes!","No — Rex could be something else!"],answer:1,explain:"Other things bark too!"},
{q:"Best kind of argument:",opts:["Valid","True reasons","Sound (valid + true!) 🏆","Long"],answer:2,explain:"Sound = valid logic + true reasons!"},
{q:"All birds fly. Penguins are birds. Penguins fly.",opts:["Sound","Valid but not sound","Invalid"],answer:1,explain:"Logic works, but not all birds fly!"},
{q:"All candy is sweet. This is candy. It's sweet.",opts:["Valid","Invalid"],answer:0,explain:"IF all candy sweet and this is candy, MUST be sweet!"},
{q:"Some dogs are big. Rex is a dog. Rex is big.",opts:["Valid","Invalid"],answer:1,explain:"SOME doesn't mean Rex is!"},
{q:"All mammals have hearts. Dogs are mammals. Dogs have hearts.",opts:["Valid and sound! 🏆","Valid but not sound","Invalid"],answer:0,explain:"Logic works AND reasons are true!"},
{q:"All apples are blue. This is an apple. It's blue.",opts:["Sound","Valid but not sound","Invalid"],answer:1,explain:"Logic fine, but apples aren't blue!"},
{q:"All students study. All who study pass. Students pass.",opts:["Valid","Invalid"],answer:0,explain:"Chain works! Students→study→pass."},
{q:"Most birds fly. Tweety is a bird. Tweety flies.",opts:["Valid","Invalid"],answer:1,explain:"MOST doesn't mean ALL!"},
],
match:[{left:"Reasons + Conclusion",right:"Argument"},{left:"Conclusion must follow",right:"Valid ✅"},{left:"Valid + true reasons",right:"Sound 🏆"},{left:"Doesn't follow",right:"Invalid ❌"},{left:"Logic works, facts wrong",right:"Valid not sound"},{left:"Logic works, facts right",right:"Sound 🏆"},{left:"The reasons",right:"Premises"},{left:"The answer",right:"Conclusion"}],
sort:{prompt:"VALID or INVALID?",categories:["✅ Valid","❌ Invalid"],
items:[{text:"All A are B. X is A. So X is B.",cat:0},{text:"All A are B. X is B. So X is A.",cat:1},{text:"No A are B. X is A. So X is not B.",cat:0},{text:"Some A are B. X is A. So X is B.",cat:1},{text:"If A then B. A is true. So B.",cat:0},{text:"If A then B. B is true. So A.",cat:1},{text:"All A are B. All B are C. All A are C.",cat:0},{text:"Most A are B. X is A. So X is B.",cat:1}]}
},

{id:6,realm:"explorer",title:"Tricky Arguments!",subtitle:"Sneaky bad arguments called 'fallacies'",
story:"Maya noticed arguments that SOUNDED good but had tricks! 🃏\n\nHer friend: \"Everyone's buying this game. MUST be the best!\"\n\nThe owl: \"That's a FALLACY — a sneaky bad argument!\" 🦉",
realWorld:"📺 Ads use fallacies ALL the time! Once you spot these tricks, you can't be fooled!",
learn:[
{type:"concept",title:"Attack the Person (Ad Hominem)",body:"Attack the PERSON instead of their argument.\n\n❌ \"You're just a kid, so your idea is bad!\"\n\nBeing a kid doesn't make an idea wrong!\nAttack the IDEA, not the PERSON."},
{type:"concept",title:"Straw Man",body:"Change what someone said to attack it easier.\n\n🧑 \"We should have less homework.\"\n👎 \"So you think we should NEVER learn?!\"\n\nThat's NOT what they said!"},
{type:"concept",title:"Bandwagon",body:"\"True because lots of people think so!\"\n\n❌ \"A million people bought it, must be best!\"\n\nLots of people can be wrong!"},
{type:"concept",title:"False Choice",body:"Pretend only two options exist.\n\n❌ \"You're either with us or against us!\"\n\nWhat about partly agreeing?"},
{type:"concept",title:"Red Herring 🐟",body:"Change the subject to dodge the question.\n\n\"Why didn't you do homework?\"\n\"Well SOME kids never do ANY!\"\n\nDoesn't answer the question!"},
],
quiz:[
{q:"\"You like recycling? Well YOU drove here!\"",opts:["Good point","Attack the Person","Straw Man","False Choice"],answer:1,explain:"Attacks the person, not the argument!"},
{q:"\"Love this restaurant or you hate pizza.\"",opts:["Bandwagon","Straw Man","Attack Person","False Choice"],answer:3,explain:"Way more than two options!"},
{q:"\"Everyone has this backpack. Must be best.\"",opts:["Good argument","Bandwagon","Straw Man","Attack Person"],answer:1,explain:"Popular doesn't mean best!"},
{q:"\"So you want to CANCEL all tests?!\" (said shorter tests)",opts:["Attack Person","False Choice","Bandwagon","Straw Man"],answer:3,explain:"Changed what they said!"},
{q:"\"You failed math, so your science idea is wrong.\"",opts:["Attack Person","Straw Man","Bandwagon","Valid"],answer:0,explain:"Math grades ≠ science ideas!"},
{q:"\"Everyone in class agrees with me!\"",opts:["Good point","Bandwagon","False Choice","Straw Man"],answer:1,explain:"Everyone could be wrong!"},
{q:"\"Why are you late?\" \"At least I came! Some kids skip!\"",opts:["Good answer","Red Herring!"],answer:1,explain:"Doesn't answer WHY late!"},
{q:"\"You're not a scientist, so you're wrong.\"",opts:["Fair point","Attack the Person!"],answer:1,explain:"Non-scientists can be right!"},
{q:"\"Support my plan 100% or you want it to fail!\"",opts:["Makes sense","False Choice!"],answer:1,explain:"Could partly support, suggest changes..."},
{q:"\"So you think students should have NO rules?\" (said fewer)",opts:["Good summary","Straw Man!"],answer:1,explain:"Fewer ≠ none!"},
],
match:[{left:"Attack who said it",right:"Ad Hominem"},{left:"Change what they said",right:"Straw Man"},{left:"Everyone believes it!",right:"Bandwagon"},{left:"Only two options",right:"False Choice"},{left:"Change the subject",right:"Red Herring 🐟"}],
sort:{prompt:"Which fallacy?",categories:["Attack Person","Straw Man","Bandwagon","False Choice"],
items:[{text:"\"You failed, so your idea is bad.\"",cat:0},{text:"\"So you want NO rules?!\"",cat:1},{text:"\"All my friends think so!\"",cat:2},{text:"\"Love it or leave!\"",cat:3},{text:"\"You're too young to understand.\"",cat:0},{text:"\"So you want candy all day?!\"",cat:1},{text:"\"Millions can't be wrong!\"",cat:2},{text:"\"Join us or be our enemy.\"",cat:3}]}
},

// 🌿 SPROUTS — Building Blocks (Units 7-10)

{id:7,realm:"adventurer",title:"Secret Code for Logic",subtitle:"Symbols instead of words!",
story:"Maya learned logicians invented a SECRET CODE! 🔐\n\n∧ = AND, ∨ = OR, ¬ = NOT, → = IF-THEN\n\n\"Less writing, more thinking!\" 🦉",
realWorld:"💻 Every computer speaks this! Every app, game, website runs on these symbols.",
learn:[
{type:"concept",title:"The Symbol Key 🔑",body:"p, q, r = any statements\n\n¬p = NOT p (flip it!)\np ∧ q = p AND q (both!)\np ∨ q = p OR q (at least one!)\np → q = IF p THEN q\n\nJust 4 symbols! 🎉"},
{type:"concept",title:"Memory Tricks!",body:"∧ looks like A (AND!) — tip it: ∧ → A\n∨ looks like a cup catching anything — OR!\n¬ is a flag waving NO!\n→ is an arrow: IF this → THEN that!"},
{type:"concept",title:"English → Symbols",body:"\"Raining and cold\" → p ∧ q\n\"If study, then pass\" → p → q\n\"Not sunny\" → ¬p\n\"Happy or sad\" → p ∨ q"},
{type:"example",title:"Your Turn!",body:"\"Not hungry\" → ¬p\n\"Tall and strong\" → p ∧ q\n\"Not (hot and humid)\" → ¬(p ∧ q)\n\"Red or blue\" → p ∨ q"},
{type:"concept",title:"Truth Table — Cheat Sheet!",body:"p | q | p ∧ q | p ∨ q\n🟢|🟢|  🟢  |  🟢\n🟢|🔴|  🔴  |  🟢\n🔴|🟢|  🔴  |  🟢\n🔴|🔴|  🔴  |  🔴\n\nAND = both green. OR = at least one!"},
],
quiz:[
{q:"p ∨ q means:",opts:["p AND q","p OR q","NOT p","IF p THEN q"],answer:1,explain:"∨ = OR!"},
{q:"\"If rain, stay home\" in symbols:",opts:["p ∧ q","p ∨ q","p → q","¬p"],answer:2,explain:"→ = IF...THEN."},
{q:"¬p means:",opts:["p AND something","NOT p","p OR something","IF p"],answer:1,explain:"¬ flips p!"},
{q:"p → q is FALSE when:",opts:["p false, q true","p true, q false","Both false","Both true"],answer:1,explain:"Only broken when IF true but THEN false!"},
{q:"\"Happy AND tired\" in symbols:",opts:["p ∨ q","p → q","p ∧ q","¬p"],answer:2,explain:"∧ = AND."},
{q:"What does ∧ mean?",opts:["OR","NOT","AND","IF-THEN"],answer:2,explain:"∧ = AND!"},
{q:"p TRUE, q FALSE. p ∨ q?",opts:["TRUE!","FALSE"],answer:0,explain:"OR: at least one! p is true."},
{q:"p TRUE, q FALSE. p ∧ q?",opts:["TRUE","FALSE!"],answer:1,explain:"AND: need both. q is false."},
{q:"¬(¬p) means:",opts:["Just p! (double flip)","NOT p","p AND p"],answer:0,explain:"Double NOT cancels!"},
{q:"\"Not raining or cold\" in symbols:",opts:["¬p ∨ q","¬(p ∨ q)","p ∧ ¬q"],answer:0,explain:"(NOT raining) OR (cold) = ¬p ∨ q!"},
],
match:[{left:"∧",right:"AND"},{left:"∨",right:"OR"},{left:"¬",right:"NOT"},{left:"→",right:"IF-THEN"},{left:"p ∧ q",right:"Both true"},{left:"p ∨ q",right:"At least one"},{left:"¬p",right:"Flip p"},{left:"p → q",right:"IF p THEN q"}],
sort:{prompt:"Which symbol?",categories:["∧ (AND)","∨ (OR)","→ (IF-THEN)","¬ (NOT)"],
items:[{text:"Hot and humid",cat:0},{text:"Bus or walk",cat:1},{text:"If I call, you answer",cat:2},{text:"Not Friday",cat:3},{text:"Brave and kind",cat:0},{text:"Red or blue",cat:1},{text:"If bedtime, brush teeth",cat:2},{text:"Not sleepy",cat:3},{text:"Tall and fast",cat:0},{text:"Cake or pie",cat:1}]}
},

{id:8,realm:"adventurer",title:"Certified Moves",subtitle:"Rules that NEVER go wrong!",
story:"The owl taught Maya special MOVES. 🎯\n\n\"These have worked 2,000+ years! They NEVER give a wrong answer!\"\n\n\"Never ever?\" \"Never ever!\" 🦉",
realWorld:"🩺 Doctors: \"If strep → fever. No fever → NOT strep.\" Scientists, detectives, lawyers — all use these!",
learn:[
{type:"concept",title:"Move 1: Modus Ponens 👑",body:"The KING of moves!\n\nIF A THEN B. (rule)\nA is true. (happened)\nSo B is true! (guaranteed!)\n\n🌧️ If rain → wet.\nIt's raining.\n💧 Ground is wet! ✅"},
{type:"concept",title:"Move 2: Modus Tollens 🔄",body:"The REVERSE move!\n\nIF A THEN B. (rule)\nB is NOT true. (didn't happen)\nSo A is NOT true!\n\n🌧️ If rain → wet.\n🏜️ NOT wet.\n☀️ Did NOT rain! ✅"},
{type:"concept",title:"Move 3: Chain Rule ⛓️",body:"Connect two IF-THENs!\n\nIf A then B.\nIf B then C.\nSo if A then C! ✅\n\n📚→✅→🎓\nStudy→pass→graduate!"},
{type:"concept",title:"Move 4: Elimination 🚫",body:"Cross one out!\n\nA or B.\nNot A.\nSo B! ✅\n\n🔑 Keys: pocket or table.\n🚫 Not pocket.\n📍 On the table! ✅"},
{type:"example",title:"Quick Practice!",body:"\"If alarm → wake up. Alarm rang.\"\n→ Modus Ponens! 👑\n\n\"If guilty → evidence. No evidence.\"\n→ Modus Tollens! 🔄\n\n\"Pizza or pasta. Not pizza.\"\n→ Elimination! 🚫"},
],
quiz:[
{q:"\"Snow → closed. Snowed. Closed.\" Which move?",opts:["Modus Ponens 👑","Modus Tollens 🔄","Chain ⛓️","Elimination 🚫"],answer:0,explain:"Rule + happened → result!"},
{q:"\"Snow → closed. NOT closed. NOT snow.\"",opts:["Modus Ponens","Modus Tollens 🔄","Chain","Elimination"],answer:1,explain:"Rule + didn't happen → reason didn't happen!"},
{q:"\"Inside or outside. Not inside. Outside.\"",opts:["Ponens","Tollens","Chain","Elimination 🚫"],answer:3,explain:"A or B + not A → B!"},
{q:"A→B and B→C gives:",opts:["A→C ✅","C→A","B→A"],answer:0,explain:"Chain! A→B→C = A→C!"},
{q:"\"Alarm → wake up. Alarm rang.\"",opts:["Modus Ponens 👑","Modus Tollens","Chain","Elimination"],answer:0,explain:"Rule + happened = result!"},
{q:"\"Guilty → evidence. No evidence.\"",opts:["Ponens","Modus Tollens 🔄","Chain","Elimination"],answer:1,explain:"Rule + result didn't happen!"},
{q:"\"Cat or dog. Not cat. So dog.\"",opts:["Ponens","Tollens","Chain","Elimination 🚫"],answer:3,explain:"A or B, not A → B!"},
{q:"\"Eat cake → happy. Happy → smile. Eat cake → smile.\"",opts:["Ponens","Tollens","Chain ⛓️","Elimination"],answer:2,explain:"Two IF-THENs chained!"},
{q:"\"Battery dies → phone off. Phone ON.\"",opts:["Battery died","Battery did NOT die! (Tollens)"],answer:1,explain:"Phone on = not off. So battery alive!"},
{q:"\"Red or blue or green. Not red. Not green.\"",opts:["Blue! (Elimination)","Can't tell"],answer:0,explain:"Cross out red and green. Blue left!"},
],
match:[{left:"p→q, p ∴ q",right:"Modus Ponens 👑"},{left:"p→q, ¬q ∴ ¬p",right:"Modus Tollens 🔄"},{left:"p→q, q→r ∴ p→r",right:"Chain ⛓️"},{left:"p∨q, ¬p ∴ q",right:"Elimination 🚫"},{left:"Rule + happened",right:"Modus Ponens"},{left:"Rule + didn't happen",right:"Modus Tollens"}],
sort:{prompt:"Which move?",categories:["Modus Ponens 👑","Modus Tollens 🔄","Chain ⛓️","Elimination 🚫"],
items:[{text:"Bark→intruder. Barked. Intruder!",cat:0},{text:"Guilty→evidence. No evidence. Not guilty.",cat:1},{text:"Rain→flood→evacuate. Rain→evacuate.",cat:2},{text:"Left or right. Not left. Right!",cat:3},{text:"Study→pass. Studied! Passed.",cat:0},{text:"Fire→smoke. No smoke. No fire!",cat:1},{text:"A→B, B→C. So A→C!",cat:2},{text:"Cat or dog. Not cat. Dog!",cat:3},{text:"Practice→improve. Practiced! Improved!",cat:0},{text:"Broke→sad. Not sad. Not broke!",cat:1}]}
},

{id:9,realm:"adventurer",title:"Groups & Circles",subtitle:"Sets and Venn diagrams",
story:"Maya's teacher drew overlapping circles. ⭕⭕\n\n\"These are VENN DIAGRAMS! They show how groups relate.\"\n\n\"All dogs are mammals means dogs fit INSIDE mammals!\" 📦",
realWorld:"📚 Libraries sort books. 🏥 Doctors find patients 'diabetic AND over 65.' Your phone sorts photos. All groups!",
learn:[
{type:"concept",title:"What is a Set?",body:"A SET is a group of things.\n\n🟡 A = {apple, banana, cherry}\n🔵 B = {banana, cherry, date}\n\nbanana ∈ A (∈ = 'is in')"},
{type:"concept",title:"Intersection ∩ = AND",body:"∩ = in BOTH groups.\n\nA = {1, 2, 3, 4}\nB = {3, 4, 5, 6}\n\nA ∩ B = {3, 4} 🎯"},
{type:"concept",title:"Union ∪ = OR",body:"∪ = in EITHER group.\n\nA = {1, 2, 3}\nB = {3, 4, 5}\n\nA ∪ B = {1, 2, 3, 4, 5} 🎒"},
{type:"concept",title:"Subset ⊂ = Inside",body:"⊂ = one fits INSIDE another.\n\n🐕 {dogs} ⊂ {mammals}\nEvery dog IS a mammal!\n\n⬛ {squares} ⊂ {rectangles}"},
{type:"concept",title:"Empty Set ∅",body:"Sometimes nothing fits!\n\nA={cats} B={fish}\nA ∩ B = ∅ (nothing!)\n\nNothing is both cat AND fish!"},
],
quiz:[
{q:"A={1,2,3,4} B={3,4,5,6}. A ∩ B = ?",opts:["{1,2,3,4,5,6}","{3,4}","{1,2}"],answer:1,explain:"∩ = both. Only 3 and 4!"},
{q:"A={a,b,c} B={c,d,e}. A ∪ B = ?",opts:["{c}","{a,b,c,d,e}","{a,b,d,e}"],answer:1,explain:"∪ = everything from both!"},
{q:"\"All roses are flowers\" means:",opts:["Roses ∩ Flowers = ∅","Roses ⊂ Flowers","Flowers ⊂ Roses"],answer:1,explain:"Roses fit INSIDE flowers!"},
{q:"∈ means:",opts:["Is NOT in","AND","Is a member of"],answer:2,explain:"∈ = 'is in the group!'"},
{q:"A={🐱,🐕} B={🐕,🐟}. A ∩ B = ?",opts:["{🐱,🐕,🐟}","{🐕}","{🐱,🐟}"],answer:1,explain:"Only 🐕 in both!"},
{q:"A ⊂ B means everything in A is in:",opts:["B","Only A","Neither"],answer:0,explain:"Subset = A inside B!"},
{q:"A={1,2,3} B={4,5,6}. A ∩ B = ?",opts:["{1,2,3,4,5,6}","∅ (nothing!)"],answer:1,explain:"No overlap! Empty set!"},
{q:"A={red,blue} B={blue,green}. A ∪ B = ?",opts:["{blue}","{red,blue,green}"],answer:1,explain:"Everything from both!"},
{q:"{squares} ⊂ {rectangles} means:",opts:["All rectangles are squares","All squares are rectangles"],answer:1,explain:"Squares inside rectangles!"},
{q:"A={1,2,3} B={1,2,3,4,5}. A ⊂ B?",opts:["Yes!","No"],answer:0,explain:"Everything in A is in B!"},
],
match:[{left:"A ∩ B",right:"In BOTH"},{left:"A ∪ B",right:"In EITHER"},{left:"A ⊂ B",right:"A inside B"},{left:"∈",right:"Is a member"},{left:"∅",right:"Empty set"},{left:"∩",right:"AND for groups"},{left:"∪",right:"OR for groups"},{left:"{dogs} ⊂ {mammals}",right:"All dogs are mammals"}],
sort:{prompt:"∩ (AND), ∪ (OR), or ⊂ (inside)?",categories:["Intersection ∩","Union ∪","Subset ⊂"],
items:[{text:"BOTH soccer AND basketball",cat:0},{text:"Soccer OR basketball",cat:1},{text:"All puppies are dogs",cat:2},{text:"BOTH chocolate AND vanilla",cat:0},{text:"Fridge or pantry",cat:1},{text:"Every square is rectangle",cat:2},{text:"Friends in BOTH classes",cat:0},{text:"Anyone in math OR science",cat:1}]}
},

{id:10,realm:"adventurer",title:"All, Some, None",subtitle:"How many are we talking about?",
story:"\"ALL, SOME, NONE are very different!\" the owl warned. 🦉\n\n\"ALL = big promise. SOME = small promise.\"\n\"To BREAK a big promise, one exception is enough!\"",
realWorld:"📝 'ALL students must...' vs 'SOME students may...' These words matter in law, science, and life!",
learn:[
{type:"concept",title:"∀ — For ALL",body:"∀ = EVERY single one.\n\n∀ dogs are mammals.\n\nTo break it? ONE dog that isn't! 🔍\nOne exception kills ALL!"},
{type:"concept",title:"∃ — There Exists",body:"∃ = at least one.\n\n∃ a brown dog.\n\nTo prove it? Find ONE! 🐕\nOne example is enough!"},
{type:"concept",title:"Flipping ALL and SOME",body:"NOT ALL = at least one doesn't\nNOT SOME = none at all\n\n\"Not all passed\" = someone didn't\n\"Not even one\" = nobody\n\nNOT flips ALL↔SOME! 🪄"},
{type:"example",title:"Real Examples",body:"\"All birds fly.\"\nPenguin can't! → BROKEN ❌\n\n\"Some birds swim.\"\nDucks swim! → PROVED ✅"},
],
quiz:[
{q:"\"All birds fly.\" Penguin can't.",opts:["True","False!"],answer:1,explain:"ONE exception breaks ALL!"},
{q:"\"At least one cat is orange\" means:",opts:["All cats orange","One orange cat exists!"],answer:1,explain:"∃ = at least one!"},
{q:"Opposite of 'All students passed':",opts:["No students passed","At least one didn't pass"],answer:1,explain:"NOT ALL = at least one didn't!"},
{q:"To break an ALL claim you need:",opts:["Lots of examples","Just ONE exception"],answer:1,explain:"ONE breaks ALL!"},
{q:"To prove a SOME claim you need:",opts:["Every example","Just ONE example"],answer:1,explain:"One is enough!"},
{q:"\"All cats have tails.\" Manx has no tail.",opts:["Claim true","Claim false!"],answer:1,explain:"One exception!"},
{q:"\"No reptiles have fur.\" Find a furry one.",opts:["Claim holds","Claim broken!"],answer:1,explain:"One exception breaks 'no' too!"},
{q:"\"Some dogs weigh 100+ lbs.\" True?",opts:["Yes — Great Danes!","No"],answer:0,explain:"One example proves SOME!"},
{q:"NOT (∃ purple elephant) means:",opts:["All elephants purple","No purple elephants!"],answer:1,explain:"NOT some = none!"},
{q:"\"∀ students study.\" One doesn't.",opts:["Still true","False!"],answer:1,explain:"One exception breaks ALL!"},
],
match:[{left:"∀",right:"For ALL"},{left:"∃",right:"At least one"},{left:"One exception breaks",right:"∀ claims"},{left:"One example proves",right:"∃ claims"},{left:"NOT all",right:"At least one doesn't"},{left:"NOT any",right:"None at all"},{left:"Big promise",right:"ALL ∀"},{left:"Small promise",right:"SOME ∃"}],
sort:{prompt:"ALL (∀) or SOME (∃)?",categories:["ALL ∀","SOME ∃"],
items:[{text:"Every human needs water",cat:0},{text:"Some speak 3 languages",cat:1},{text:"All triangles: 3 sides",cat:0},{text:"A number > 100 exists",cat:1},{text:"All evens divide by 2",cat:0},{text:"Some mammals fly (bats!)",cat:1},{text:"Every square: 4 equal sides",cat:0},{text:"A country with no army exists",cat:1}]}
},

// 🌳 BRANCHES — Putting It Together (Units 11-13)

{id:11,realm:"scholar",title:"The Complete Toolbox",subtitle:"Rules for perfect logic sentences",
story:"\"Logic has grammar rules too!\" the owl said. 🦉\n\n\"Sentences that follow ALL rules are 'well-formed.' Ones that break rules are gibberish!\"",
realWorld:"💻 Computers need PERFECT grammar. One mistake = crash! Logic grammar keeps everything working.",
learn:[
{type:"concept",title:"De Morgan's Magic 🪄",body:"NOT flips AND↔OR!\n\n¬(p∧q) = ¬p ∨ ¬q\nNOT(A AND B) = NOT-A OR NOT-B\n\n¬(p∨q) = ¬p ∧ ¬q\nNOT(A OR B) = NOT-A AND NOT-B\n\n\"Not (rain AND cold)\"\n= \"Not rain OR not cold!\""},
{type:"concept",title:"Tautology & Contradiction",body:"TAUTOLOGY = always true!\n🟢 \"Raining OR not raining.\"\n\nCONTRADICTION = never true!\n🔴 \"Raining AND not raining.\"\n\nCONTINGENT = sometimes!\n🟡 \"It's raining.\" (depends!)"},
{type:"concept",title:"Contrapositive 🔄",body:"\"If A then B\" = \"If NOT B then NOT A\"\n\n\"If rain → wet.\"\nSame as: \"If NOT wet → NOT rain.\"\n\nFlip AND negate! Always works!"},
],
quiz:[
{q:"NOT (A AND B) = ?",opts:["NOT A AND NOT B","NOT A OR NOT B"],answer:1,explain:"De Morgan's: AND→OR!"},
{q:"Always true:",opts:["p AND q","p → p","p AND NOT p"],answer:1,explain:"If p then p — always!"},
{q:"Contrapositive of 'If rain, wet':",opts:["If wet, rain","If NOT wet, NOT rain","If no rain, not wet"],answer:1,explain:"Flip and negate!"},
{q:"p AND NOT p is:",opts:["Tautology","Contradiction","Contingent"],answer:1,explain:"Can't be both!"},
{q:"NOT(sunny OR warm) = ?",opts:["NOT sunny AND NOT warm","NOT sunny OR NOT warm"],answer:0,explain:"De Morgan's: OR→AND!"},
{q:"\"Monday or not Monday\" is:",opts:["Tautology!","Contradiction","Depends"],answer:0,explain:"Always true!"},
{q:"Contrapositive of 'If student, studies':",opts:["If studies, student","If NOT studies, NOT student"],answer:1,explain:"Flip and negate!"},
{q:"¬(p ∧ q) = ?",opts:["¬p ∧ ¬q","¬p ∨ ¬q"],answer:1,explain:"De Morgan's! AND→OR!"},
{q:"p ∨ ¬p is:",opts:["Tautology!","Contradiction","Contingent"],answer:0,explain:"One must be true!"},
{q:"\"If happy, smile\" same as:",opts:["If smile, happy","If NOT smile, NOT happy"],answer:1,explain:"Contrapositive!"},
],
match:[{left:"¬(p∧q)",right:"¬p ∨ ¬q"},{left:"¬(p∨q)",right:"¬p ∧ ¬q"},{left:"p→q same as",right:"¬q→¬p"},{left:"Always true",right:"Tautology"},{left:"Never true",right:"Contradiction"},{left:"Sometimes",right:"Contingent"},{left:"De Morgan's",right:"NOT flips AND↔OR"},{left:"Contrapositive",right:"Flip and negate"}],
sort:{prompt:"Tautology, Contradiction, or Contingent?",categories:["Always True!","Never True!","Sometimes"],
items:[{text:"p OR NOT p",cat:0},{text:"p AND NOT p",cat:1},{text:"p → q",cat:2},{text:"Sunny or not sunny",cat:0},{text:"Asleep and awake",cat:1},{text:"It's raining",cat:2},{text:"If A then A",cat:0},{text:"Happy and not happy",cat:1},{text:"2+2=4 OR 2+2=5",cat:0},{text:"The sky is blue",cat:2}]}
},

{id:12,realm:"scholar",title:"Talking About Things",subtitle:"Logic about objects (predicate logic!)",
story:"\"So far we say 'It's raining.' But what about 'ALL dogs are mammals'?\"\n\n\"We need logic about THINGS!\" 🦉",
realWorld:"🔍 Search: 'Italian restaurants near me rated 4+ stars' = predicate logic! Databases, AI, search engines use this!",
learn:[
{type:"concept",title:"Predicates = Properties",body:"A predicate says something ABOUT a thing.\n\nDog(x) = \"x is a dog\"\nTall(x) = \"x is tall\"\nLoves(x,y) = \"x loves y\"\n\nDog(Rex) = \"Rex is a dog\" ✅"},
{type:"concept",title:"∀ and ∃ with Predicates",body:"\"Every dog is mammal\"\n∀x(Dog(x) → Mammal(x))\n\n\"Some cats are orange\"\n∃x(Cat(x) ∧ Orange(x))\n\nALL uses →, SOME uses ∧!"},
{type:"concept",title:"ORDER MATTERS! ⚠️",body:"∀x ∃y Loves(x,y)\n= \"Everyone loves SOMEONE.\"\n\n∃y ∀x Loves(x,y)\n= \"Someone is loved by ALL.\"\n\nTotally different!"},
],
quiz:[
{q:"∀x ∃y Loves(x,y) means:",opts:["One person everyone loves","Everyone loves SOMEONE","Nobody loves"],answer:1,explain:"For ALL x, EXISTS some y!"},
{q:"'No reptiles are mammals':",opts:["∀x(R(x)→M(x))","∀x(R(x)→¬M(x))"],answer:1,explain:"If reptile, NOT mammal!"},
{q:"Switching ∀ and ∃ changes meaning?",opts:["Yes!","No"],answer:0,explain:"Totally different!"},
{q:"\"Some birds swim\":",opts:["∀x(Bird→Swim)","∃x(Bird(x) ∧ Swim(x))"],answer:1,explain:"SOME = ∃ with ∧!"},
{q:"Dog(Fido) means:",opts:["All dogs are Fido","Fido is a dog"],answer:1,explain:"Predicate applied to Fido!"},
{q:"∀x(Student(x)→Studies(x)) means:",opts:["Some study","All students study"],answer:1,explain:"For ALL: if student, studies!"},
{q:"ALL statements use which connector?",opts:["∧","→"],answer:1,explain:"ALL: if X then Y."},
{q:"SOME statements use which connector?",opts:["∧","→"],answer:0,explain:"SOME: exists X AND Y."},
{q:"∃y ∀x Loves(x,y) means:",opts:["Everyone loves someone","One person EVERYONE loves!"],answer:1,explain:"One y ALL x love!"},
{q:"\"All mammals breathe air\":",opts:["∃x(M(x)∧B(x))","∀x(M(x)→B(x))"],answer:1,explain:"ALL: if mammal, breathes!"},
],
match:[{left:"Tall(x)",right:"x is tall"},{left:"Loves(x,y)",right:"x loves y"},{left:"∀x∃y",right:"For each x, some y"},{left:"∃y∀x",right:"One y for ALL x"},{left:"ALL uses →",right:"∀x(A→B)"},{left:"SOME uses ∧",right:"∃x(A∧B)"},{left:"∀",right:"For every"},{left:"∃",right:"There exists"}],
sort:{prompt:"Simple or predicate logic?",categories:["Simple (p,q)","Predicate (things!)"],
items:[{text:"p ∧ q → r",cat:0},{text:"∀x(Dog(x)→Barks(x))",cat:1},{text:"¬p ∨ q",cat:0},{text:"∃x(Prime(x)∧Even(x))",cat:1},{text:"(p→q) ∧ (q→r)",cat:0},{text:"Loves(Romeo,Juliet)",cat:1},{text:"p ∨ ¬p",cat:0},{text:"∀x∃y Greater(x,y)",cat:1}]}
},

{id:13,realm:"scholar",title:"Ways to Prove Things",subtitle:"Direct proof, contradiction, dominoes!",
story:"\"Different PATHS to prove things true!\" 🦉\n\n\"Walk straight (direct). Assume opposite, crash (contradiction). Or knock infinite dominoes (induction)!\" 🎳",
realWorld:"🔐 Passwords are safe because math is PROVED. Bridges hold because engineers PROVED it. Proof = certainty!",
learn:[
{type:"concept",title:"Direct Proof ➡️",body:"Walk straight to the answer.\n\nEven + even = even.\n2a + 2b = 2(a+b) = even! ✅"},
{type:"concept",title:"Contradiction 💥",body:"Assume opposite. Show it crashes.\n\n\"No biggest prime.\"\nAssume biggest exists.\nMultiply all + 1.\nNew number breaks rules! 💥"},
{type:"concept",title:"Induction 🎳",body:"For ALL numbers:\n\n1️⃣ BASE: Works for first.\n2️⃣ STEP: If works for n, works for n+1.\n\nFirst domino + chain = ALL fall! ♾️"},
{type:"example",title:"When to Use What?",body:"Direct ➡️: \"Show equals that.\"\nContradiction 💥: \"Prove impossible.\"\nInduction 🎳: \"Prove for ALL numbers.\""},
],
quiz:[
{q:"Contradiction starts by:",opts:["Assuming what to prove","Assuming OPPOSITE"],answer:1,explain:"Assume opposite, crash!"},
{q:"Induction needs:",opts:["Just first domino","BOTH domino AND chain!"],answer:1,explain:"First + chain = all!"},
{q:"Direct proof goes:",opts:["End → Start","Start → End"],answer:1,explain:"Walk straight!"},
{q:"Which is like dominoes?",opts:["Direct","Contradiction","Induction! 🎳"],answer:2,explain:"Dominoes = induction!"},
{q:"Assume opposite, find impossible. Proved:",opts:["Opposite true","Original claim true!"],answer:1,explain:"If opposite impossible, claim true!"},
{q:"Prove formula for ALL n:",opts:["Direct","Contradiction","Induction!"],answer:2,explain:"ALL numbers = dominoes!"},
{q:"\"√2 not a fraction.\" Best method?",opts:["Direct","Contradiction! 💥","Induction"],answer:1,explain:"Assume fraction, crash!"},
{q:"'Base case' in induction:",opts:["First domino!","Chain reaction","Conclusion"],answer:0,explain:"Base = first one works!"},
{q:"\"n² + n always even.\" Could use:",opts:["Direct","Induction","Either!"],answer:2,explain:"Multiple paths work!"},
{q:"Base AND step in induction →",opts:["First 100 work","ALL work! ♾️"],answer:1,explain:"All dominoes fall!"},
],
match:[{left:"Assume opposite → crash",right:"Contradiction 💥"},{left:"Step by step",right:"Direct ➡️"},{left:"Base + step = all",right:"Induction 🎳"},{left:"First domino",right:"Base case"},{left:"Each knocks next",right:"Inductive step"},{left:"Reductio ad absurdum",right:"Contradiction 💥"}],
sort:{prompt:"Which proof method?",categories:["Direct ➡️","Contradiction 💥","Induction 🎳"],
items:[{text:"Odd → odd+1 even (show it!)",cat:0},{text:"No biggest prime (assume...crash!)",cat:1},{text:"1+2+...+n = n(n+1)/2 for ALL n",cat:2},{text:"√3 not fraction (assume...crash!)",cat:1},{text:"Sum first n odds = n²",cat:2},{text:"Product of two odds is odd",cat:0},{text:"No smallest positive fraction",cat:1},{text:"2ⁿ > n for all n ≥ 1",cat:2}]}
},

// 🌲 DEEP ROOTS — The Big Questions (Units 14-15)

{id:14,realm:"philosopher",title:"Can Logic Check Itself?",subtitle:"Gödel's surprise!",
story:"\"Can a robot check its OWN homework?\" 🦉\n\n\"Kurt Gödel found out in 1931. The answer SHOCKED the world!\"",
realWorld:"🤖 Can AI check if its own code is correct? These questions shape safe technology!",
learn:[
{type:"concept",title:"Soundness = No Lies",body:"SOUND: if logic says true, it IS true.\n\nNever lies. Might miss some truths.\nBut never calls false true.\n\nCareful friend who only speaks when SURE."},
{type:"concept",title:"Completeness = No Gaps",body:"COMPLETE: if true, logic CAN prove it.\n\nNothing slips through.\n\nFriend who answers EVERY question."},
{type:"concept",title:"Gödel 1930: Basic Logic = Perfect! 🏆",body:"Basic logic is BOTH sound AND complete!\n\nProved → true ✅\nTrue → can be proved ✅"},
{type:"concept",title:"Gödel 1931: The Surprise! 🤯",body:"For math systems:\n\n1️⃣ Some true things NEVER provable!\n2️⃣ System can't prove ITSELF reliable!\n\nA rule book can't check its own rules! 🦋"},
],
quiz:[
{q:"Sound system:",opts:["Proves everything","Never says false is true!"],answer:1,explain:"Sound = no lies!"},
{q:"Gödel's surprise:",opts:["Logic useless","Some truths can't be proved!"],answer:1,explain:"True but unprovable! 🤯"},
{q:"Basic logic is:",opts:["Sound only","Both sound AND complete! 🏆"],answer:1,explain:"Gödel 1930 proved both!"},
{q:"\"Rule book can't check itself\":",opts:["Soundness","Incompleteness! 🤯"],answer:1,explain:"System can't prove own reliability!"},
{q:"Sound means:",opts:["Everything true","Proved = really true!"],answer:1,explain:"If proved, actually true!"},
{q:"Complete means:",opts:["Finished","True = can be proved!"],answer:1,explain:"If true, system finds proof!"},
{q:"Math systems:",opts:["Have truths they can't prove!","Prove everything"],answer:0,explain:"Some truths escape!"},
{q:"Soundness protects against:",opts:["Missing truths","Proving false things!"],answer:1,explain:"Never says false is true!"},
{q:"Completeness protects against:",opts:["Missing truths!","False proofs"],answer:0,explain:"No truth slips through!"},
{q:"Sound but NOT complete:",opts:["Sometimes lies","Misses truths but never lies!"],answer:1,explain:"No lies, some gaps."},
],
match:[{left:"Proved → true",right:"Soundness"},{left:"True → provable",right:"Completeness"},{left:"True but unprovable",right:"Incompleteness 🤯"},{left:"Can't check itself",right:"2nd Incompleteness"},{left:"Basic logic: both!",right:"Gödel 1930 🏆"},{left:"Math: limits!",right:"Gödel 1931 🤯"},{left:"No false positives",right:"Soundness"},{left:"No missed truths",right:"Completeness"}],
sort:{prompt:"Soundness or Completeness?",categories:["Soundness (no lies)","Completeness (no gaps)"],
items:[{text:"Never proves false",cat:0},{text:"Every truth provable",cat:1},{text:"Proved → actually true",cat:0},{text:"True → can be proved",cat:1},{text:"No false positives",cat:0},{text:"No missing truths",cat:1},{text:"If I said it, it's right",cat:0},{text:"I can say everything right",cat:1}]}
},

{id:15,realm:"philosopher",title:"Must Be vs. Could Be",subtitle:"Modal logic!",
story:"\"2+2 ALWAYS = 4. Rain tomorrow? Maybe, maybe not!\"\n\n\"Must vs. could = MODAL logic!\" 🌍 🦉",
realWorld:"🔒 Engineers: 'Bridge ALWAYS holds?' Doctors: 'Medicine COULD help?' Must vs. could everywhere!",
learn:[
{type:"concept",title:"□ = MUST Be True",body:"□ = necessarily true. Always.\n\n□(2+2=4) ✅\n□(circles round) ✅\n\nLocked box 🔒 Can't change!"},
{type:"concept",title:"◇ = COULD Be True",body:"◇ = possibly true. Maybe.\n\n◇(rain tomorrow) ☔\n◇(life on Mars) 👽\n\nOpen door 🚪 Might happen!"},
{type:"concept",title:"How They Connect",body:"□p = ¬◇¬p\nMUST = can't possibly NOT\n\n◇p = ¬□¬p\nCOULD = not necessarily NOT"},
{type:"concept",title:"Possible Worlds 🌍",body:"□p = true in ALL worlds\n◇p = true in at least ONE world\n\n2+2=4 → ALL worlds → □\nSnowy → SOME worlds → ◇"},
],
quiz:[
{q:"□p means:",opts:["Possibly","MUST be true!"],answer:1,explain:"□ = locked box!"},
{q:"◇p means:",opts:["Must be","COULD be true!"],answer:1,explain:"◇ = open door!"},
{q:"\"2+2=4\" is:",opts:["□ Necessary!","◇ Possible"],answer:0,explain:"True in ALL worlds!"},
{q:"\"Might rain tomorrow\":",opts:["□ Necessary","◇ Possible!"],answer:1,explain:"Maybe, maybe not!"},
{q:"If □p, then ◇p?",opts:["Yes!","No"],answer:0,explain:"Must = definitely can!"},
{q:"□p same as:",opts:["Not possible to be false!","Possibly true"],answer:0,explain:"Must = can't be false!"},
{q:"\"Triangles have 3 sides\":",opts:["□ Necessary!","◇ Possible"],answer:0,explain:"By definition. Always!"},
{q:"\"Could've been a doctor\":",opts:["□ Necessary","◇ Possible!"],answer:1,explain:"Possible, not guaranteed!"},
{q:"True in ALL possible worlds:",opts:["Necessary □!","Possible ◇"],answer:0,explain:"ALL worlds = must!"},
{q:"True in at least ONE world:",opts:["Necessary □","Possible ◇!"],answer:1,explain:"At least one = could!"},
],
match:[{left:"□p",right:"Must be true 🔒"},{left:"◇p",right:"Could be true 🚪"},{left:"All worlds",right:"Necessary □"},{left:"Some world",right:"Possible ◇"},{left:"2+2=4",right:"Necessary □"},{left:"Life on Mars?",right:"Possible ◇"},{left:"□p = ¬◇¬p",right:"Must = can't not"},{left:"◇p = ¬□¬p",right:"Could = not must not"}],
sort:{prompt:"Must □ or Could ◇?",categories:["Must □","Could ◇"],
items:[{text:"2+2 = 4",cat:0},{text:"Rain tomorrow",cat:1},{text:"Triangles: 3 sides",cat:0},{text:"Life on Mars",cat:1},{text:"Bachelors unmarried",cat:0},{text:"Born elsewhere",cat:1},{text:"Circle is round",cat:0},{text:"Learn piano someday",cat:1},{text:"1+1=2",cat:0},{text:"Dinosaurs had feathers",cat:1}]}
},

// 🌟 CANOPY — Mind-Bending Ideas (Units 16-18)

{id:16,realm:"master",title:"Models — Logic Alive!",subtitle:"When symbols meet real things",
story:"\"Symbols + meaning = MODEL!\" the owl said. 🦉\n\n\"Like 'x' becoming '5' in math!\"",
realWorld:"📊 Databases, video games, search engines — all models!",
learn:[
{type:"concept",title:"What is a Model?",body:"1️⃣ DOMAIN = things we talk about\n   {🍎, 🍊, 🍋}\n\n2️⃣ MEANING = what symbols mean\n   Red(🍎) = TRUE ✅\n   Red(🍊) = FALSE ❌\n\nDomain + Meaning = Model!"},
{type:"concept",title:"Same Rules, Different Models",body:"Rule: ∀x(P(x)→Q(x))\n\nModel 1: P=dogs, Q=mammals ✅\nModel 2: P=fish, Q=can fly ❌\n\nSame rule, different meanings!"},
{type:"concept",title:"Compactness ✨",body:"Every SMALL piece works...\nALL pieces work together!\n\nPuzzle 🧩: small groups fit → whole fits!"},
{type:"concept",title:"Logic Twins 👯",body:"Different models, same truths!\n\n{1,2,3} and {a,b,c}\ncan agree on every logic fact!\n\n= ELEMENTARILY EQUIVALENT"},
],
quiz:[
{q:"A model needs:",opts:["Just symbols","Domain + Meaning!"],answer:1,explain:"Things + what symbols mean!"},
{q:"Compactness:",opts:["Everything small","Small pieces work → all works!"],answer:1,explain:"Small fits → whole fits!"},
{q:"Logic twins:",opts:["Look the same","Same logic truths!"],answer:1,explain:"Same truths, different look!"},
{q:"Domain means:",opts:["Website","Things we talk about!"],answer:1,explain:"Collection of things!"},
{q:"Same rules, different models?",opts:["Impossible","Yes! Different meanings!"],answer:1,explain:"Same rules + different things!"},
{q:"Small pieces all work → compactness says:",opts:["Only small works","ALL work!"],answer:1,explain:"Whole puzzle fits!"},
{q:"Red(🍎)=TRUE means:",opts:["All things red","Apple is red here!"],answer:1,explain:"In this model, apple is red!"},
{q:"Logic twins must:",opts:["Look same","Agree on all logic facts!"],answer:1,explain:"Same truths = twins!"},
{q:"Can {dogs,cats} and {1,2} be twins?",opts:["Yes, if same truths!","No, different things"],answer:0,explain:"Truths matter, not appearance!"},
{q:"{🍎,🍊,🍋} has how many things?",opts:["1","3!"],answer:1,explain:"Three fruits!"},
],
match:[{left:"Domain + Meaning",right:"Model"},{left:"Small pieces → all works",right:"Compactness ✨"},{left:"Same logic truths",right:"Twins 👯"},{left:"Things we discuss",right:"Domain"},{left:"What symbols mean",right:"Interpretation"},{left:"Same rules, diff things",right:"Diff models"}],
sort:{prompt:"Part of Model or Property of Models?",categories:["Part of Model","Property of Models"],
items:[{text:"Domain (things)",cat:0},{text:"Interpretation (meanings)",cat:0},{text:"Compactness",cat:1},{text:"Elementary equivalence",cat:1},{text:"What 'Red' means",cat:0},{text:"Two models being twins",cat:1},{text:"The set {1,2,3}",cat:0},{text:"Small → whole works",cat:1}]}
},

{id:17,realm:"master",title:"What Can Computers Solve?",subtitle:"The Halting Problem!",
story:"\"Can a computer solve ANY puzzle?\" 🦉\n\n\"WRONG! Turing proved in 1936: some are IMPOSSIBLE. Forever.\" 😱",
realWorld:"💻 Some bugs can NEVER be caught automatically. Some things are beyond ALL computers!",
learn:[
{type:"concept",title:"Decidable ✅",body:"Computer ALWAYS answers YES or NO.\n\n\"Is this even?\" → Divide by 2! ✅\n\"Is 17 prime?\" → Check! ✅\n\nAlways finishes with answer."},
{type:"concept",title:"Undecidable ❌",body:"NO computer can always answer.\n\n\"Will this program stop or run forever?\"\n→ IMPOSSIBLE!\n\n= THE HALTING PROBLEM"},
{type:"concept",title:"Why Impossible 🤯",body:"Magic machine H predicts stop/forever.\n\nSneaky program D:\n\"If H says stop → run forever!\nIf H says forever → stop!\"\n\nD does the OPPOSITE! 😈\nH is always wrong about D!\nSo H can't exist! 🤯"},
{type:"concept",title:"P vs NP 🏆",body:"P = easy to solve ✅\nNP = hard to solve, easy to CHECK 🔍\n\nPuzzle: hard to solve, easy to check!\n\nP = NP? Nobody knows! $1,000,000!"},
],
quiz:[
{q:"Computer always tells if program stops?",opts:["Yes","No — IMPOSSIBLE!"],answer:1,explain:"Halting Problem!"},
{q:"Decidable:",opts:["Very hard","Always YES or NO!"],answer:1,explain:"Guaranteed answer!"},
{q:"Halting Problem is:",opts:["Easy","Undecidable!"],answer:1,explain:"Impossible forever!"},
{q:"P vs NP asks:",opts:["Computers fast?","Easy-check = easy-solve?"],answer:1,explain:"Million dollar question!"},
{q:"\"Is this even?\":",opts:["Undecidable","Decidable!"],answer:1,explain:"Divide by 2. Always works!"},
{q:"Halting Problem impossible because:",opts:["Computers slow","Opposite trick! 😈"],answer:1,explain:"Sneaky program beats any predictor!"},
{q:"P problems:",opts:["Easy to solve!","Easy to check"],answer:0,explain:"P = easy to solve!"},
{q:"NP problems:",opts:["Impossible","Easy to CHECK!"],answer:1,explain:"Hard to solve, easy to check!"},
{q:"Who proved Halting Problem?",opts:["Einstein","Alan Turing!"],answer:1,explain:"Turing, 1936!"},
{q:"Prove P=NP wins:",opts:["Nothing","$1,000,000!"],answer:1,explain:"Millennium Prize!"},
],
match:[{left:"Always answers",right:"Decidable ✅"},{left:"NO computer can",right:"Undecidable ❌"},{left:"Program stop?",right:"Halting Problem"},{left:"Easy check, hard solve?",right:"P vs NP"},{left:"Easy to solve",right:"Class P"},{left:"Easy to check",right:"Class NP"},{left:"Turing",right:"Halting Problem"},{left:"$1,000,000",right:"P = NP?"}],
sort:{prompt:"Decidable ✅ or Undecidable ❌?",categories:["Decidable ✅","Undecidable ❌"],
items:[{text:"Is this number even?",cat:0},{text:"Will program run forever?",cat:1},{text:"Is p ∧ q true?",cat:0},{text:"Is predicate formula always true?",cat:1},{text:"Is 17 prime?",cat:0},{text:"Does program have any bug?",cat:1},{text:"What is 2+2?",cat:0},{text:"Will code ever output 'hello'?",cat:1}]}
},

{id:18,realm:"master",title:"Breaking the Rules!",subtitle:"What if logic worked differently?",
story:"\"Everything uses TRUE or FALSE. But what if... partly true? True AND false?\" 🌈 🦉",
realWorld:"🌡️ 'Is water hot?' Sort of! Fuzzy logic handles 'sort of.' These ideas run washing machines, AI, and robots!",
learn:[
{type:"concept",title:"Intuitionistic 🔨",body:"Don't CLAIM true. BUILD a proof!\n\nCan't say \"true or false\"\nunless you SHOW which!\n\n🤯 Programs ARE proofs!"},
{type:"concept",title:"Paraconsistent 🧱",body:"Normal: contradiction → EVERYTHING true! 💥\n\nParaconsistent: contradiction stays in its room.\nRest still works!\n\nFirewall: fire in one room ≠ whole house."},
{type:"concept",title:"Fuzzy 🌡️",body:"Normal: TRUE(1) or FALSE(0).\nFuzzy: 0 to 1!\n\n\"Hot?\" Cold(0)—warm(0.5)—hot(1)\nNOT hot = 1 minus number.\n0.6 hot → NOT hot = 0.4"},
{type:"concept",title:"Relevance 🎯",body:"Normal: \"If moon=cheese, 2+2=4\" is true!\n\nRelevance: NO! IF must connect to THEN!\nMoon cheese ≠ math!"},
],
quiz:[
{q:"Intuitionistic says:",opts:["Everything true","PROVE IT!"],answer:1,explain:"Build a proof!"},
{q:"Fuzzy: tall=0.8. NOT tall?",opts:["0.8","0.2"],answer:1,explain:"1 - 0.8 = 0.2!"},
{q:"Paraconsistent useful because:",opts:["No contradictions","Think DESPITE contradictions!"],answer:1,explain:"Mess stays contained!"},
{q:"Relevance rejects:",opts:["All arguments","Unconnected IF-THEN!"],answer:1,explain:"Stay on topic!"},
{q:"'Warm water' in fuzzy:",opts:["TRUE or FALSE","0.6!"],answer:1,explain:"Degrees of truth!"},
{q:"Programs = proofs in:",opts:["Fuzzy","Intuitionistic!"],answer:1,explain:"Curry-Howard!"},
{q:"Fuzzy: hot=0.3, cold=0.7. NOT cold?",opts:["0.7","0.3!"],answer:1,explain:"1 - 0.7 = 0.3!"},
{q:"Conflicting database? Use:",opts:["Classical","Paraconsistent!"],answer:1,explain:"Contains the mess!"},
{q:"\"If purple elephants, 1=2\" ok in:",opts:["Classical! (IF false)","Relevance"],answer:0,explain:"Classical allows unconnected!"},
{q:"Washing machine uses:",opts:["Classical","Fuzzy! (dirtiness=0.7)"],answer:1,explain:"Degrees of dirty!"},
],
match:[{left:"Prove it!",right:"Intuitionistic 🔨"},{left:"Contain contradictions",right:"Paraconsistent 🧱"},{left:"0 to 1",right:"Fuzzy 🌡️"},{left:"Stay on topic",right:"Relevance 🎯"},{left:"Programs = proofs",right:"Intuitionistic"},{left:"Washing machines",right:"Fuzzy"},{left:"Firewall",right:"Paraconsistent"},{left:"IF↔THEN connected",right:"Relevance"}],
sort:{prompt:"Which logic?",categories:["Intuitionistic 🔨","Paraconsistent 🧱","Fuzzy 🌡️","Relevance 🎯"],
items:[{text:"Must build proof!",cat:0},{text:"Database conflicts but works",cat:1},{text:"72°F = 0.5 warm",cat:2},{text:"IF must relate to THEN",cat:3},{text:"Programs ARE proofs",cat:0},{text:"Sensors disagree, system works",cat:1},{text:"Dirtiness = 0.7",cat:2},{text:"Moon cheese → math? No!",cat:3}]}
},
];

export default C;
