// LOGIC CURRICULUM — 10 units, 3 tiers each, all modes
// Format matches grammarData.js exactly

export const LOGIC = [
  {
    id: 'l1', title: 'What Can Be True or False?', subtitle: 'Statements vs. non-statements',
    anchorTexts: '"All men are mortal," newspaper headlines, "This statement is false"',
    learn: 'Logic starts by separating statements (which can be true or false) from everything else. "It\'s raining" is a statement — it makes a claim about the world. "Is it raining?" is a question, not a claim. "Close the door!" is a command, not a claim. But what about "Chocolate is the best flavor" or "Murder is wrong"? The boundary between statement and non-statement is where philosophy begins.',
    quiz: {
      seed: [
        { q: '"The earth orbits the sun." Is this a statement?', opts: ['Yes — it can be true or false', 'No — it\'s a fact', 'Only if you believe it', 'It\'s a question'], ans: 0 },
        { q: '"Close the door!" Is this a statement?', opts: ['Yes', 'No — it\'s a command', 'Only if you obey', 'It depends'], ans: 1 },
        { q: '"Is it Tuesday?" Is this a statement?', opts: ['Yes', 'No — it\'s a question', 'Yes — it can be true or false', 'Sometimes'], ans: 1 },
        { q: '"Pizza is the best food." Is this a statement?', opts: ['Yes — definitely true', 'It\'s an opinion, not a testable statement', 'No', 'It\'s a command'], ans: 1 },
        { q: '"2 + 2 = 5" is a statement because:', opts: ['It\'s true', 'It\'s false, but still makes a claim', 'It\'s math', 'It\'s not a statement'], ans: 1 },
        { q: '"Wow!" Is this a statement?', opts: ['Yes', 'No — it\'s an exclamation', 'It depends on tone', 'It\'s a fragment'], ans: 1 },
        { q: 'Which of these IS a statement?', opts: ['What time is it?', 'Please sit down.', 'Water boils at 100°C at sea level.', 'Ouch!'], ans: 2 },
        { q: '"I feel happy." Is this a statement?', opts: ['No — feelings aren\'t facts', 'Yes — it claims something about the speaker\'s state', 'Only if it\'s true', 'It\'s an exclamation'], ans: 1 },
        { q: 'Statements are important in logic because:', opts: ['Logic only works with claims that can be true or false', 'Logic requires math', 'Statements are always true', 'Logic needs complete sentences'], ans: 0 },
        { q: '"This sentence is false." This is:', opts: ['True', 'False', 'A paradox — it breaks the system', 'Not a sentence'], ans: 2 },
      ],
      growth: [
        { q: '"The economy is struggling." Is this a statement?', opts: ['Clearly true or false', 'Ambiguous — "struggling" is vague and partly metaphorical', 'An opinion', 'Only economists can judge'], ans: 1 },
        { q: 'Rewriting "The economy is struggling" as a testable statement:', opts: ['"The economy is bad"', '"GDP decreased by 2% in Q3"', '"Everyone is poor"', '"Money is worthless"'], ans: 1 },
        { q: '"Murder is wrong" is:', opts: ['A statement of fact', 'A moral claim — a value judgment, different from an empirical claim', 'Not a statement', 'Obviously true and therefore a fact'], ans: 1 },
        { q: '"It rained yesterday" vs "Yesterday was a bad day." The difference:', opts: ['No difference', 'The first is empirically testable; the second involves subjective judgment', 'The first is a fact, the second is wrong', 'Both are opinions'], ans: 1 },
        { q: '"Everyone knows that..." is persuasive but not evidence because:', opts: ['Everyone does know', 'It replaces evidence with social pressure — it assumes the conclusion', 'It\'s a statement', 'Common knowledge is always right'], ans: 1 },
        { q: '"Studies show..." can be misleading if:', opts: ['Studies are always right', 'The studies are cherry-picked, misrepresented, or don\'t actually support the claim', 'Science is unreliable', '"Studies show" is meaningless'], ans: 1 },
        { q: 'A headline that looks factual but contains a hidden opinion is:', opts: ['Good journalism', 'A statement that blurs the line between claim and evaluation', 'Impossible', 'Always intentional'], ans: 1 },
        { q: 'Distinguishing statements from non-statements matters because:', opts: ['Grammar requires it', 'You can only evaluate the truth of claims that actually make claims', 'It\'s a Logic 101 exercise', 'It doesn\'t matter'], ans: 1 },
        { q: '"This statement is false" is paradoxical because:', opts: ['It\'s poorly written', 'If true, it\'s false; if false, it\'s true — no consistent truth value', 'It\'s meaningless', 'All self-reference is paradoxical'], ans: 1 },
        { q: 'The Liar Paradox reveals:', opts: ['Language is broken', 'Self-reference can break truth/falsity — a limit of formal logic', 'We should avoid self-reference', 'Nothing important'], ans: 1 },
      ],
      canopy: [
        { q: '"God exists" — is this a statement in the logical sense?', opts: ['Yes — it makes a claim that is either true or false', 'No — it\'s a matter of faith', 'It depends on your theology', 'All three perspectives have merit — genuinely debated'], ans: 3 },
        { q: 'Logical positivists argued that only empirically verifiable claims are meaningful. This excludes:', opts: ['Scientific claims', 'Ethical, aesthetic, metaphysical, and theological claims', 'Nothing important', 'Only religious claims'], ans: 1 },
        { q: 'The positivist criterion was abandoned partly because:', opts: ['It was too strict', 'The criterion itself is not empirically verifiable — it fails its own test', 'No one cared', 'Science proved it wrong'], ans: 1 },
        { q: 'Wittgenstein\'s later philosophy: meaning comes from:', opts: ['Dictionary definitions', 'Its use in specific contexts ("language games")', 'Logic alone', 'Grammar'], ans: 1 },
        { q: 'This matters for Logic because:', opts: ['Logic is useless', 'The domain of "statements" may be narrower than we assume', 'All language is logical', 'Wittgenstein was wrong'], ans: 1 },
        { q: '"Kindness is good" functions in discourse as:', opts: ['An empirical claim', 'A normative claim — it prescribes rather than describes, yet participates in reasoning', 'A meaningless expression', 'A command'], ans: 1 },
        { q: 'The medieval distinction between "speculative" and "practical" reasoning:', opts: ['Two types of logic', 'Some statements are about what IS, others about what OUGHT — both are domains of rational inquiry', 'Only speculative reasoning is logical', 'Outdated'], ans: 1 },
        { q: 'Where to draw the line between evaluable and non-evaluable statements is:', opts: ['Settled', 'One of the most important open questions in philosophy', 'Easy to answer', 'Unimportant'], ans: 1 },
        { q: 'Liar Paradox + Gödel + limits of verificationism converge on:', opts: ['Logic is useless', 'Formal systems have boundaries — the most interesting questions live there', 'We need better logic', 'Nothing'], ans: 1 },
        { q: 'The purpose of this unit is:', opts: ['Classify sentences', 'Develop the habit of asking: Is this a claim? What kind? Can it be evaluated?', 'Learn terminology', 'Start easy'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Write five statements about the world. Then write five sentences that LOOK like statements but aren\'t (opinions disguised as facts, vague claims, questions in disguise). Explain the difference between each pair.' },
      growth: { prompt: 'Find a paragraph from a news article. Separate the factual claims from the opinions, interpretations, and assumptions. How many of each? Which are doing the most work in the paragraph?' },
      canopy: { prompt: 'Is "God exists" a statement in the logical sense? What about "Kindness is good"? Write 200 words on where you would draw the line between statements logic can evaluate and those it can\'t — and what tools we use for the ones logic can\'t reach.' },
    },
    encounter: {
      text: '"We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness."',
      attribution: '— Declaration of Independence',
      questions: [
        { tier: 'seed', q: 'Is "all men are created equal" a factual statement or something else? How do you know?' },
        { tier: 'growth', q: 'Jefferson calls these truths "self-evident" — meaning they need no proof. But are they? List one way "all men are created equal" could be read as empirically false. Then explain what Jefferson might mean by "equal" that makes it true.' },
        { tier: 'canopy', q: '"Self-evident" means the statement requires no argument. But Jefferson is writing a document that IS an argument. Why does he need to argue for truths he calls self-evident? What does this reveal about the relationship between logic and rhetoric?' },
      ]
    },
    bridge: 'The ability to distinguish statement from non-statement depends on grammatical precision. "The economy is struggling" — is this a factual claim or a metaphor? (Grammar → Logic.)',
  },
  {
    id: 'l2', title: 'Combining Truths', subtitle: 'AND, OR, NOT — logical connectives',
    anchorTexts: 'Game rules, legal contracts, Boolean logic',
    learn: 'AND means both must be true. OR means at least one. NOT flips truth value. These three simple operations can express extraordinarily complex ideas. Every search engine, every contract clause, every conditional rule uses these connectives. Truth tables show you exactly what happens when you combine statements — no ambiguity, no hand-waving.',
    quiz: {
      seed: [
        { q: 'If it\'s raining AND cold, both must be:', opts: ['False', 'True', 'One true', 'Neither'], ans: 1 },
        { q: '"You can have cake OR pie." You can have:', opts: ['Both', 'At least one', 'Neither', 'Only cake'], ans: 1 },
        { q: 'NOT true equals:', opts: ['True', 'False', 'Maybe', 'Unknown'], ans: 1 },
        { q: '"Bring a pencil AND an eraser." You need:', opts: ['Just pencil', 'Just eraser', 'Both', 'Either one'], ans: 2 },
        { q: 'If "it\'s sunny" is true, "it\'s NOT sunny" is:', opts: ['True', 'False', 'Unknown', 'Sometimes'], ans: 1 },
        { q: '"The store is open AND it\'s Tuesday." If it\'s Monday:', opts: ['Whole thing true', 'Whole thing false', 'Can\'t tell', 'Still true'], ans: 1 },
        { q: 'OR means:', opts: ['Both must be true', 'At least one must be true', 'Neither true', 'Exactly one'], ans: 1 },
        { q: 'If A is true and B is false, "A AND B" is:', opts: ['True', 'False', 'Unknown', 'Depends'], ans: 1 },
        { q: 'If A is true and B is false, "A OR B" is:', opts: ['True', 'False', 'Unknown', 'Depends'], ans: 0 },
        { q: 'NOT (NOT true) equals:', opts: ['True', 'False', 'Unknown', 'Paradox'], ans: 0 },
      ],
      growth: [
        { q: 'T AND T =', opts: ['T', 'F', 'Unknown', 'Depends'], ans: 0 },
        { q: 'T AND F =', opts: ['T', 'F', 'Unknown', 'Depends'], ans: 1 },
        { q: 'F OR F =', opts: ['T', 'F', 'Unknown', 'Depends'], ans: 1 },
        { q: 'T OR F =', opts: ['T', 'F', 'Unknown', 'Depends'], ans: 0 },
        { q: '"A AND (B OR C)" — if A=T, B=F, C=T:', opts: ['True', 'False', 'Unknown', 'Depends'], ans: 0 },
        { q: 'NOT (A AND B) is equivalent to:', opts: ['NOT A AND NOT B', '(NOT A) OR (NOT B) — De Morgan\'s Law', 'A OR B', 'NOT A AND B'], ans: 1 },
        { q: 'Legal: "shall not keep pets OR sublease without consent." Ambiguity:', opts: ['None', 'Does "without consent" apply to pets AND subleasing, or just subleasing?', 'Pets only', 'Both clearly'], ans: 1 },
        { q: 'Boolean search "cats AND dogs" returns:', opts: ['Pages about either', 'Pages containing both terms', 'Pages about neither', 'All pages'], ans: 1 },
        { q: 'Boolean search "cats OR dogs" returns:', opts: ['Pages about either or both', 'Pages about both only', 'Pages about neither', 'Exact phrase'], ans: 0 },
        { q: 'Logical connectives matter because:', opts: ['Computer science', 'They\'re the building blocks of all complex reasoning', 'Grammar requires them', 'Just notation'], ans: 1 },
      ],
      canopy: [
        { q: 'De Morgan\'s Laws: NOT(A AND B) = (NOT A) OR (NOT B). This is:', opts: ['A definition', 'A provable equivalence showing how negation distributes over connectives', 'Convention', 'Approximation'], ans: 1 },
        { q: 'In natural language, "or" is often exclusive (one not both). In logic, OR is:', opts: ['Exclusive', 'Inclusive — at least one, possibly both', 'Undefined', 'Context-dependent'], ans: 1 },
        { q: 'This ambiguity between natural and formal "or" leads to:', opts: ['Nothing', 'Real misunderstandings in law, policy, and argument', 'Better precision', 'Only academic concern'], ans: 1 },
        { q: 'Legal clause: "eligible if employed AND (resident OR citizen)." If employed but non-resident non-citizen:', opts: ['Eligible', 'Not eligible', 'Ambiguous', 'Depends on jurisdiction'], ans: 1 },
        { q: 'Truth tables exhaustively show:', opts: ['Common outcomes', 'Every possible combination of truth values for component statements', 'Likely outcomes', 'Nothing useful'], ans: 1 },
        { q: 'The power of formal logic is that it:', opts: ['Replaces thinking', 'Makes hidden structure explicit and testable', 'Is always right', 'Eliminates ambiguity'], ans: 1 },
        { q: 'Its limitation is that:', opts: ['It\'s hard', 'Natural language is richer and more ambiguous than formal notation can capture', 'It\'s outdated', 'None'], ans: 1 },
        { q: 'Talmudic kal va-chomer ("if the lesser, then certainly the greater") is:', opts: ['AND logic', 'A form of conditional reasoning beyond simple connectives', 'OR logic', 'NOT logic'], ans: 1 },
        { q: 'AND, OR, NOT are to logic what:', opts: ['Letters to words', 'Atoms to molecules — elementary units combining into complex structures', 'Numbers to math', 'Rules to games'], ans: 1 },
        { q: 'Mastering connectives means:', opts: ['Memorizing tables', 'Being able to analyze the logical structure of any compound claim', 'Computing', 'Nothing beyond this unit'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Write the rules of a simple game (like tag, hide-and-seek, or one you invent) using AND, OR, and NOT. Be precise enough that someone unfamiliar could play without asking questions.' },
      growth: { prompt: 'Find a terms-of-service clause from an app you use. Rewrite it using logical notation (AND, OR, NOT). Does the logical version reveal any ambiguity the English hides?' },
      canopy: { prompt: 'Design a truth table for a real-world decision with 3 or more variables (e.g., "Should I take this job?" with factors like salary, location, growth). What does the table reveal that informal reasoning might miss? Write 150 words reflecting.' },
    },
    encounter: {
      text: '"No person shall be a Senator who shall not have attained to the Age of thirty Years, and been nine Years a Citizen of the United States, and who shall not, when elected, be an Inhabitant of that State for which he shall be chosen."',
      attribution: '— U.S. Constitution, Article I, Section 3',
      questions: [
        { tier: 'seed', q: 'What are the three requirements to be a Senator? Hint: look for AND.' },
        { tier: 'growth', q: 'Rewrite this using logical notation (AND, OR, NOT). Is the double negative ("shall not...not") confusing? What does it actually mean?' },
        { tier: 'canopy', q: 'Why might the framers have used such complex logical syntax? Is the complexity serving precision, or creating ambiguity? Analyze one clause where the logic could be read two ways.' },
      ]
    },
    bridge: 'Logical connectives operate at the sentence level. Grammar taught you sentence structure; Logic teaches the structure of claims built from sentences.',
  },
  {
    id: 'l3', title: 'If-Then', subtitle: 'Conditional reasoning',
    anchorTexts: '"If rain, then wet ground," medical diagnostics, kal va-chomer',
    learn: '"If P, then Q" is the engine of reasoning. But most everyday errors come from confusing the direction. "If it rains, the ground gets wet" does NOT mean "if the ground is wet, it rained" — a sprinkler could have done it. The converse, inverse, and contrapositive: this single distinction prevents enormous reasoning errors in medicine, law, and daily life.',
    quiz: {
      seed: [
        { q: '"If it rains, the ground gets wet." It rained. So:', opts: ['Ground is wet', 'Ground might be wet', 'Ground is dry', 'Can\'t tell'], ans: 0 },
        { q: 'The ground is wet. Did it rain?', opts: ['Yes', 'No', 'Maybe — something else could have caused it', 'Definitely'], ans: 2 },
        { q: '"If you study, you\'ll pass." You passed. Did you study?', opts: ['Yes', 'Not necessarily', 'Definitely', 'No'], ans: 1 },
        { q: '"If you study, you\'ll pass." You didn\'t study. So:', opts: ['You\'ll fail', 'You might fail, but could still pass', 'You\'ll pass anyway', 'Can\'t tell'], ans: 1 },
        { q: '"If it\'s a dog, it\'s an animal." Which follows?', opts: ['If animal, then dog', 'If not dog, then not animal', 'If not animal, then not dog', 'All animals are dogs'], ans: 2 },
        { q: '"If you eat too much candy, you\'ll get a stomachache." You have a stomachache. Candy?', opts: ['Yes', 'No — many things cause stomachaches', 'Probably', 'Definitely'], ans: 1 },
        { q: 'The CONTRAPOSITIVE of "If rain, then wet" is:', opts: ['If wet, then rain', 'If no rain, then not wet', 'If not wet, then no rain', 'Rain means wet'], ans: 2 },
        { q: 'The contrapositive is always:', opts: ['Sometimes true', 'Just as true as the original', 'Less true', 'Opposite'], ans: 1 },
        { q: '"If it\'s Tuesday, the library is open." It\'s not Tuesday. The library is:', opts: ['Closed', 'Open', 'Could be either — maybe it\'s open other days too', 'Definitely closed'], ans: 2 },
        { q: 'Confusing "if P then Q" with "if Q then P" is called:', opts: ['Good reasoning', 'Affirming the consequent — a common error', 'The contrapositive', 'Logic'], ans: 1 },
      ],
      growth: [
        { q: 'The CONVERSE of "If P then Q" is:', opts: ['If not Q then not P', 'If Q then P', 'If not P then not Q', 'Not (if P then Q)'], ans: 1 },
        { q: 'The converse is:', opts: ['Always true', 'NOT necessarily true — must be established independently', 'Always false', 'Same as original'], ans: 1 },
        { q: 'The INVERSE of "If P then Q" is:', opts: ['If not P then not Q', 'If Q then P', 'If not Q then not P', 'None'], ans: 0 },
        { q: 'The inverse is:', opts: ['Always true', 'NOT necessarily true', 'Always false', 'Same as contrapositive'], ans: 1 },
        { q: 'Doctor knows: if measles, then fever. Patient has fever. Conclude measles?', opts: ['Yes', 'No — many diseases cause fever', 'Probably', 'Run tests — can\'t logically conclude measles'], ans: 3 },
        { q: 'Doctor knows: if measles, then fever. Patient has NO fever. Conclude:', opts: ['No measles (contrapositive!)', 'Maybe measles', 'Can\'t tell', 'Need more tests'], ans: 0 },
        { q: 'Most advertising errors involve confusing:', opts: ['AND with OR', 'The conditional with its converse', 'Truth with falsity', 'Nothing'], ans: 1 },
        { q: '"All A are B" is equivalent to:', opts: ['All B are A', 'If A then B', 'If B then A', 'A equals B'], ans: 1 },
        { q: 'Chain: "If A then B" and "If B then C" together give:', opts: ['If C then A', 'If A then C', 'If not A then not C', 'Nothing'], ans: 1 },
        { q: 'The single most important lesson of conditional reasoning:', opts: ['Memorize forms', 'The direction of the arrow matters — confusing it is the most common reasoning error', 'All conditionals are true', 'Avoid if-then'], ans: 1 },
      ],
      canopy: [
        { q: 'Kal va-chomer: "If X applies in the lesser case, certainly in the greater." This is:', opts: ['Simple if-then', 'A fortiori reasoning — strengthened conditional', 'Deductive only', 'Inductive only'], ans: 1 },
        { q: 'It differs from simple if-then because:', opts: ['It doesn\'t', 'It involves a comparative judgment about what counts as "lesser" and "greater"', 'It\'s religious', 'It\'s weaker'], ans: 1 },
        { q: 'Is kal va-chomer deductive or inductive?', opts: ['Purely deductive', 'Purely inductive', 'Elements of both — the comparison introduces judgment', 'Neither'], ans: 2 },
        { q: 'The Talmud limits kal va-chomer (can\'t derive punishment greater than the source). This suggests:', opts: ['The rabbis were cautious', 'Formal reasoning needs constraints — logic alone doesn\'t determine just application', 'It\'s only about law', 'Nothing about logic'], ans: 1 },
        { q: 'Necessary conditions: "If P then Q" means Q is ___ for P:', opts: ['Sufficient', 'Necessary — can\'t have P without Q', 'Both', 'Neither'], ans: 1 },
        { q: 'Sufficient conditions: P is ___ for Q:', opts: ['Necessary', 'Sufficient — P guarantees Q, but Q might occur without P', 'Both', 'Neither'], ans: 1 },
        { q: 'Confusing necessary and sufficient conditions is:', opts: ['Rare', 'Extremely common in everyday reasoning and policy debates', 'Only academic', 'Harmless'], ans: 1 },
        { q: '"Democracy requires free speech" means free speech is:', opts: ['Sufficient for democracy', 'Necessary for democracy — but not sufficient alone', 'Irrelevant', 'Both'], ans: 1 },
        { q: 'A chain of if-then statements is only as strong as:', opts: ['Its longest link', 'Its weakest link — one false premise breaks the chain', 'Its first link', 'Its conclusion'], ans: 1 },
        { q: 'Conditional reasoning mastery means:', opts: ['Memorizing forms', 'Automatically checking direction, distinguishing necessary from sufficient, testing each link', 'Avoiding conditionals', 'Formal notation'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Write 3 if-then statements about your daily life (e.g., "If it\'s cold, I wear a jacket"). For each, write the reverse. Is the reverse also true? Why or why not?' },
      growth: { prompt: 'Find 3 if-then claims in advertisements or news headlines. Write the converse of each. Is the ad relying on you confusing the original with its converse?' },
      canopy: { prompt: 'Construct a chain of 3 if-then statements leading to a surprising but valid conclusion. Then find the weakest link — where does the chain most likely break in the real world? Write 200 words analyzing.' },
    },
    encounter: {
      text: 'A patient arrives with fever, rash, and fatigue. The doctor knows:\n• If measles → fever + rash\n• If lupus → fatigue + rash\n• If flu → fever + fatigue\nThe patient has all three symptoms.',
      attribution: '— Diagnostic reasoning exercise',
      questions: [
        { tier: 'seed', q: 'Can the doctor be sure which disease the patient has? Why or why not?' },
        { tier: 'growth', q: 'The doctor can\'t conclude measles from fever + rash alone (other diseases cause those too). What additional test would help? Which disease can be ruled out by which missing symptom?' },
        { tier: 'canopy', q: 'Medical diagnosis uses abductive reasoning (inference to best explanation), not pure deduction. How does this differ from strict if-then logic? When is "most likely" good enough, and when do we need certainty?' },
      ]
    },
    bridge: 'If-then reasoning is the skeleton of every argument. In Unit 4, we\'ll see how premises chain together into complete arguments — and how to test whether they hold.',
  },
  {
    id: 'l4', title: 'The Shape of an Argument', subtitle: 'Premises, conclusions, validity, soundness',
    anchorTexts: 'Lincoln\'s Cooper Union speech, Anselm\'s ontological argument',
    learn: 'An argument has premises (starting points) and a conclusion (what follows). It\'s valid if the conclusion truly follows from the premises — even if the premises are wrong. It\'s sound if valid AND premises are actually true. Most bad arguments hide premises no one questions. Finding hidden premises is the most practical logical skill there is.',
    quiz: {
      seed: [
        { q: 'An argument\'s conclusion is:', opts: ['The first statement', 'What the reasons support', 'The longest sentence', 'The opinion'], ans: 1 },
        { q: '"All dogs are mammals. Rex is a dog. Therefore Rex is a mammal." This is:', opts: ['Invalid', 'Valid and sound', 'Valid but unsound', 'An opinion'], ans: 1 },
        { q: '"All birds can fly. Penguins are birds. Therefore penguins can fly." This is:', opts: ['Valid and sound', 'Valid but UNSOUND — premise "all birds fly" is false', 'Invalid', 'Correct'], ans: 1 },
        { q: 'A hidden premise is:', opts: ['A secret', 'An unstated assumption the argument depends on', 'Always wrong', 'Unimportant'], ans: 1 },
        { q: '"She\'s smart, so she\'ll succeed." The hidden premise:', opts: ['Smart people always succeed', 'There is no hidden premise', 'She works hard', 'Success is guaranteed'], ans: 0 },
        { q: 'Valid means:', opts: ['True', 'IF premises are true, conclusion MUST be true', 'Persuasive', 'Popular'], ans: 1 },
        { q: 'Sound means:', opts: ['Valid', 'Valid AND premises are actually true', 'Loud', 'Convincing'], ans: 1 },
        { q: 'An argument can be valid but wrong if:', opts: ['Never', 'The logic is correct but a premise is false', 'It\'s too short', 'It\'s unpopular'], ans: 1 },
        { q: 'Finding the conclusion: look for words like:', opts: ['Because, since', 'Therefore, so, thus, consequently', 'And, but', 'First, second'], ans: 1 },
        { q: 'Finding premises: look for words like:', opts: ['Therefore, so', 'Because, since, given that', 'However', 'Finally'], ans: 1 },
      ],
      growth: [
        { q: 'A hidden premise is dangerous because:', opts: ['It\'s always false', 'It goes unexamined — you accept it without realizing', 'It\'s complex', 'It\'s intentional'], ans: 1 },
        { q: '"We should cut taxes because it will grow the economy." Hidden premises include:', opts: ['Taxes are bad', 'Tax cuts always grow the economy AND economic growth is the priority', 'The economy needs growth', 'Nothing is hidden'], ans: 1 },
        { q: 'A valid argument with a false conclusion must have:', opts: ['Good logic', 'At least one false premise', 'An invalid structure', 'Nothing wrong'], ans: 1 },
        { q: 'The strongest way to attack an argument:', opts: ['Insult the speaker', 'Identify and challenge the weakest premise', 'Deny the conclusion', 'Change the subject'], ans: 1 },
        { q: 'Modus ponens: If P then Q. P is true. Therefore:', opts: ['Not Q', 'Q', 'Not P', 'P again'], ans: 1 },
        { q: 'Modus tollens: If P then Q. Q is false. Therefore:', opts: ['Q', 'P', 'Not P', 'Not Q again'], ans: 2 },
        { q: 'Testing an argument means checking:', opts: ['If you agree', 'Validity (does conclusion follow?) AND soundness (are premises true?)', 'Length', 'Who said it'], ans: 1 },
        { q: 'A deductively valid argument:', opts: ['Might be wrong', 'Guarantees its conclusion IF premises are true', 'Is always right', 'Is persuasive'], ans: 1 },
        { q: '"All heroes are brave. Achilles is a hero. Therefore Achilles is brave." This is:', opts: ['Inductive', 'A syllogism — a classic deductive form', 'A guess', 'Invalid'], ans: 1 },
        { q: 'The practical value of argument analysis:', opts: ['Winning debates', 'Seeing the full structure — premises, hidden assumptions, and logical form — before deciding', 'Being right', 'Sounding smart'], ans: 1 },
      ],
      canopy: [
        { q: 'Anselm\'s ontological argument: "God is that than which nothing greater can be conceived. Existing in reality is greater than existing in mind alone. Therefore God exists." This is:', opts: ['Obviously true', 'Valid in structure, but the second premise is highly contested', 'Obviously false', 'Not an argument'], ans: 1 },
        { q: 'The controversy lies in:', opts: ['The definition of God', 'Whether existence is a "property" that makes something "greater"', 'The conclusion', 'Nothing — settled'], ans: 1 },
        { q: 'Kant\'s objection — "existence is not a predicate" — means:', opts: ['God doesn\'t exist', 'Saying something exists doesn\'t add a property — 100 real dollars have no more properties than 100 imagined ones', 'Anselm was wrong', 'Logic can\'t discuss God'], ans: 1 },
        { q: 'Hidden premises in political arguments often take the form of:', opts: ['Lies', 'Unstated values — assumptions about what\'s good, fair, or important', 'Complex logic', 'Nothing hidden'], ans: 1 },
        { q: 'Steel-manning (building the strongest version of an opposing argument):', opts: ['Is dishonest', 'Means if you defeat it, your position is genuinely strong; if not, you learn', 'Shows weakness', 'Is unnecessary'], ans: 1 },
        { q: 'Philosophical arguments about God, justice, consciousness resist resolution because:', opts: ['They\'re meaningless', 'Key premises depend on commitments that are themselves debatable', 'People are stubborn', 'Logic doesn\'t apply'], ans: 1 },
        { q: 'Argument mapping (visual representation) helps because:', opts: ['It\'s pretty', 'It makes invisible logical structure visible and testable', 'It\'s required', 'It simplifies everything'], ans: 1 },
        { q: 'A sorites (chain argument): If A→B, B→C, C→D, then A→D. The risk:', opts: ['None', 'Each link may be slightly uncertain, and uncertainties compound', 'It\'s always valid', 'Chains are always strong'], ans: 1 },
        { q: 'Formal vs. informal logic:', opts: ['Formal is better', 'Formal uses symbols; informal evaluates reasoning in natural language — both matter', 'Informal is sloppy', 'No difference'], ans: 1 },
        { q: 'The capstone skill of argument analysis:', opts: ['Winning debates', 'Seeing full structure — premises, hidden assumptions, logical form, evidence strength — then evaluating honestly', 'Memorizing forms', 'Being persuasive'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Build an argument for your favorite food being the best. State at least two reasons (premises) and a clear conclusion. Then ask: are your premises actually true, or just opinions?' },
      growth: { prompt: 'Find a public figure\'s argument (op-ed, speech, interview). Identify the explicit premises AND the hidden ones. Which hidden premise is most debatable?' },
      canopy: { prompt: 'Reconstruct the strongest argument you disagree with. Be scrupulously fair — build the steel man. Then identify exactly where it goes wrong: which premise do you reject, and why? (250 words)' },
    },
    encounter: {
      text: '"Let us examine the facts. Of the 39 signers of the Constitution, 21 — a majority — were known to have been opposed to slavery. They voted for the Constitution not because of, but in spite of, its compromise with slavery."',
      attribution: '— Abraham Lincoln, Cooper Union Speech (adapted)',
      questions: [
        { tier: 'seed', q: 'What is Lincoln\'s conclusion? What are his premises (reasons)?' },
        { tier: 'growth', q: 'Lincoln uses historical evidence as premises. Map his argument. Where is the reasoning strongest? Where might someone push back?' },
        { tier: 'canopy', q: 'Lincoln\'s argument depends on a hidden premise: that the founders\' intentions should guide constitutional interpretation. Is this premise defensible? What\'s the strongest objection to originalism as Lincoln practices it here?' },
      ]
    },
    bridge: 'You can now test any argument for validity and soundness. But how do arguments go wrong in practice? Unit 5: Fallacies.',
  },
  {
    id: 'l5', title: 'How Reasoning Goes Wrong', subtitle: 'Fallacies as diagnostic tools',
    anchorTexts: 'Advertisements, political debates, social media arguments',
    learn: 'Fallacies aren\'t a catalog to memorize — they\'re a diagnostic toolkit. When reasoning feels persuasive but something\'s off, fallacies help you name the disease. Major groups: Relevance (ad hominem, appeal to authority), Presumption (begging the question, false dilemma), Ambiguity (equivocation). The real skill: explaining WHY the reasoning breaks, not just slapping a label on it.',
    quiz: {
      seed: [
        { q: '"Don\'t listen to her about health — she\'s overweight!" This is:', opts: ['Good reasoning', 'Ad hominem — attacking the person, not the argument', 'A fair point', 'Logical'], ans: 1 },
        { q: '"You\'re either with us or against us." This is:', opts: ['True', 'False dilemma — ignoring middle positions', 'Inspiring', 'Logical'], ans: 1 },
        { q: '"Everyone is buying this product!" This appeals to:', opts: ['Logic', 'Popularity (bandwagon) — not evidence of quality', 'Authority', 'Evidence'], ans: 1 },
        { q: '"We should trust the scientist because she\'s an expert." This is:', opts: ['A fallacy', 'Reasonable — but only if she\'s expert in the relevant field', 'Always wrong', 'Always right'], ans: 1 },
        { q: '"If we allow X, next will come Y, then Z!" This is:', opts: ['Good prediction', 'Slippery slope — assuming each step inevitably follows', 'Logical', 'A warning'], ans: 1 },
        { q: '"This is right because it\'s always been done this way." This is:', opts: ['Tradition = truth', 'Appeal to tradition — age doesn\'t prove correctness', 'Wise', 'Logical'], ans: 1 },
        { q: '"You can\'t prove ghosts DON\'T exist!" This is:', opts: ['Good argument', 'Shifting burden of proof — the claim-maker must provide evidence', 'True', 'Logical'], ans: 1 },
        { q: '"My uncle smoked and lived to 95, so smoking isn\'t dangerous." This is:', opts: ['Proof', 'Anecdotal evidence — one case doesn\'t disprove statistics', 'Reasonable', 'Valid'], ans: 1 },
        { q: 'A straw man is when you:', opts: ['Build something', 'Misrepresent someone\'s argument to make it easier to attack', 'Strengthen their position', 'Ignore them'], ans: 1 },
        { q: 'The point of learning fallacies:', opts: ['Win arguments', 'Recognize when reasoning breaks — in others AND yourself', 'Impress people', 'Pass tests'], ans: 1 },
      ],
      growth: [
        { q: '"We can\'t afford to fund both education AND defense." This may be:', opts: ['True', 'False dilemma — the budget may allow both, or other cuts exist', 'Fiscal responsibility', 'Logical'], ans: 1 },
        { q: 'Appeal to authority is fallacious WHEN:', opts: ['Always', 'The authority cited is not expert in the relevant domain, or experts disagree', 'Never', 'Rarely'], ans: 1 },
        { q: 'Circular reasoning means:', opts: ['Going in circles', 'The conclusion is assumed in the premise — "It\'s true because it says so"', 'Repetition', 'Strong emphasis'], ans: 1 },
        { q: 'Equivocation uses:', opts: ['Big words', 'The same word in two different senses to make an argument seem valid', 'Quotes', 'Statistics'], ans: 1 },
        { q: '"Evolution is just a theory." Equivocation on "theory" because:', opts: ['It\'s true', 'In common usage "theory" = guess; in science "theory" = well-tested explanation', 'Evolution is wrong', 'No equivocation'], ans: 1 },
        { q: 'Ad hominem is sometimes NOT fallacious when:', opts: ['Never', 'The person\'s character is directly relevant (e.g., a liar testifying)', 'Always acceptable', 'The person is wrong'], ans: 1 },
        { q: 'A fallacy can be persuasive because:', opts: ['People are stupid', 'It mimics valid reasoning — the error is structural, not obvious', 'Fallacies are true', 'Logic doesn\'t matter'], ans: 1 },
        { q: 'The best response to a fallacy in debate:', opts: ['Name the fallacy', 'Explain WHY the reasoning doesn\'t work — naming alone isn\'t sufficient', 'Ignore it', 'Get angry'], ans: 1 },
        { q: 'The "fallacy fallacy": claiming an argument is wrong because it contains a fallacy. This is wrong because:', opts: ['It\'s not', 'A bad argument can still have a true conclusion — conclusion must be evaluated on its own', 'Fallacies always mean wrong', 'Never happens'], ans: 1 },
        { q: 'The most important fallacy to recognize in yourself:', opts: ['Ad hominem', 'Confirmation bias — seeking evidence that supports what you already believe', 'Straw man', 'Red herring'], ans: 1 },
      ],
      canopy: [
        { q: 'Some "fallacy" accusations are themselves fallacious because:', opts: ['Always', 'Informal fallacies are often defeasible — imperfect reasoning isn\'t the same as fallacious', 'Never', 'Rarely'], ans: 1 },
        { q: 'Deference to expertise is reasonable when:', opts: ['Always', 'Relevant credentials, expert consensus, and the claim is within their domain', 'Never', 'The expert is famous'], ans: 1 },
        { q: 'The line between "fallacious appeal to authority" and "reasonable trust" is:', opts: ['Clear', 'Genuinely difficult and context-dependent', 'Nonexistent', 'Always the same'], ans: 1 },
        { q: '"You\'re committing a fallacy!" can itself be a rhetorical weapon because:', opts: ['It can\'t', 'Naming a fallacy can shut down legitimate reasoning by making it seem illegitimate', 'Labels are always accurate', 'Logic is objective'], ans: 1 },
        { q: 'Many important historical arguments contain what could be called fallacies. This suggests:', opts: ['They\'re all wrong', 'Fallacy labels sometimes oversimplify — context, stakes, and practical reasoning matter', 'History is illogical', 'Fallacies don\'t exist'], ans: 1 },
        { q: 'The Talmudic "elu v\'elu" (these and these are words of the living God) challenges:', opts: ['Nothing', 'The assumption that arguments must end with one winner — some disagreements are permanently productive', 'Logic itself', 'Fallacy theory'], ans: 1 },
        { q: 'Cognitive biases (anchoring, framing) differ from fallacies because:', opts: ['They don\'t differ', 'Biases are psychological tendencies; fallacies are structural reasoning errors — but they interact', 'Biases are worse', 'Fallacies are worse'], ans: 1 },
        { q: 'A "steel man" is harder but better than a straw man because:', opts: ['It\'s nicer', 'If you defeat the strongest version, your position is genuinely strong; if not, you learn', 'It shows respect', 'It\'s required'], ans: 1 },
        { q: 'Fallacy recognition is ultimately about:', opts: ['Classification', 'Intellectual self-honesty — the tools are meant for examining your own reasoning first', 'Debate skills', 'Academic exercise'], ans: 1 },
        { q: 'The most sophisticated lesson of this unit:', opts: ['Memorize all fallacies', 'Read charitably first, then critically — and be as vigilant about your own reasoning as others\'', 'Win every argument', 'Never commit fallacies'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Find an ad (on TV, online, or in a store) that\'s trying to persuade you using something other than evidence. Describe the ad and explain the trick in 3-4 sentences.' },
      growth: { prompt: 'Find a real argument online that contains a fallacy. Quote the argument, name and explain the fallacy, then rewrite the argument WITHOUT the fallacy. Is the cleaned-up version still convincing?' },
      canopy: { prompt: 'Some important historical arguments contain "fallacies." Choose one (e.g., an argument from a founding document, a famous speech, a religious text). Is calling it a fallacy fair, or does the label oversimplify? Write 250 words.' },
    },
    encounter: {
      text: '"You say we should have stricter environmental regulations. But you drove here in a car. How can you argue for the environment when you yourself contribute to pollution?"',
      attribution: '— Common argument pattern',
      questions: [
        { tier: 'seed', q: 'Is this a good argument? Why or why not?' },
        { tier: 'growth', q: 'This is called tu quoque ("you too") — a type of ad hominem. But does a person\'s hypocrisy actually make their argument wrong? Explain the difference between the person and their reasoning.' },
        { tier: 'canopy', q: 'When IS a person\'s behavior relevant to their argument? Write 200 words on where the line falls between legitimate character evidence and ad hominem fallacy.' },
      ]
    },
    bridge: 'Fallacies are patterns of bad reasoning in deductive arguments. But most real-world reasoning isn\'t deductive — it\'s inductive. Unit 6: Patterns and Probability.',
  },
  {
    id: 'l6', title: 'Patterns and Probability', subtitle: 'Inductive reasoning and its limits',
    anchorTexts: 'Scientific discovery, Hume\'s problem of induction, "The Boy Who Cried Wolf"',
    learn: 'Deduction gives certainty: if premises are true, conclusion must be true. Induction gives probability: this has happened many times, so it will probably happen again. Most daily reasoning is inductive — and that\'s fine, as long as we know the limits. Sample size matters. Representativeness matters. And Hume showed that induction itself can\'t be proven to work — we just trust that the future will resemble the past.',
    quiz: {
      seed: [
        { q: '"Every swan I\'ve seen is white, so all swans are white." This is:', opts: ['Deductive', 'Inductive — general conclusion from specific observations', 'A fact', 'A fallacy'], ans: 1 },
        { q: 'Inductive reasoning is:', opts: ['Certain', 'Probable but never 100% certain', 'Useless', 'Same as deductive'], ans: 1 },
        { q: 'Surveying 10 people vs 10,000. Which gives stronger evidence?', opts: ['10 people', '10,000 — larger sample', 'Same', 'Depends on questions'], ans: 1 },
        { q: '"I flipped heads 5 times, so next will be heads." This is:', opts: ['Correct', 'Wrong — each flip is independent', 'Inductive', 'Deductive'], ans: 1 },
        { q: 'Patterns in small samples can be:', opts: ['Always meaningful', 'Coincidence — small samples are unreliable', 'Proof', 'Science'], ans: 1 },
        { q: '"It worked for me" is:', opts: ['Strong evidence', 'An anecdote — one case, not data', 'Proof', 'Scientific'], ans: 1 },
        { q: 'Science uses induction to:', opts: ['Prove theories', 'Build well-supported theories that could be revised by new evidence', 'Guess', 'Create facts'], ans: 1 },
        { q: 'Correlation means:', opts: ['Causation', 'Two things occur together — NOT necessarily cause', 'Proof', 'Nothing'], ans: 1 },
        { q: 'Ice cream sales and drowning both rise in summer. Ice cream causes drowning?', opts: ['Yes', 'No — both caused by a third factor (heat)', 'Maybe', 'Probably'], ans: 1 },
        { q: 'Strong inductive reasoning requires:', opts: ['Certainty', 'Large, representative samples and awareness of limitations', 'Small samples', 'Opinions'], ans: 1 },
      ],
      growth: [
        { q: '"The sun has risen every day, so it will tomorrow." This is:', opts: ['Certain', 'Extremely strong induction but not logically certain', 'Deductive', 'A fact'], ans: 1 },
        { q: 'Hume\'s problem of induction:', opts: ['Induction is wrong', 'We can\'t justify induction through logic — we assume the future resembles the past', 'Hume was wrong', 'Induction is deduction'], ans: 1 },
        { q: 'Despite Hume, we use induction because:', opts: ['He was wrong', 'It works extraordinarily well in practice — the question is philosophical, not practical', 'We have no choice', 'Science proved Hume wrong'], ans: 1 },
        { q: 'Base rate neglect: test is 99% accurate, disease is 1 in 10,000. You test positive. Probability you\'re sick?', opts: ['99%', 'About 1% — most positives are false due to low base rate', '50%', '100%'], ans: 1 },
        { q: 'This is counterintuitive because:', opts: ['Math is hard', 'We focus on test accuracy and ignore how rare the disease is', 'It\'s wrong', 'Tests are unreliable'], ans: 1 },
        { q: 'Representative sample means:', opts: ['Big sample', 'Sample that reflects the actual population in relevant ways', 'Random', 'Small but detailed'], ans: 1 },
        { q: 'Survivorship bias:', opts: ['Studying survivors', 'We see successes but not failures, leading to skewed conclusions', 'Survival of fittest', 'Nothing important'], ans: 1 },
        { q: 'Confirmation bias in induction:', opts: ['Confirming hypotheses', 'Seeking evidence that supports existing beliefs while ignoring contradicting evidence', 'Being confident', 'Testing claims'], ans: 1 },
        { q: 'Falsifiability (Popper): a good scientific theory must:', opts: ['Be proven true', 'Be potentially disprovable by evidence', 'Be popular', 'Be old'], ans: 1 },
        { q: 'The deepest lesson: induction is:', opts: ['Unreliable', 'Our most powerful tool AND inherently uncertain — holding both truths is maturity', 'Perfect', 'Same as deduction'], ans: 1 },
      ],
      canopy: [
        { q: 'Hume showed induction can\'t be justified by:', opts: ['Science', 'Either deduction (circular) or induction (circular) — it\'s a foundational assumption', 'Mathematics', 'Common sense'], ans: 1 },
        { q: 'Popper\'s solution: science doesn\'t prove, it:', opts: ['Guesses', 'Conjectures and refutes — we can\'t verify universals but can falsify them', 'Ignores Hume', 'Uses deduction'], ans: 1 },
        { q: 'Bayesian reasoning updates beliefs by:', opts: ['Ignoring priors', 'Combining prior probability with new evidence to calculate posterior probability', 'Deduction only', 'Intuition'], ans: 1 },
        { q: 'The replication crisis in science suggests:', opts: ['Science is fake', 'Published findings based on small samples and flexible methods may not hold', 'Science is broken', 'Nothing'], ans: 1 },
        { q: 'The Boy Who Cried Wolf: villagers\' reasoning was:', opts: ['Foolish', 'Good induction based on past evidence — which makes the story tragic', 'Random', 'Deductive'], ans: 1 },
        { q: 'Goodman\'s "grue" paradox challenges induction by showing:', opts: ['Induction is worthless', 'Any set of observations is compatible with infinitely many generalizations', 'Colors don\'t exist', 'Logic is broken'], ans: 1 },
        { q: 'Does science produce knowledge or justified belief?', opts: ['Knowledge', 'Justified belief — well-supported but revisable', 'Neither', 'Both equally'], ans: 1 },
        { q: 'The relationship between induction and the scientific method:', opts: ['Identical', 'Science uses induction within a framework of hypothesis, testing, and revision that mitigates its limitations', 'Unrelated', 'Science transcends induction'], ans: 1 },
        { q: 'For practical reasoning, the right response to uncertainty is:', opts: ['Paralysis', 'Calibrated confidence — as certain as evidence warrants, no more', 'Ignore uncertainty', 'Only accept certainty'], ans: 1 },
        { q: 'Mastering inductive reasoning means:', opts: ['Accepting uncertainty', 'Thinking rigorously about evidence quality, sample size, base rates, and your own biases', 'Never being wrong', 'Avoiding induction'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'What patterns do you notice in your daily life? (E.g., "It\'s always colder on Mondays.") Pick one pattern, predict what will happen tomorrow, then check. Was your prediction right? Why or why not?' },
      growth: { prompt: 'Design a simple experiment to test a claim like "People walk faster when it\'s cold" or "Students focus better in the morning." What would make the evidence strong or weak? Describe your method and explain potential problems.' },
      canopy: { prompt: 'Does science produce knowledge or justified belief? Write 200 words using the problem of induction. How should the answer affect how we treat scientific findings in public policy?' },
    },
    encounter: {
      text: '"A boy tended sheep near a village. Bored, he cried \'Wolf!\' Villagers came running but found no wolf. He did it again. They came again. When a wolf truly came and the boy cried out, no one came. The wolf devoured the flock."',
      attribution: '— Aesop, "The Boy Who Cried Wolf"',
      questions: [
        { tier: 'seed', q: 'Why did the villagers stop coming? Were they being reasonable?' },
        { tier: 'growth', q: 'The villagers used inductive reasoning: past cries were false → this cry is probably false. Was this GOOD induction? (Yes — which is what makes the story tragic, not stupid.)' },
        { tier: 'canopy', q: 'The boy\'s real failure was destroying the evidence system. Write 200 words on trust as the foundation of communication. When credibility is destroyed, even truth becomes unbelievable. Connect this to rhetoric.' },
      ]
    },
    bridge: 'Induction gives us probabilities from patterns. But we also reason by comparison and analogy — Unit 7.',
  },
  {
    id: 'l7', title: 'Thinking by Comparison', subtitle: 'Analogies and their limits',
    anchorTexts: '"The heart is a pump," legal precedent, Talmudic gezera shava',
    learn: 'Analogies are how we understand the unfamiliar through the familiar. "The heart is a pump" is genuinely useful — but if you take it too far (hearts don\'t have on/off switches), it misleads. Every analogy illuminates AND obscures. The strength depends on whether the similarities are relevant. Knowing when an analogy breaks is as important as seeing it.',
    quiz: {
      seed: [
        { q: 'An analogy says:', opts: ['A equals B', 'A is LIKE B in relevant ways', 'A causes B', 'A and B are identical'], ans: 1 },
        { q: '"The brain is a computer." This helps us understand:', opts: ['Computers', 'How the brain processes information', 'Brains are machines', 'Nothing'], ans: 1 },
        { q: 'Every analogy has:', opts: ['Perfect accuracy', 'A breaking point where the comparison stops working', 'Infinite applications', 'No limits'], ans: 1 },
        { q: '"Life is a journey." This breaks down because:', opts: ['Life isn\'t a road', 'Journeys have clear destinations; life often doesn\'t', 'It\'s a cliché', 'It\'s wrong'], ans: 1 },
        { q: 'A strong analogy has:', opts: ['Emotional appeal', 'Relevant similarities between the two things', 'Lots of details', 'Famous sources'], ans: 1 },
        { q: '"The economy is like a household budget." This might mislead because:', opts: ['Economies and households are identical', 'Governments can print money and borrow differently than households', 'Economics is hard', 'It\'s accurate'], ans: 1 },
        { q: 'Lawyers use analogies when they:', opts: ['Appeal emotionally', 'Argue a current case is LIKE a past case, so same ruling should apply', 'Make things up', 'Never do this'], ans: 1 },
        { q: 'When evaluating an analogy, ask:', opts: ['Is it clever?', 'Are the relevant similarities strong enough to support the conclusion?', 'Is it new?', 'Is it long?'], ans: 1 },
        { q: 'Two things can be similar in some ways and:', opts: ['Must be similar in all ways', 'Different in others — every analogy has limits', 'Identical', 'Unrelated'], ans: 1 },
        { q: 'The best response to a misleading analogy:', opts: ['Reject all analogies', 'Show where the comparison breaks down', 'Accept it', 'Ignore it'], ans: 1 },
      ],
      growth: [
        { q: 'Legal precedent works by analogy: this case resembles that case. It fails when:', opts: ['Courts change', 'The cases differ in relevant ways the analogy obscures', 'Laws change', 'Never'], ans: 1 },
        { q: '"Economy as ecosystem" vs "economy as household." Different analogies suggest:', opts: ['Same policies', 'Different policies — ecosystem implies balance; budget implies austerity', 'Nothing different', 'One is right'], ans: 1 },
        { q: 'Talmudic gezera shava connects two laws because they share a word. This is:', opts: ['Simple analogy', 'Linguistic analogy — shared word bridges legal contexts', 'Word play', 'Irrelevant'], ans: 1 },
        { q: 'A scientific model is essentially:', opts: ['A replica', 'A structured analogy — highlighting relevant features while simplifying', 'A guess', 'A picture'], ans: 1 },
        { q: '"All models are wrong; some are useful" means:', opts: ['Models are bad', 'Models illuminate aspects of reality even though they simplify', 'We should stop modeling', 'Models are right'], ans: 1 },
        { q: 'Identifying WHICH similarities are relevant is:', opts: ['Easy', 'The hardest part of analogical reasoning', 'Unnecessary', 'Automatic'], ans: 1 },
        { q: 'False analogy (fallacy) occurs when:', opts: ['Any analogy is used', 'Things compared are too different in relevant ways', 'Analogies are long', 'Never'], ans: 1 },
        { q: 'Metaphors in everyday speech are:', opts: ['Not analogies', 'Compressed analogies — "He\'s a snake" means he\'s LIKE a snake in relevant ways', 'Literal', 'Decoration'], ans: 1 },
        { q: 'The strongest use of analogy:', opts: ['Proving claims', 'Generating insight — seeing something familiar in a new way', 'Winning arguments', 'Decoration'], ans: 1 },
        { q: 'Analogical reasoning is:', opts: ['Inferior to deduction', 'Fundamental to human cognition — we understand new by mapping to known', 'Only for arguments', 'A fallacy'], ans: 1 },
      ],
      canopy: [
        { q: 'Gezera shava differs from standard analogy because:', opts: ['It\'s religious', 'The connection is verbal (shared word), not substantive — a different theory of meaning-transfer', 'It\'s weaker', 'No difference'], ans: 1 },
        { q: 'This raises the question:', opts: ['Is it valid?', 'Does linguistic form carry meaning independent of content? Can shared language create conceptual connections?', 'Is it outdated?', 'Nothing'], ans: 1 },
        { q: 'Kuhn argued scientific revolutions replace one model/analogy with another. This means:', opts: ['Science is arbitrary', 'Analogies structure entire paradigms — they\'re not just rhetorical tools', 'Kuhn was wrong', 'Science doesn\'t use analogies'], ans: 1 },
        { q: 'The trivium itself: building, journey, or conversation?', opts: ['Building', 'Journey', 'Conversation', 'Each illuminates AND obscures — the question reveals how analogies shape understanding'], ans: 3 },
        { q: 'Legal reasoning by precedent assumes:', opts: ['Past always relevant', 'Similar cases deserve similar treatment — but defining "similar" is the entire challenge', 'Courts are consistent', 'Nothing philosophical'], ans: 1 },
        { q: 'At its deepest, analogical reasoning reveals:', opts: ['Everything is connected', 'We never understand anything "directly" — all understanding maps new experience onto prior frameworks', 'Analogies are optional', 'Logic is sufficient'], ans: 1 },
        { q: 'The limit of analogy is also its power:', opts: ['It\'s approximate', 'Simplification is what makes complex things graspable', 'It\'s weak', 'No limit exists'], ans: 1 },
        { q: 'Mixing metaphors ("hit the ground running and dive deep") fails because:', opts: ['Grammar', 'The analogies contradict — can\'t run and dive simultaneously', 'It\'s informal', 'It doesn\'t fail'], ans: 1 },
        { q: 'The relationship between analogy and logic:', opts: ['Analogy isn\'t logical', 'Analogy is a form of reasoning with its own rigor — weaker than deduction but essential for discovery', 'They\'re separate', 'Logic includes analogy'], ans: 1 },
        { q: 'Mastering analogical reasoning:', opts: ['Avoid analogies', 'See them everywhere, evaluate rigorously, know when they illuminate and when they mislead', 'Use more analogies', 'Stick to deduction'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Explain something you know well (a hobby, a concept, a place) to someone unfamiliar with it, using a comparison. Example: "Learning guitar is like learning a language — you start with vocabulary (chords) before you can make sentences (songs)."' },
      growth: { prompt: 'Find an analogy used in a public debate (political, scientific, cultural). Where does it illuminate? Where does it mislead? Who benefits from the comparison, and who might be harmed by it?' },
      canopy: { prompt: 'Argue for one analogy for the trivium: is it best understood as a building (foundation up), a journey (sequential path), or a conversation (simultaneous voices)? Defend your choice, then identify its breaking point. (200 words)' },
    },
    encounter: {
      text: '"The economy is like a household budget — you can\'t spend more than you earn."',
      attribution: '— Common political analogy',
      questions: [
        { tier: 'seed', q: 'How is an economy like a household budget? How is it different?' },
        { tier: 'growth', q: 'What policies does this analogy support? What might change if we said "the economy is like an ecosystem" instead?' },
        { tier: 'canopy', q: 'Analogies don\'t just illustrate — they constrain thought. Write 200 words on how the choice of analogy determines the range of "reasonable" policy options. When you change the metaphor, you change the debate.' },
      ]
    },
    bridge: 'Analogies generate hypotheses. But how do we test them with evidence? Unit 8.',
  },
  {
    id: 'l8', title: 'What Counts as Evidence?', subtitle: 'Anecdote, data, and the hierarchy of proof',
    anchorTexts: 'Correlation-causation errors, the replication crisis, courtroom standards',
    learn: 'Not all evidence is equal. Your friend\'s experience (anecdote) is real but not representative. A study of 10,000 people is stronger. A controlled experiment is stronger still. A meta-analysis of many experiments is strongest. And correlation never proves causation — ice cream sales and drowning both rise in summer, but ice cream doesn\'t cause drowning. Heat does.',
    quiz: {
      seed: [
        { q: 'A friend\'s experience vs a study of 10,000 people:', opts: ['Friend is better', 'Study is stronger evidence', 'Same', 'Depends'], ans: 1 },
        { q: 'Correlation means:', opts: ['One causes the other', 'Two things happen together', 'Proof', 'Nothing'], ans: 1 },
        { q: 'Ice cream sales and drowning rise together. Ice cream causes drowning?', opts: ['Yes', 'No — both rise because of heat', 'Probably', 'Maybe'], ans: 1 },
        { q: '"I took vitamin C and my cold went away!" This is:', opts: ['Proof', 'Anecdote — the cold might have gone away anyway', 'Science', 'Strong evidence'], ans: 1 },
        { q: 'Larger studies are usually better because:', opts: ['More work', 'Patterns in small groups can be coincidence', 'Bigger is always better', 'Scientists prefer them'], ans: 1 },
        { q: 'A controlled experiment is strong because:', opts: ['It\'s expensive', 'It isolates the variable being tested', 'It\'s long', 'It uses technology'], ans: 1 },
        { q: '"Studies show..." might mislead if:', opts: ['Studies are always right', 'The study is small, biased, or misrepresented', 'Science is unreliable', 'Never'], ans: 1 },
        { q: 'An anecdote is:', opts: ['Evidence', 'A personal story — real but not representative', 'Data', 'Proof'], ans: 1 },
        { q: 'The best evidence is:', opts: ['What you believe', 'A systematic review of many well-designed studies', 'An expert\'s opinion', 'A single perfect study'], ans: 1 },
        { q: 'Why does evidence quality matter?', opts: ['School', 'Bad evidence leads to wrong conclusions and bad decisions', 'It doesn\'t', 'Only for scientists'], ans: 1 },
      ],
      growth: [
        { q: 'Hierarchy of evidence (weakest to strongest):', opts: ['Study, expert, anecdote', 'Anecdote < expert < observational < experimental < meta-analysis', 'All equal', 'Depends on topic'], ans: 1 },
        { q: 'Observational studies can show correlation but not:', opts: ['Anything', 'Causation — other factors aren\'t controlled', 'Correlation', 'Data'], ans: 1 },
        { q: 'A randomized controlled trial (RCT) establishes causation by:', opts: ['Being expensive', 'Randomly assigning groups so the only difference is the variable tested', 'Using placebos', 'Being published'], ans: 1 },
        { q: 'The placebo effect shows:', opts: ['Medicine is fake', 'Belief alone can produce measurable changes — which is why controls are needed', 'Nothing', 'Placebos work'], ans: 1 },
        { q: 'Publication bias means:', opts: ['Published = true', 'Studies with positive results get published more than negative ones, skewing the evidence', 'Publishing is unbiased', 'Nothing important'], ans: 1 },
        { q: 'Cherry-picking evidence means:', opts: ['Choosing the best studies', 'Selecting only evidence that supports your position while ignoring contradicting evidence', 'Good research', 'Nothing wrong'], ans: 1 },
        { q: 'A confounding variable is:', opts: ['A complex variable', 'A hidden factor that affects both things being measured, creating a false appearance of causation', 'Unimportant', 'Always detectable'], ans: 1 },
        { q: '"Correlation does not imply causation" is important because:', opts: ['Correlations are useless', 'People naturally assume causation when they see correlation — and are often wrong', 'It\'s a rule', 'Nothing practical'], ans: 1 },
        { q: 'In a courtroom, "beyond reasonable doubt" vs "preponderance of evidence" reflects:', opts: ['Legal jargon', 'Different standards of proof for different stakes — criminal vs civil', 'The same standard', 'Nothing logical'], ans: 1 },
        { q: 'The deepest lesson about evidence:', opts: ['Trust science', 'Always ask: How do we know this? What\'s the quality of the evidence? What might be missing?', 'Ignore anecdotes', 'Only trust experiments'], ans: 1 },
      ],
      canopy: [
        { q: 'The replication crisis (many published studies fail to replicate) suggests:', opts: ['Science is fake', 'Our evidence standards were too lax — small samples, flexible methods, and publication bias produced unreliable findings', 'Science is broken', 'Nothing'], ans: 1 },
        { q: 'P-hacking (manipulating analysis to get significant results) is a problem because:', opts: ['It\'s illegal', 'It makes random noise look like real findings', 'It\'s rare', 'Only in bad labs'], ans: 1 },
        { q: 'Pre-registration (publicly committing to methods before collecting data) helps because:', opts: ['It\'s bureaucracy', 'It prevents researchers from adjusting methods to get desired results', 'It\'s optional', 'It doesn\'t help'], ans: 1 },
        { q: 'Bayesian vs. frequentist statistics represents:', opts: ['A minor disagreement', 'Two fundamentally different philosophies of what probability means and how evidence updates belief', 'The same thing', 'Only academic'], ans: 1 },
        { q: 'In Torah study, what counts as "evidence" for an interpretation?', opts: ['Nothing — it\'s faith', 'Textual evidence: word choice, parallel passages, structural patterns, intertextual resonance', 'Tradition only', 'Authority only'], ans: 1 },
        { q: 'The parallel between scientific evidence evaluation and textual evidence evaluation:', opts: ['None', 'Both require rigorous standards, skepticism of easy answers, and awareness of bias', 'Science is better', 'Texts are better'], ans: 1 },
        { q: 'Expert consensus is strong evidence but not infallible because:', opts: ['Experts are wrong', 'Consensus has been wrong before (ulcers, continental drift) — but it\'s still the best available guide', 'Always right', 'Never useful'], ans: 1 },
        { q: 'The standard "extraordinary claims require extraordinary evidence" (Sagan) means:', opts: ['Normal claims need no evidence', 'The more a claim defies established knowledge, the stronger the evidence must be', 'Extraordinary claims are always false', 'Only applies to science'], ans: 1 },
        { q: 'For practical decisions under uncertainty:', opts: ['Wait for certainty', 'Act on the best available evidence while remaining open to revision', 'Ignore evidence', 'Trust intuition'], ans: 1 },
        { q: 'Evidence literacy means:', opts: ['Reading papers', 'Habitually asking about evidence quality, sources of bias, alternative explanations, and what would change your mind', 'Trusting science', 'Being skeptical of everything'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Think of something you believe is true (e.g., "breakfast is the most important meal"). What\'s your evidence? Is it an anecdote, something you read, or something you were told? How strong is it really?' },
      growth: { prompt: 'Find a news article that claims "X causes Y." Does the underlying study show causation or just correlation? What confounding variables might be at play? Write a 150-word analysis.' },
      canopy: { prompt: 'Compare how "evidence" works in two different domains: science and Torah study. What counts as strong evidence in each? What are the standards of proof? Where do the methods overlap, and where do they diverge? (250 words)' },
    },
    encounter: {
      text: '"A new study finds that people who eat chocolate daily live longer than those who don\'t. Researchers followed 5,000 adults over 10 years and found a significant correlation between chocolate consumption and longevity."',
      attribution: '— Hypothetical news report',
      questions: [
        { tier: 'seed', q: 'Does this prove chocolate makes you live longer? Why or why not?' },
        { tier: 'growth', q: 'This is an observational study showing correlation. Name three possible confounding variables — other explanations for why chocolate-eaters might live longer.' },
        { tier: 'canopy', q: 'Design the experiment that WOULD prove causation. What would you control for? Why is this experiment probably impossible or unethical to run? What does that tell us about the limits of evidence in nutrition science?' },
      ]
    },
    bridge: 'Evidence evaluation is where Logic meets the real world. But in complex real-world situations, we often can\'t prove things definitively — we have to reason under uncertainty. Unit 9.',
  },
  {
    id: 'l9', title: 'Reasoning Under Uncertainty', subtitle: 'When you can\'t be sure',
    anchorTexts: 'Pascal\'s Wager, medical decision-making, the Trolley Problem',
    learn: 'Most real decisions happen under uncertainty. You don\'t know the future. You don\'t have all the facts. You have to decide anyway. This unit explores frameworks for reasoning when certainty is impossible: expected value, risk assessment, precautionary principles, and the difference between "I don\'t know" and "Nobody can know."',
    quiz: {
      seed: [
        { q: 'Most real-life decisions are made with:', opts: ['Complete information', 'Incomplete information — you decide under uncertainty', 'No information', 'Perfect logic'], ans: 1 },
        { q: '"I\'m not sure, so I\'ll do nothing" is:', opts: ['Wise', 'Also a decision — inaction has consequences too', 'Safe', 'Logical'], ans: 1 },
        { q: 'Expected value means:', opts: ['What you expect to happen', 'The average outcome if you made this decision many times', 'The best outcome', 'The worst outcome'], ans: 1 },
        { q: 'A 10% chance of winning $100 has an expected value of:', opts: ['$100', '$10', '$0', '$90'], ans: 1 },
        { q: '"Better safe than sorry" is a version of:', opts: ['Risk aversion', 'The precautionary principle — when uncertain, avoid potential harm', 'Cowardice', 'Logic'], ans: 1 },
        { q: 'But "better safe than sorry" can also lead to:', opts: ['Good outcomes', 'Paralysis — you can\'t act if you\'re always avoiding risk', 'Nothing bad', 'Perfect decisions'], ans: 1 },
        { q: '"I don\'t know" vs "Nobody can know" — the difference:', opts: ['None', 'The first is about your knowledge; the second is a claim about the limits of all knowledge', 'Both the same', 'First is worse'], ans: 1 },
        { q: 'Making a decision you might regret is:', opts: ['Always wrong', 'Unavoidable — some decisions must be made before all evidence is in', 'Irresponsible', 'Lazy'], ans: 1 },
        { q: 'Risk assessment asks:', opts: ['Is this scary?', 'How likely is the harm AND how severe would it be?', 'Can I avoid all risk?', 'Nothing useful'], ans: 1 },
        { q: 'The goal of reasoning under uncertainty:', opts: ['Eliminate uncertainty', 'Make the best possible decision with the information available', 'Wait for certainty', 'Avoid all decisions'], ans: 1 },
      ],
      growth: [
        { q: 'Pascal\'s Wager: believe in God because if wrong, you lose little; if right, you gain everything. The logical issue:', opts: ['It\'s brilliant', 'It assumes only two options and that belief can be chosen — but there are many possible gods and belief isn\'t a switch', 'It\'s obviously wrong', 'No issues'], ans: 1 },
        { q: 'Expected value works well for:', opts: ['All decisions', 'Repeated decisions (gambling, investment) — less well for one-time, high-stakes choices', 'No decisions', 'Only money'], ans: 1 },
        { q: 'The Trolley Problem tests:', opts: ['Train safety', 'How we reason about moral tradeoffs under pressure — action vs inaction, numbers vs rights', 'Nothing useful', 'Trolley design'], ans: 1 },
        { q: 'Sunk cost fallacy: continuing because you\'ve "already invested too much" is wrong because:', opts: ['It\'s not wrong', 'Past costs are unrecoverable — only future costs and benefits should drive decisions', 'Persistence is good', 'It\'s logical'], ans: 1 },
        { q: 'Reversible vs irreversible decisions should be treated:', opts: ['The same', 'Differently — irreversible decisions deserve more caution and analysis', 'Reversible are harder', 'Neither matters'], ans: 1 },
        { q: 'The precautionary principle (avoid harm when uncertain) is strongest when:', opts: ['Always', 'The potential harm is catastrophic and irreversible', 'Risk is small', 'You\'re anxious'], ans: 1 },
        { q: 'But the precautionary principle can be misused to:', opts: ['Save lives', 'Block all innovation and change by exaggerating potential harms', 'Make good decisions', 'Nothing bad'], ans: 1 },
        { q: 'In medicine, "watchful waiting" is:', opts: ['Negligence', 'A deliberate decision to gather more information before acting — itself a form of reasoning under uncertainty', 'Lazy', 'Always wrong'], ans: 1 },
        { q: 'Decision matrices (listing options, probabilities, outcomes) help by:', opts: ['Eliminating uncertainty', 'Making the structure of a decision visible — even when the numbers are estimates', 'Being accurate', 'Nothing'], ans: 1 },
        { q: 'The key insight: uncertainty is not a deficiency but:', opts: ['A problem to solve', 'The normal condition of rational life — the question is how to reason well within it', 'Unimportant', 'Temporary'], ans: 1 },
      ],
      canopy: [
        { q: 'Decision theory vs virtue ethics: one focuses on outcomes, the other on:', opts: ['Nothing', 'Character — what kind of person makes this choice, regardless of outcome', 'Rules', 'Feelings'], ans: 1 },
        { q: 'Nassim Taleb\'s concept of "antifragility" argues that some systems:', opts: ['Resist disorder', 'Actually benefit from uncertainty, stress, and volatility', 'Need stability', 'Can\'t handle uncertainty'], ans: 1 },
        { q: 'The Talmudic concept of safek (doubt) handles uncertainty by:', opts: ['Eliminating it', 'Developing rules for how to act under different types of doubt — stringency for biblical law, leniency for rabbinic', 'Ignoring doubt', 'Always being strict'], ans: 1 },
        { q: 'This shows that uncertainty management is:', opts: ['Modern', 'An ancient and sophisticated intellectual tradition', 'Simple', 'Only scientific'], ans: 1 },
        { q: 'Epistemic humility — admitting what you don\'t know — is:', opts: ['Weakness', 'A prerequisite for good reasoning, because overconfidence leads to worse decisions', 'Unnecessary for experts', 'Always appropriate'], ans: 1 },
        { q: 'The difference between risk (known probabilities) and uncertainty (unknown probabilities):', opts: ['None', 'Crucial — we can calculate risk but must navigate uncertainty with judgment and wisdom', 'Academic only', 'Risk is worse'], ans: 1 },
        { q: 'Moral reasoning under uncertainty often requires:', opts: ['Rules', 'Judgment — weighing competing values when no algorithm gives the right answer', 'Certainty first', 'Majority vote'], ans: 1 },
        { q: 'The relationship between Logic (Unit 9) and Rhetoric:', opts: ['None', 'Reasoning under uncertainty is where logic meets persuasion — you must ARGUE for your best judgment, not just calculate', 'Logic is better', 'Rhetoric handles certainty'], ans: 1 },
        { q: 'The examined life (Socrates) requires:', opts: ['Certainty', 'The willingness to reason honestly about what you don\'t know — and act anyway', 'Perfect information', 'Avoiding hard questions'], ans: 1 },
        { q: 'The deepest lesson of this unit:', opts: ['Avoid uncertainty', 'Learn to reason, decide, and act well precisely when you cannot be certain — which is most of the time', 'Wait for certainty', 'Trust your instincts'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Think of a decision you\'re facing where you don\'t have all the information (what to study, whether to try something new, etc.). List what you know, what you don\'t know, and what you\'d need to know to be more confident. Then decide anyway — and explain why.' },
      growth: { prompt: 'Analyze a real-world decision made under uncertainty (a medical recommendation, a policy choice, an investment). What information was available? What was unknown? Was the decision reasonable given the uncertainty? Write 150 words.' },
      canopy: { prompt: 'Compare two frameworks for handling uncertainty: expected value calculation vs the precautionary principle. When is each appropriate? Can they conflict? Write 250 words using a concrete example (climate policy, medical treatment, or a personal decision).' },
    },
    encounter: {
      text: '"A philosopher once asked: Is it better to make the wrong decision for the right reasons, or the right decision for the wrong reasons? A doctor prescribes a medication based on the best evidence available. The patient gets worse. A neighbor recommends an herbal remedy based on a hunch. The patient recovers."',
      attribution: '— Thought experiment',
      questions: [
        { tier: 'seed', q: 'Who made the better decision — the doctor or the neighbor? Why?' },
        { tier: 'growth', q: 'The doctor\'s reasoning was sound but the outcome was bad. The neighbor\'s reasoning was weak but the outcome was good. Which matters more — process or result? Can you have good reasoning and bad outcomes?' },
        { tier: 'canopy', q: 'Write 200 words on the difference between evaluating a decision by its process vs its outcome. When should we judge people by their reasoning rather than their results? When might we be wrong to do so?' },
      ]
    },
    bridge: 'Reasoning under uncertainty leads directly to the hardest question: how do we reason about right and wrong? Unit 10.',
  },
  {
    id: 'l10', title: 'The Limits of Logic', subtitle: 'What logic can and cannot do',
    anchorTexts: 'Gödel\'s Incompleteness, the role of wisdom, Ecclesiastes',
    learn: 'Logic is the most powerful tool for clear thinking ever developed. And it has limits. Gödel proved that any sufficiently complex logical system contains truths it cannot prove. The Liar Paradox shows self-reference can break formal systems. And the deepest human questions — what is good? what is meaningful? how should I live? — require more than logic alone. This is where Logic hands the baton to Rhetoric and beyond: to philosophy, theology, and wisdom.',
    quiz: {
      seed: [
        { q: 'Logic is:', opts: ['Perfect', 'The best tool for clear thinking, but not the only tool we need', 'Useless', 'All we need'], ans: 1 },
        { q: 'Can logic tell you what to value?', opts: ['Yes', 'No — logic can test consistency and consequences, but values come from somewhere else', 'Sometimes', 'Always'], ans: 1 },
        { q: '"You should be kind" — can logic alone prove this?', opts: ['Yes', 'No — "should" statements require value judgments logic can\'t generate', 'Sometimes', 'With enough premises'], ans: 1 },
        { q: 'Logic helps us:', opts: ['Know everything', 'Think clearly, test arguments, avoid errors', 'Feel good', 'Win arguments'], ans: 1 },
        { q: 'Logic can\'t help us:', opts: ['Test arguments', 'Decide what matters most in life', 'Find errors', 'Think clearly'], ans: 1 },
        { q: 'Gödel proved that:', opts: ['Logic is useless', 'Some truths exist that logic cannot prove within its own system', 'Math is wrong', 'Everything is uncertain'], ans: 1 },
        { q: 'Wisdom differs from logic because:', opts: ['Wisdom is illogical', 'Wisdom includes judgment, experience, and values alongside logic', 'Logic is wiser', 'No difference'], ans: 1 },
        { q: 'The best thinkers use:', opts: ['Logic only', 'Logic AND judgment, empathy, experience, and moral vision', 'Feelings only', 'Rules only'], ans: 1 },
        { q: 'Logic is to wisdom as:', opts: ['Everything to nothing', 'A map to a journey — essential but not the whole thing', 'Nothing to everything', 'The same thing'], ans: 1 },
        { q: 'After studying Logic, you should be able to:', opts: ['Win every argument', 'Think more clearly, spot errors, and reason honestly — while knowing logic\'s limits', 'Be certain', 'Never be wrong'], ans: 1 },
      ],
      growth: [
        { q: 'Gödel\'s First Incompleteness Theorem says:', opts: ['Math is wrong', 'Any consistent formal system complex enough for arithmetic contains true statements it cannot prove', 'Logic is useless', 'Nothing practical'], ans: 1 },
        { q: 'This matters beyond math because:', opts: ['It doesn\'t', 'It shows that even our most rigorous systems of reasoning have inherent limits', 'Only mathematicians care', 'It disproves logic'], ans: 1 },
        { q: 'The "is-ought problem" (Hume): you cannot derive what OUGHT to be from what IS. This means:', opts: ['Science is useless', 'Logic alone can\'t generate moral conclusions — you always need a value premise', 'Morality is illogical', 'Nothing important'], ans: 1 },
        { q: 'Aristotle\'s phronesis (practical wisdom) differs from logic because:', opts: ['It\'s less rigorous', 'It involves judgment about particular situations, not just general rules', 'It\'s outdated', 'No difference'], ans: 1 },
        { q: 'A person who is logical but not wise might:', opts: ['Be perfect', 'Win arguments but miss what matters — technically correct but humanly wrong', 'Not exist', 'Be better than wise'], ans: 1 },
        { q: 'A person who is wise but not logical might:', opts: ['Be perfect', 'Have good judgment but be vulnerable to reasoning errors', 'Not exist', 'Be better than logical'], ans: 1 },
        { q: 'The ideal is:', opts: ['Logic alone', 'Wisdom alone', 'Logic AND wisdom working together', 'Neither'], ans: 2 },
        { q: '"The heart has its reasons which reason knows not" (Pascal) means:', opts: ['Emotions are irrational', 'There are legitimate modes of understanding (intuition, empathy, faith) that formal logic cannot capture', 'Logic is wrong', 'Feelings are better'], ans: 1 },
        { q: 'The trivium places Logic between Grammar and Rhetoric because:', opts: ['Alphabetical order', 'Grammar gives you the material (language), Logic gives you the method (reasoning), Rhetoric gives you the action (communication)', 'Historical convention', 'No real reason'], ans: 1 },
        { q: 'The greatest value of studying Logic:', opts: ['Being right', 'Developing the habit of honest, rigorous thinking — and knowing when more than logic is needed', 'Winning debates', 'Academic credit'], ans: 1 },
      ],
      canopy: [
        { q: 'Gödel\'s theorems have been interpreted as showing:', opts: ['Math is broken', 'Human understanding may transcend formal systems — we can recognize truths that no system can prove', 'Nothing beyond math', 'Computers can\'t think'], ans: 1 },
        { q: 'Ecclesiastes says "Of making many books there is no end, and much study is a weariness of the flesh." This challenges Logic because:', opts: ['Study is bad', 'Accumulating knowledge and arguments may not lead to wisdom — something beyond analysis is needed', 'Ecclesiastes is anti-intellectual', 'It doesn\'t challenge Logic'], ans: 1 },
        { q: 'The Talmudic tradition values both rigorous logic AND:', opts: ['Blind obedience', 'Humility before mystery — some questions are preserved as permanent openings, not problems to be solved', 'Emotional reasoning', 'Certainty'], ans: 1 },
        { q: 'Levinas argued that the encounter with another person is:', opts: ['A logical problem', 'Prior to and more fundamental than any logical framework — ethics precedes ontology', 'Irrelevant to philosophy', 'Fully capturable by logic'], ans: 1 },
        { q: 'If ethics precedes logic (Levinas), then:', opts: ['Logic is useless for ethics', 'The most important things about human life may not be the things logic handles best', 'Levinas was wrong', 'Ethics is illogical'], ans: 1 },
        { q: 'Wittgenstein ended the Tractatus with "Whereof one cannot speak, thereof one must be silent." This suggests:', opts: ['Silence is golden', 'Logic has a boundary beyond which the most important things (ethics, aesthetics, the mystical) lie — they are real but not capturable in propositions', 'Don\'t talk about hard things', 'Logic covers everything'], ans: 1 },
        { q: 'The medieval concept of the liberal arts placed Logic as a tool FOR:', opts: ['Winning', 'The higher pursuit of philosophy and theology — logic serves wisdom, not the reverse', 'Its own sake', 'Employment'], ans: 1 },
        { q: 'This means the trivium\'s structure itself argues:', opts: ['Logic is supreme', 'Logic is essential but instrumental — it prepares you for encounters with meaning that exceed its scope', 'Logic is unnecessary', 'All subjects are equal'], ans: 1 },
        { q: 'The capstone insight of Logic:', opts: ['Logic is the ultimate tool', 'Mastering logic includes mastering the knowledge of when to rely on something beyond logic', 'Logic should be abandoned', 'Nothing beyond logic matters'], ans: 1 },
        { q: 'Having completed Logic, you are now prepared for Rhetoric because:', opts: ['You need a new subject', 'You can think clearly (Logic) and read closely (Grammar) — now you must learn to communicate truth to others, which requires wisdom, judgment, and art', 'Rhetoric is easier', 'Convention dictates it'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Think of a question that logic alone can\'t answer (e.g., "What makes a good friend?" "Is it ever right to lie?"). Write your answer in 3-4 sentences. What are you using besides logic to get there?' },
      growth: { prompt: 'A friend says: "I can\'t decide whether to pursue a career I love that pays poorly or one I find boring that pays well." Use everything you\'ve learned in Logic to analyze this decision — and then explain why logic alone can\'t make the choice for them. (200 words)' },
      canopy: { prompt: 'Write 300 words on the relationship between logic and wisdom. Use at least one thinker we\'ve encountered (Gödel, Hume, Aristotle, Wittgenstein, the Talmudic tradition) to argue that logic is necessary but not sufficient for the good life. What fills the gap?' },
    },
    encounter: {
      text: '"To every thing there is a season, and a time to every purpose under the heaven: A time to be born, and a time to die; a time to plant, and a time to pluck up that which is planted... a time to keep silence, and a time to speak."',
      attribution: '— Ecclesiastes 3:1-7 (KJV)',
      questions: [
        { tier: 'seed', q: 'Ecclesiastes says there\'s a time for opposite things — silence AND speaking, planting AND uprooting. What kind of wisdom is this? Can logic tell you WHEN the time is right?' },
        { tier: 'growth', q: '"A time to keep silence, and a time to speak." Logic can help you think clearly, but it can\'t tell you when to stay quiet. What other capacities (beyond logic) does knowing "the right time" require?' },
        { tier: 'canopy', q: 'Ecclesiastes is often read as skeptical of intellectual pursuit: "much study is a weariness of the flesh." Yet it\'s preserved in the canon of sacred texts — studied endlessly by the very scholars it seems to warn. Write 250 words on this paradox. What does it mean to study a text that questions the value of study?' },
      ]
    },
    bridge: 'Logic is complete. You can think clearly. Grammar gave you the ability to read. Logic gave you the ability to reason. Now Rhetoric asks: Can you move others? Can you communicate truth in a way that changes the world?',
  },
];
