// RHETORIC CURRICULUM — 10 units, 3 tiers, all modes

export const RHETORIC = [
  {
    id: 'r1', title: 'Why Rhetoric Matters', subtitle: 'The power and ethics of persuasion',
    anchorTexts: 'Plato vs Aristotle, MLK\'s "I Have a Dream"',
    learn: 'Rhetoric is the art of effective communication — persuasion, clarity, beauty, and the ability to move others. Plato feared rhetoric as manipulation. Aristotle redeemed it as a skill every citizen needs. You already use rhetoric every time you argue, explain, or ask. The question is whether you use it well and honestly.',
    quiz: {
      seed: [
        { q: 'Rhetoric is:', opts: ['Lying', 'The art of effective, persuasive communication', 'Yelling louder', 'Only for politicians'], ans: 1 },
        { q: 'You use rhetoric when you:', opts: ['Only in speeches', 'Explain, argue, persuade, or ask — daily', 'Never', 'Only when writing'], ans: 1 },
        { q: 'Plato worried rhetoric could:', opts: ['Help people', 'Make bad ideas sound good', 'Educate', 'Nothing'], ans: 1 },
        { q: 'Aristotle argued rhetoric is:', opts: ['Always bad', 'A necessary skill for finding the best means of persuasion', 'Only for elites', 'Same as logic'], ans: 1 },
        { q: '"I have a dream" is powerful because:', opts: ['Volume', 'Word choice, rhythm, imagery, and structure', 'Topic alone', 'It\'s short'], ans: 1 },
        { q: 'Persuasion vs manipulation:', opts: ['No difference', 'Persuasion respects the audience; manipulation bypasses judgment', 'Manipulation is louder', 'Persuasion fails'], ans: 1 },
        { q: 'Good rhetoric requires:', opts: ['Tricks', 'Something worth saying AND skill to say it well', 'A loud voice', 'Big words'], ans: 1 },
        { q: 'Rhetoric without truth is:', opts: ['Effective enough', 'Dangerous — can make lies beautiful', 'Impossible', 'Harmless'], ans: 1 },
        { q: 'Truth without rhetoric is:', opts: ['Enough', 'Often powerless — true things fail if communicated poorly', 'Better', 'Always sufficient'], ans: 1 },
        { q: 'The goal of studying rhetoric:', opts: ['Win arguments', 'Communicate honestly and recognize when others don\'t', 'Sound smart', 'Become a politician'], ans: 1 },
      ],
      growth: [
        { q: 'Plato\'s Gorgias: rhetoric without philosophy is like:', opts: ['Art without beauty', 'Cooking without medicine — gratifies but doesn\'t nourish', 'Music without rhythm', 'Nothing'], ans: 1 },
        { q: 'Aristotle\'s reply: rhetoric is:', opts: ['A weapon', 'A tool — moral value depends on the user and the truth of the message', 'Always good', 'Always bad'], ans: 1 },
        { q: 'Ethos, Pathos, Logos are:', opts: ['Three separate skills', 'Aristotle\'s three modes of persuasion — most arguments use all three', 'Modern concepts', 'Outdated'], ans: 1 },
        { q: 'Strong ethos but weak logos:', opts: ['Ideal', 'May persuade through trust but the argument crumbles under scrutiny', 'Impossible', 'Unethical'], ans: 1 },
        { q: 'Strong logos but no pathos:', opts: ['Ideal', 'Technically correct but fails to move — people don\'t act on logic alone', 'Always wins', 'Unethical'], ans: 1 },
        { q: 'Propaganda is rhetoric that:', opts: ['Is always obvious', 'Bypasses critical thinking rather than engaging it', 'Doesn\'t work', 'Is modern only'], ans: 1 },
        { q: 'The ethics of rhetoric depend on:', opts: ['Technique', 'Whether the speaker respects the audience as rational agents', 'Topic', 'Outcome only'], ans: 1 },
        { q: 'Douglass\'s power as a rhetor came from:', opts: ['Volume', 'Moral authority (ethos), logical argument (logos), and emotional power (pathos) together', 'Tricks', 'Education alone'], ans: 1 },
        { q: 'Studying rhetoric makes you:', opts: ['More manipulative', 'A better communicator AND a more critical audience', 'Nothing', 'A better speaker only'], ans: 1 },
        { q: 'Rhetoric in the trivium:', opts: ['Public speaking class', 'The completion: Grammar reads, Logic thinks, Rhetoric acts', 'Winning', 'Performance'], ans: 1 },
      ],
      canopy: [
        { q: 'Plato banned poets because:', opts: ['He disliked poetry', 'Beautiful language can make people feel strongly about falsehoods', 'Poetry was expensive', 'Political decision'], ans: 1 },
        { q: 'Aristotle counters: rhetoric is like medicine —', opts: ['Only heals', 'Can harm, but that doesn\'t make the knowledge bad', 'Only harms', 'Neither'], ans: 1 },
        { q: 'The Platonic worry today applies to:', opts: ['Nothing', 'Misinformation, propaganda, advertising — beautiful lies at scale', 'Ancient philosophy only', 'Politics only'], ans: 1 },
        { q: 'Quintilian: "a good man speaking well" implies:', opts: ['Only good people can speak', 'Highest rhetoric requires moral character — technique without virtue is dangerous', 'Morality is irrelevant', 'Speaking is everything'], ans: 1 },
        { q: 'Derashah (Jewish homiletics) combines:', opts: ['Nothing rhetorical', 'Textual analysis, logical argument, and persuasive communication — the trivium in action', 'Only religion', 'Only emotion'], ans: 1 },
        { q: 'Isocrates: rhetoric is:', opts: ['A game', 'Civic education — learning to speak well IS learning to think and act as a citizen', 'Unnecessary', 'Elitist'], ans: 1 },
        { q: 'Plato vs Aristotle on rhetoric mirrors:', opts: ['Nothing modern', 'The permanent tension between fearing persuasion\'s power and needing it for democracy', 'A settled debate', 'Ancient quarrel only'], ans: 1 },
        { q: 'In the social media age, rhetorical literacy is:', opts: ['Obsolete', 'More important than ever — everyone produces and consumes persuasion', 'Less important', 'Professional only'], ans: 1 },
        { q: 'The prophetic tradition uses rhetoric to:', opts: ['Entertain', 'Speak truth to power with moral vision and persuasive force', 'Manipulate', 'Be literary'], ans: 1 },
        { q: 'The deepest question of rhetoric:', opts: ['How to win', 'Can truth be communicated? What does that require — and what does it cost?', 'What techniques work', 'How to be famous'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Think of a time someone convinced you to do something. How did they do it? Was it logic, emotion, trust, or something else? Write 3-4 sentences.' },
      growth: { prompt: 'Find a speech, ad, or post that persuades effectively. Identify the balance of ethos, pathos, and logos. Which dominates? Would shifting the balance strengthen it? (150 words)' },
      canopy: { prompt: 'Is it possible to be both highly persuasive and completely honest? Or does all persuasion involve some manipulation? Write 250 words with at least one example.' },
    },
    encounter: {
      text: '"I have a dream that one day this nation will rise up and live out the true meaning of its creed: that all men are created equal. I have a dream that one day on the red hills of Georgia, the sons of former slaves and the sons of former slave owners will be able to sit down together at the table of brotherhood."',
      attribution: '— Martin Luther King Jr., "I Have a Dream" (1963)',
      questions: [
        { tier: 'seed', q: 'What makes this powerful? Point to specific words or phrases.' },
        { tier: 'growth', q: 'King uses repetition, vivid imagery, and allusion to the Declaration. How do these techniques create something more powerful than logical argument alone?' },
        { tier: 'canopy', q: 'King quotes a document written by slaveholders. Write 200 words on how he uses America\'s own rhetoric against its failures — holding a nation accountable to its own words.' },
      ]
    },
    bridge: 'Rhetoric begins with something true to say and knowing your audience. Unit 2: Ethos — the foundation of credibility.',
  },
  {
    id: 'r2', title: 'Ethos', subtitle: 'Character and credibility',
    anchorTexts: 'Atticus Finch, social media credibility, the prophetic voice',
    learn: 'Ethos is the persuasive power of character. We believe people we trust. Credibility comes from expertise, consistency, honesty, and demonstrated concern for the audience. You can build ethos over years and destroy it in seconds. In every argument, ask: why should the audience trust this speaker?',
    quiz: {
      seed: [
        { q: 'Ethos means:', opts: ['Emotion', 'Character and credibility', 'Logic', 'Volume'], ans: 1 },
        { q: 'You trust your doctor because of:', opts: ['Pathos', 'Ethos — expertise and training', 'Logos', 'Their office'], ans: 1 },
        { q: 'A celebrity selling vitamins has:', opts: ['Strong medical ethos', 'Fame but not relevant expertise', 'Perfect credibility', 'Authority'], ans: 1 },
        { q: 'Ethos can be destroyed by:', opts: ['Nothing', 'Lying, inconsistency, or self-serving behavior', 'Being quiet', 'One mistake'], ans: 1 },
        { q: 'Trust is built:', opts: ['Instantly', 'Slowly, through consistent honesty', 'By being loud', 'By agreeing always'], ans: 1 },
        { q: '"I\'m not a scientist, but..." signals:', opts: ['Strong ethos', 'The speaker acknowledges limited expertise', 'Nothing', 'False modesty'], ans: 1 },
        { q: 'An anonymous online commenter has:', opts: ['Strong ethos', 'Weak ethos — identity and motives unverifiable', 'No opinion', 'Credibility'], ans: 1 },
        { q: 'Best way to build ethos in writing:', opts: ['Big words', 'Show knowledge, acknowledge counterarguments, write honestly', 'Be aggressive', 'Quote famous people'], ans: 1 },
        { q: 'The same argument is more persuasive when:', opts: ['Longer', 'Delivered by someone the audience trusts', 'Repeated', 'Written'], ans: 1 },
        { q: 'Ethos matters because:', opts: ['People are irrational', 'Trust is the precondition for all other persuasion', 'Only experts speak', 'It doesn\'t'], ans: 1 },
      ],
      growth: [
        { q: 'Aristotle\'s three sources of ethos: practical wisdom, virtue, and:', opts: ['Wealth', 'Goodwill — the audience must believe you care about them', 'Fame', 'Education'], ans: 1 },
        { q: 'Atticus Finch\'s courtroom ethos comes from:', opts: ['His degree', 'Consistent character — his defense of justice matches his life', 'Eloquence', 'The judge'], ans: 1 },
        { q: '"I feel your pain" builds ethos through:', opts: ['Logos', 'Identification — claiming shared experience', 'Pathos only', 'Nothing'], ans: 1 },
        { q: 'This backfires when:', opts: ['Never', 'The audience doesn\'t believe the speaker shares their experience', 'Always', 'Too empathetic'], ans: 1 },
        { q: 'Acknowledging counterarguments builds ethos because:', opts: ['Shows weakness', 'Demonstrates intellectual honesty', 'Wastes space', 'Required'], ans: 1 },
        { q: 'Ad hominem attacks target:', opts: ['The argument', 'The person\'s ethos — destroying credibility instead of engaging ideas', 'Evidence', 'Conclusion'], ans: 1 },
        { q: 'Appeal to authority works when:', opts: ['Famous person', 'Authority has relevant expertise in the specific domain', 'Platform', 'Confidence'], ans: 1 },
        { q: 'Prophetic ethos (Isaiah, Amos) comes from:', opts: ['Education', 'Moral authority and willingness to speak truth at personal cost', 'Politics', 'Popularity'], ans: 1 },
        { q: 'In the Talmud, a student can challenge a sage. This means:', opts: ['Ethos doesn\'t matter', 'Logos can override ethos — the argument matters more than who makes it', 'Disrespect', 'Never happens'], ans: 1 },
        { q: 'Deepest form of ethos:', opts: ['Expertise', 'Integrity — words, actions, and character consistent over time', 'Fame', 'Intelligence'], ans: 1 },
      ],
      canopy: [
        { q: 'Aristotle says ethos is "the most effective means of persuasion" because:', opts: ['People are irrational', 'Trust is the precondition — without it, no argument lands', 'Logic fails', 'Emotion dominates'], ans: 1 },
        { q: 'King\'s ethos in "Letter from Birmingham Jail" rests on:', opts: ['His degree', 'Dual identity as minister AND civil rights leader — moral authority from both', 'Fame', 'Writing skill'], ans: 1 },
        { q: 'He addresses "Fellow Clergymen" to:', opts: ['Be polite', 'Establish shared ethos before diverging — you must respect me before dismissing me', 'Follow convention', 'Ensure publication'], ans: 1 },
        { q: 'Digital age ethos is fragmented because:', opts: ['Nothing changed', 'Anyone can project credibility online; verification is harder', 'Social media is honest', 'Only experts post'], ans: 1 },
        { q: 'This creates:', opts: ['Only opportunity', 'Both opportunity (marginalized voices gain platforms) and danger (bad actors gain credibility)', 'Only danger', 'Neither'], ans: 1 },
        { q: 'Quintilian\'s "good man speaking well" implies rhetoric requires:', opts: ['Only technique', 'Moral character — the inseparability of ethics and effective communication', 'Only goodness', 'Neither'], ans: 1 },
        { q: 'The tension between ethos and logos is:', opts: ['Resolved', 'Permanent — respect expertise AND demand good arguments', 'Ethos wins', 'Logos wins'], ans: 1 },
        { q: 'A leader who admits error builds ethos because:', opts: ['It doesn\'t', 'Honesty about failure demonstrates the character that warrants trust', 'It shows weakness', 'People like humility'], ans: 1 },
        { q: 'The ethical obligation regarding ethos:', opts: ['Build strongest possible', 'Never claim more credibility than you have — honest self-representation', 'Fake it', 'Ethos is automatic'], ans: 1 },
        { q: 'The deepest lesson:', opts: ['Credentials matter', 'You ARE your argument — character and words are inseparable', 'Image is everything', 'Only logic matters'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Think of someone you trust. List three specific things that make their words believable. These are elements of their ethos.' },
      growth: { prompt: 'Compare two sources arguing the same position (scientist vs blogger, or two politicians). Whose ethos is stronger and why? Be specific. (150 words)' },
      canopy: { prompt: 'How does ethos work differently in a courtroom, a pulpit, and on social media? What counts as credibility in each? Where might ethos-based persuasion become ethically problematic? (250 words)' },
    },
    encounter: {
      text: '"I submit that an individual who breaks a law that conscience tells him is unjust, and who willingly accepts the penalty of imprisonment in order to arouse the conscience of the community over its injustice, is in reality expressing the highest respect for law."',
      attribution: '— Martin Luther King Jr., "Letter from Birmingham Jail"',
      questions: [
        { tier: 'seed', q: 'King says breaking the law can actually show respect for law. How does this work?' },
        { tier: 'growth', q: 'King\'s ethos here rests on willingness to accept punishment. How does accepting consequences strengthen his moral authority compared to someone who breaks the law and evades consequences?' },
        { tier: 'canopy', q: 'King\'s argument depends on an ethos only available to those who suffer for their principles. Write 200 words on whether this kind of moral authority can be built any other way.' },
      ]
    },
    bridge: 'Ethos is who you are. Pathos is what your audience feels. Unit 3: the power and ethics of emotional appeal.',
  },
  {
    id: 'r3', title: 'Pathos', subtitle: 'Emotion as legitimate tool',
    anchorTexts: 'Nathan\'s parable to David, charity appeals, sentimentality vs genuine emotion',
    learn: 'Pathos is the persuasive power of emotion. Emotion isn\'t reason\'s enemy — it\'s what makes reasoning matter. Without feeling, we would never act on what we know. Nathan told David a story about a lamb to make him feel outrage at injustice he\'d rationalized away. That\'s pathos at its highest: feeling that opens the eyes.',
    quiz: {
      seed: [
        { q: 'Pathos means:', opts: ['Sadness', 'Persuasion through emotion', 'Sympathy', 'Weakness'], ans: 1 },
        { q: 'A charity ad showing a hungry child uses:', opts: ['Logos', 'Pathos — emotion to motivate action', 'Ethos', 'Nothing'], ans: 1 },
        { q: 'Emotions in an argument are:', opts: ['Always wrong', 'Legitimate when they help the audience care about truth', 'Always right', 'Irrelevant'], ans: 1 },
        { q: 'Fear-based arguments are:', opts: ['Always good', 'Sometimes legitimate (real dangers), sometimes manipulative (exaggerated threats)', 'Always bad', 'Logical'], ans: 1 },
        { q: 'A movie about injustice that makes you cry is using:', opts: ['Tricks', 'Pathos — and if the injustice is real, the emotion serves truth', 'Manipulation', 'Nothing'], ans: 1 },
        { q: 'Pathos without logos is:', opts: ['Powerful enough', 'Feeling without thinking', 'Better', 'Impossible'], ans: 1 },
        { q: 'Logos without pathos is:', opts: ['Ideal', 'Often ineffective — people need to care before they act', 'All we need', 'Sufficient'], ans: 1 },
        { q: '"Think of the children!" becomes manipulative when:', opts: ['Never', 'Used to shut down debate rather than illuminate real harm', 'Always', 'Involves kids'], ans: 1 },
        { q: 'Nathan told David a story about a lamb to create:', opts: ['Entertainment', 'Outrage at injustice — then revealed David was the unjust man', 'Confusion', 'Sadness'], ans: 1 },
        { q: 'The best rhetoric combines:', opts: ['Only pathos', 'Ethos, pathos, and logos together', 'Only logos', 'Only ethos'], ans: 1 },
      ],
      growth: [
        { q: 'Aristotle listed emotions a rhetor should understand:', opts: ['Only two', 'Anger, pity, fear, shame, and others — each has triggers and uses', 'None', 'Only happiness'], ans: 1 },
        { q: 'Anger is legitimate in rhetoric when:', opts: ['Never', 'Real injustice demands outrage, not complacency', 'Always', 'Politics only'], ans: 1 },
        { q: 'Sentimentality vs genuine emotion:', opts: ['Same thing', 'Sentimentality is cheap, unearned feeling; genuine emotion confronts reality', 'Sentimentality is stronger', 'Identical'], ans: 1 },
        { q: 'Using a tragic story to deflect from policy questions is:', opts: ['Effective', 'Pathos replacing logos — emotion as distraction', 'Honest', 'Appropriate'], ans: 1 },
        { q: 'Nathan\'s parable works because:', opts: ['David likes stories', 'It creates emotional engagement that bypasses self-justification', 'It\'s clever', 'God commanded it'], ans: 1 },
        { q: 'Using narrative to create moral insight is:', opts: ['Manipulation', 'Legitimate — it helps people see, not forces them', 'Unique to Bible', 'Outdated'], ans: 1 },
        { q: 'Music, imagery, rhythm create pathos through:', opts: ['Magic', 'Sensory experience — making abstract ideas feel real', 'Confusion', 'Nothing'], ans: 1 },
        { q: 'The ethical test for pathos:', opts: ['Does it work?', 'Does the emotion serve truth, or replace it?', 'Does it feel good?', 'Is it strong?'], ans: 1 },
        { q: 'Fear appeals work best when:', opts: ['Maximally scary', 'The threat is real AND the audience is given a way to act', 'Vague', 'Repeated'], ans: 1 },
        { q: 'Strongest pathos opens eyes like:', opts: ['A blow', 'Nathan\'s parable — reveals what the audience couldn\'t or wouldn\'t see', 'Entertainment', 'A trick'], ans: 1 },
      ],
      canopy: [
        { q: 'Aristotle treats emotions as:', opts: ['Irrational', 'A form of cognition — judgments about what matters', 'Irrelevant to rhetoric', 'Purely physical'], ans: 1 },
        { q: 'When King makes an audience feel anger at injustice:', opts: ['Manipulation', 'He helps them correctly perceive reality — the anger is a right response', 'Distraction', 'Irrationality'], ans: 1 },
        { q: 'Neuroscience: patients with damaged emotional centers:', opts: ['Think more clearly', 'Cannot make good decisions — emotion is necessary for reasoning', 'Are more logical', 'Are unchanged'], ans: 1 },
        { q: 'The prophetic tradition uses vivid imagery of suffering to:', opts: ['Scare', 'Create moral urgency — making the audience FEEL injustice they\'ve normalized', 'Entertain', 'Be poetic'], ans: 1 },
        { q: 'Nathan\'s parable uses all three: ethos (prophet), pathos (lamb), logos (logical trap). The genius is:', opts: ['The story', 'The integration — emotion opens the door that logic walks through', 'The surprise', 'Divine authority'], ans: 1 },
        { q: 'Algorithms optimize for engagement, which means:', opts: ['Better content', 'Emotional manipulation at scale — outrage and fear spread fastest', 'More truth', 'Nothing bad'], ans: 1 },
        { q: 'Compassion fatigue happens when:', opts: ['People are selfish', 'Constant emotional appeals desensitize — pathos loses force through overuse', 'Emotions are weak', 'Never'], ans: 1 },
        { q: 'The difference between propaganda and art:', opts: ['None', 'Both use emotion, but art respects the audience\'s freedom to interpret', 'Art never persuades', 'Propaganda is honest'], ans: 1 },
        { q: 'Pathos at its most ethical:', opts: ['Makes people feel good', 'Creates the emotional conditions for clear moral perception', 'Avoids emotion', 'Is never used'], ans: 1 },
        { q: 'The deepest lesson:', opts: ['Emotion is dangerous', 'Emotion and reason need each other — pathos without logos manipulates; logos without pathos is impotent', 'Use more emotion', 'Avoid pathos'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Write a short paragraph (3-4 sentences) about something you care about. First write it using only facts (logos). Then rewrite it to make the reader FEEL something (pathos). Which is more effective? Why?' },
      growth: { prompt: 'Find a charity appeal (website, commercial, letter). How does it use emotion? Is the emotion earned (based on real need) or manufactured (manipulative)? What\'s the difference? (150 words)' },
      canopy: { prompt: 'Read the story of Nathan and David (2 Samuel 12:1-7). Nathan uses a fictional story to create real moral insight. Is this manipulation or revelation? Write 250 words on the ethics of using emotion to create moral clarity.' },
    },
    encounter: {
      text: '"There was a rich man who had many flocks and herds. And there was a poor man who had nothing except one little ewe lamb. He raised it, and it grew up with him and his children. It ate of his food, drank from his cup, and lay in his arms. It was like a daughter to him. A traveler came to the rich man, and instead of taking from his own flock, he took the poor man\'s lamb."',
      attribution: '— 2 Samuel 12:1-4 (Nathan\'s Parable, adapted)',
      questions: [
        { tier: 'seed', q: 'How does this story make you feel? What emotion does it create?' },
        { tier: 'growth', q: 'Nathan told this story to King David, who had stolen another man\'s wife. David was outraged at the rich man — then Nathan said "You are the man." Why does the indirect approach (a story) work better than a direct accusation?' },
        { tier: 'canopy', q: 'Nathan\'s parable is arguably the most effective piece of rhetoric in the Hebrew Bible. Write 200 words analyzing WHY: how does it use ethos, pathos, and logos together? Why does narrative succeed where direct argument might have failed?' },
      ]
    },
    bridge: 'Pathos makes the audience feel. Logos makes them think. Unit 4: the structure of logical appeal.',
  },
  {
    id: 'r4', title: 'Logos in Action', subtitle: 'Making arguments move',
    anchorTexts: 'Lincoln-Douglas debates, courtroom closing arguments, op-eds',
    learn: 'Logos in rhetoric isn\'t abstract logic — it\'s logic made persuasive. An argument that\'s technically valid but poorly communicated fails. A beautifully structured speech that leads the audience step by step from shared premises to a surprising but inevitable conclusion — that\'s logos at work. Structure matters: claim, evidence, reasoning, and the art of making the audience feel they discovered the conclusion themselves.',
    quiz: {
      seed: [
        { q: 'Logos in rhetoric means:', opts: ['Using big words', 'Logical argument and evidence — reasoning that persuades', 'Quoting experts', 'Statistics only'], ans: 1 },
        { q: 'The best persuasive arguments make the audience feel:', opts: ['Confused', 'Like they discovered the conclusion themselves', 'Stupid', 'Forced'], ans: 1 },
        { q: 'A claim without evidence is:', opts: ['Persuasive', 'An assertion — it asks to be believed without reason', 'A fact', 'Strong'], ans: 1 },
        { q: 'Evidence without a clear claim is:', opts: ['Persuasive', 'Data without direction — the audience doesn\'t know what to conclude', 'Scientific', 'Complete'], ans: 1 },
        { q: 'The structure of most persuasive arguments is:', opts: ['Random', 'Claim → evidence → reasoning → conclusion', 'Conclusion first', 'No structure'], ans: 1 },
        { q: '"Three reasons why..." is effective because:', opts: ['Three is magic', 'Clear structure helps the audience follow and remember', 'Sounds smart', 'Tradition'], ans: 1 },
        { q: 'Addressing a counterargument in your speech:', opts: ['Shows weakness', 'Strengthens your position by showing you\'ve considered alternatives', 'Wastes time', 'Confuses people'], ans: 1 },
        { q: 'An example or story can serve as evidence when:', opts: ['Never', 'It illustrates a broader pattern or principle', 'Always', 'It\'s dramatic'], ans: 1 },
        { q: 'Logical structure in a speech means:', opts: ['Being boring', 'Organizing ideas so each builds on the last toward a clear conclusion', 'Using formulas', 'Avoiding emotion'], ans: 1 },
        { q: 'The best logos makes complex things:', opts: ['More complex', 'Clear without being simplistic', 'Simple always', 'Longer'], ans: 1 },
      ],
      growth: [
        { q: 'Lincoln-Douglas debates worked because both speakers:', opts: ['Were friends', 'Presented structured arguments that built step by step, allowing the audience to follow the reasoning', 'Yelled', 'Agreed'], ans: 1 },
        { q: 'A courtroom closing argument uses logos by:', opts: ['Ignoring evidence', 'Weaving the evidence into a narrative that leads inevitably to the verdict', 'Reading the law', 'Being emotional only'], ans: 1 },
        { q: 'An op-ed persuades through logos when it:', opts: ['States opinions', 'Presents a clear thesis supported by evidence, reasoning, and engagement with objections', 'Uses big words', 'Is long'], ans: 1 },
        { q: 'The "rule of three" works because:', opts: ['Random', 'Two points feel incomplete; four feel excessive; three creates a satisfying pattern', 'Schools teach it', 'Nothing special'], ans: 1 },
        { q: 'Concession-and-rebuttal ("Some might argue X, but...") strengthens logos by:', opts: ['Wasting time', 'Showing intellectual honesty and eliminating the audience\'s objections before they arise', 'Being polite', 'Weakening your argument'], ans: 1 },
        { q: 'Inductive structure (examples → conclusion) feels:', opts: ['Confusing', 'Like discovery — the audience arrives at the conclusion themselves', 'Random', 'Weak'], ans: 1 },
        { q: 'Deductive structure (principle → application) feels:', opts: ['Confusing', 'Authoritative — the conclusion follows inevitably from accepted premises', 'Random', 'Weak'], ans: 1 },
        { q: 'Choosing between inductive and deductive depends on:', opts: ['Nothing', 'Your audience — do they need to discover the truth or be reminded of principles they accept?', 'Your preference', 'The topic only'], ans: 1 },
        { q: 'Statistics are powerful evidence but dangerous when:', opts: ['Never', 'Presented without context — numbers can mislead as easily as words', 'Always', 'They\'re large'], ans: 1 },
        { q: 'Logos at its best:', opts: ['Eliminates emotion', 'Makes the audience think clearly AND feel the force of the reasoning', 'Is purely technical', 'Avoids examples'], ans: 1 },
      ],
      canopy: [
        { q: 'Lincoln at Cooper Union builds his argument from:', opts: ['Emotion', 'Historical evidence (what the founders actually believed) toward a political conclusion — logos as forensic reconstruction', 'Personal story', 'Appeals to authority'], ans: 1 },
        { q: 'This works rhetorically because:', opts: ['History is boring', 'Lincoln forces his opponents to argue against their own heroes — the evidence constrains the conclusion', 'He\'s famous', 'He yells'], ans: 1 },
        { q: 'Classical arrangement (exordium, narratio, confirmatio, refutatio, peroratio) structures speeches to:', opts: ['Be formulaic', 'Move the audience through a psychological journey: attention → context → proof → counterarguments → action', 'Be long', 'Follow tradition'], ans: 1 },
        { q: 'Enthymeme (a syllogism with a missing premise) is powerful because:', opts: ['It hides logic', 'The audience fills in the missing premise themselves, creating participation and buy-in', 'It\'s lazy', 'Nothing special'], ans: 1 },
        { q: 'Example: "He\'s a citizen, so he can vote." Missing premise:', opts: ['He\'s old enough', 'Citizens can vote — the audience supplies this, making them participants in the reasoning', 'He wants to', 'Nothing missing'], ans: 1 },
        { q: 'Talmudic argumentation uses logos distinctively by:', opts: ['Being dry', 'Preserving the reasoning process — showing HOW conclusions are reached, not just what they are', 'Avoiding evidence', 'Being circular'], ans: 1 },
        { q: 'This models a different relationship with logos:', opts: ['Worse', 'Logos as ongoing inquiry rather than settled proof — reasoning as a practice, not just a product', 'Same as Western', 'Better'], ans: 1 },
        { q: 'The strongest logos adapts to its audience by:', opts: ['Dumbing down', 'Starting from premises the audience already accepts and building toward new conclusions', 'Ignoring them', 'Being abstract'], ans: 1 },
        { q: 'When logos and pathos work together:', opts: ['They conflict', 'The argument becomes both intellectually compelling AND emotionally resonant — the most powerful form of rhetoric', 'Pathos dominates', 'Logos dominates'], ans: 1 },
        { q: 'Mastering rhetorical logos means:', opts: ['Memorizing structures', 'Learning to make truth visible, clear, and compelling to a specific audience at a specific moment', 'Being technical', 'Avoiding emotion'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Pick something you want to convince your friends or family of (a movie to watch, a place to eat, an idea). Write your argument with: a clear claim, at least two reasons, and a conclusion. Does it convince YOU?' },
      growth: { prompt: 'Take a claim you believe and write it two ways: once building from examples to conclusion (inductive), once from a principle down to application (deductive). Which feels more natural? More convincing? Why? (200 words)' },
      canopy: { prompt: 'Read Lincoln\'s Cooper Union Address (or an excerpt). Analyze how Lincoln uses historical evidence as logos. How does he make the evidence feel inevitable rather than cherry-picked? Write 250 words on Lincoln\'s rhetorical strategy.' },
    },
    encounter: {
      text: '"It is rather for us to be here dedicated to the great task remaining before us — that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion — that we here highly resolve that these dead shall not have died in vain — that this nation, under God, shall have a new birth of freedom."',
      attribution: '— Abraham Lincoln, Gettysburg Address (conclusion)',
      questions: [
        { tier: 'seed', q: 'What is Lincoln asking the audience to do? Where is the call to action?' },
        { tier: 'growth', q: 'Lincoln\'s logos: he moves from the dead → our duty → national purpose. Trace the logical chain: how does honoring the dead lead to "a new birth of freedom"?' },
        { tier: 'canopy', q: 'Lincoln makes an argument about the future using the authority of the dead. Is this logos (logical reasoning about obligation) or pathos (emotional weight of sacrifice) or both? Write 200 words analyzing how Lincoln fuses logical and emotional appeal.' },
      ]
    },
    bridge: 'Logos structures the argument. But WHEN you speak, and to WHOM, and in what CONTEXT — that\'s kairos. Unit 5.',
  },
  {
    id: 'r5', title: 'Kairos', subtitle: 'The right words at the right time',
    anchorTexts: 'Churchill\'s "We shall fight on the beaches," Ecclesiastes 3, comedy timing',
    learn: 'Kairos is the ancient concept of the right moment — saying the right thing at the right time to the right audience. The same speech can triumph or fail depending on when it\'s given. Churchill\'s wartime rhetoric would be absurd at a dinner party. A joke depends entirely on timing. Kairos is the rhetorical sense of occasion, audience, and moment.',
    quiz: {
      seed: [
        { q: 'Kairos means:', opts: ['Speaking loudly', 'The right words at the right time — rhetorical timing', 'Chronological time', 'Speed'], ans: 1 },
        { q: 'The same words can succeed or fail depending on:', opts: ['Nothing', 'When, where, and to whom they\'re spoken', 'Volume', 'Length'], ans: 1 },
        { q: 'A joke that falls flat usually has bad:', opts: ['Content', 'Timing — the right joke at the wrong moment fails', 'Vocabulary', 'Grammar'], ans: 1 },
        { q: 'Churchill\'s wartime speeches worked because:', opts: ['He was loud', 'They matched the desperate moment — the words fit the crisis', 'They were long', 'He was famous'], ans: 1 },
        { q: 'Giving a lighthearted speech at a funeral would fail because:', opts: ['Funerals are quiet', 'The tone doesn\'t match the occasion — bad kairos', 'Speeches aren\'t allowed', 'It\'s illegal'], ans: 1 },
        { q: 'Knowing your audience matters because:', opts: ['It doesn\'t', 'Different audiences need different approaches — what persuades one group may alienate another', 'Everyone is the same', 'Politeness'], ans: 1 },
        { q: 'A politician who addresses a disaster with statistics instead of empathy has failed:', opts: ['Logically', 'In kairos — the moment demands feeling, not data', 'Completely', 'Ethically'], ans: 1 },
        { q: 'Ecclesiastes: "A time to keep silence, and a time to speak." This is about:', opts: ['Scheduling', 'Kairos — wisdom about when words are needed and when silence is', 'Being quiet', 'Nothing'], ans: 1 },
        { q: 'Kairos requires:', opts: ['A script', 'Awareness — reading the room, the moment, the audience', 'Rules', 'Practice only'], ans: 1 },
        { q: 'You can have perfect ethos, pathos, and logos and still fail if:', opts: ['You\'re unlucky', 'The timing and context are wrong — kairos is missing', 'Impossible', 'The audience is wrong'], ans: 1 },
      ],
      growth: [
        { q: 'Churchill: "We shall fight on the beaches" worked in June 1940 because:', opts: ['Nice words', 'Britain had just evacuated Dunkirk — the nation needed defiance, not comfort', 'He was PM', 'Radio was new'], ans: 1 },
        { q: 'The same speech in peacetime would sound:', opts: ['Powerful', 'Absurd — the urgency would feel manufactured without a real crisis', 'Even better', 'The same'], ans: 1 },
        { q: 'Kairos in social media means:', opts: ['Posting often', 'Understanding what resonates NOW — trends, mood, cultural moment', 'Following trends', 'Nothing'], ans: 1 },
        { q: 'A brand that posts a lighthearted ad during a tragedy fails at:', opts: ['Marketing', 'Kairos — the message doesn\'t fit the moment', 'Design', 'Everything'], ans: 1 },
        { q: 'King chose Birmingham for his campaign because:', opts: ['It was convenient', 'Birmingham was the most segregated city — the kairos (political moment and location) maximized impact', 'Random', 'It was safe'], ans: 1 },
        { q: 'Comedians "read the room" — this is:', opts: ['Talent only', 'Kairos in action — adjusting content, tone, and timing to the audience\'s state', 'Irrelevant to rhetoric', 'Basic skill'], ans: 1 },
        { q: 'Knowing when NOT to speak is:', opts: ['Cowardice', 'Advanced kairos — silence can be more powerful than words', 'Failure', 'Always wrong'], ans: 1 },
        { q: 'Writing for a specific publication requires:', opts: ['Nothing special', 'Understanding the publication\'s audience, conventions, and current concerns — kairos of context', 'The same style always', 'Only good writing'], ans: 1 },
        { q: 'Kairos is the most difficult element of rhetoric because:', opts: ['It\'s vague', 'It can\'t be taught as rules — it requires judgment, awareness, and experience', 'It\'s unimportant', 'It\'s simple'], ans: 1 },
        { q: 'The deepest lesson of kairos:', opts: ['Be trendy', 'Rhetoric is situational — the best communication is shaped by its moment, not just its content', 'Timing is everything', 'Always wait'], ans: 1 },
      ],
      canopy: [
        { q: 'The Greek concept of kairos vs chronos:', opts: ['Same thing', 'Chronos is clock time; kairos is the pregnant moment — qualitative, not quantitative', 'Chronos is better', 'Both are clocks'], ans: 1 },
        { q: 'In Jewish thought, the concept of "et ratzon" (an auspicious time) parallels kairos by:', opts: ['Coincidence', 'Recognizing that certain moments are uniquely receptive to certain messages or actions', 'No parallel', 'Being religious only'], ans: 1 },
        { q: 'Churchill was a mediocre peacetime politician but extraordinary in war because:', opts: ['He changed', 'His rhetorical strengths (defiance, grandeur, moral clarity) matched wartime kairos perfectly', 'War is easier', 'He was lucky'], ans: 1 },
        { q: 'This teaches us that rhetorical effectiveness is:', opts: ['Fixed', 'Partly a function of fit between the speaker and the moment — the same person can be powerful or irrelevant', 'About skill only', 'Random'], ans: 1 },
        { q: 'The internet disrupts kairos because:', opts: ['It doesn\'t', 'Context collapses — a message intended for one audience at one moment is seen by everyone at all times', 'Information flows better', 'Nothing changes'], ans: 1 },
        { q: 'Context collapse means:', opts: ['Nothing', 'A joke among friends can become a scandal when seen by millions — kairos is destroyed by decontextualization', 'Context doesn\'t matter', 'Everything collapses'], ans: 1 },
        { q: 'A speech that is "timeless" seems to transcend kairos. But it actually:', opts: ['Ignores kairos', 'Captures something SO true about its specific moment that it resonates beyond it — the deepest kairos produces universality', 'Is generic', 'Is luck'], ans: 1 },
        { q: 'Kairos connects to the Talmudic "da lifnei mi atah omed" (know before whom you stand) because:', opts: ['No connection', 'Both demand total awareness of context — who you are, who your audience is, what the moment requires', 'It\'s religious only', 'Only about God'], ans: 1 },
        { q: 'Teaching kairos is paradoxical because:', opts: ['It can\'t be taught', 'It requires rules AND the judgment to know when to break them — phronesis, not technique', 'It\'s easy', 'Only experience teaches'], ans: 1 },
        { q: 'The master of kairos is someone who:', opts: ['Follows trends', 'Has internalized all the tools of rhetoric AND can read the moment well enough to deploy them wisely', 'Speaks first', 'Waits forever'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Think of a time you said the right thing at the right moment — or the wrong thing at the wrong moment. What happened? What made the timing matter? Write 3-4 sentences.' },
      growth: { prompt: 'Find a famous speech and research when and where it was delivered. How did the specific occasion shape the speech? Would the same words work at a different time? Write 150 words analyzing the kairos.' },
      canopy: { prompt: 'Ecclesiastes 3 says there\'s "a time for every purpose under heaven." Write 250 words on what it means to develop kairotic sense — the ability to know what the moment requires. Is this a skill that can be taught, or only developed through experience?' },
    },
    encounter: {
      text: '"We shall fight on the beaches, we shall fight on the landing grounds, we shall fight in the fields and in the streets, we shall fight in the hills; we shall never surrender."',
      attribution: '— Winston Churchill, June 4, 1940',
      questions: [
        { tier: 'seed', q: 'Why is this powerful? What would happen if someone said this today, outside of wartime?' },
        { tier: 'growth', q: 'Churchill delivered this after the evacuation of Dunkirk — a military disaster. He turned retreat into defiance. How does the kairos (the desperate moment) make this rhetoric work?' },
        { tier: 'canopy', q: 'Churchill\'s wartime speeches are considered among the greatest in English. But in peacetime, he was often a poor communicator. Write 200 words on what this tells us about kairos — can a rhetor be great in one moment and mediocre in another? What does that mean for rhetoric as a skill vs rhetoric as a situational art?' },
      ]
    },
    bridge: 'Kairos is about the right moment. But HOW you arrange your argument within that moment matters too. Unit 6: classical arrangement and structure.',
  },
,
  {
    id: 'r6', title: 'Arrangement', subtitle: 'How structure shapes persuasion',
    anchorTexts: 'Classical oration, five-paragraph essay vs real structure, chiasm in Scripture',
    learn: 'Arrangement is the architecture of a speech or essay. The classical model (introduction, narration, proof, refutation, conclusion) isn\'t a formula — it\'s a map of the audience\'s psychological journey. A strong opening hooks attention. The middle builds the case. The ending drives to action. But the best rhetoric breaks expected structures when the moment demands it.',
    quiz: {
      seed: [
        { q: 'Arrangement in rhetoric means:', opts: ['Alphabetizing', 'How you organize and order your argument', 'Decorating', 'Grammar'], ans: 1 },
        { q: 'A strong opening should:', opts: ['Summarize everything', 'Hook the audience\'s attention and establish why they should care', 'Be long', 'Start with "I think"'], ans: 1 },
        { q: 'Putting your strongest point last creates:', opts: ['Boredom', 'Climax — building toward the most powerful moment', 'Confusion', 'Nothing'], ans: 1 },
        { q: 'Putting your strongest point first creates:', opts: ['Anti-climax', 'Immediate impact — leading with your best', 'Weakness', 'Error'], ans: 1 },
        { q: 'Addressing counterarguments BEFORE your main case:', opts: ['Wastes time', 'Clears objections so your argument lands on prepared ground', 'Shows weakness', 'Confuses'], ans: 1 },
        { q: 'The five-paragraph essay (intro, 3 body, conclusion) is:', opts: ['Perfect', 'A training tool — useful for beginners but limiting for real rhetoric', 'The only structure', 'Always bad'], ans: 1 },
        { q: 'A speech without clear structure feels:', opts: ['Creative', 'Confusing — the audience can\'t follow the thread', 'Professional', 'Advanced'], ans: 1 },
        { q: 'Ending with a call to action means:', opts: ['Begging', 'Telling the audience what to DO with what they\'ve heard', 'Being pushy', 'Summarizing'], ans: 1 },
        { q: 'Transitions between sections:', opts: ['Are optional', 'Guide the audience through the argument\'s logic', 'Waste time', 'Are filler'], ans: 1 },
        { q: 'Good arrangement makes the audience feel:', opts: ['Lost', 'Carried — each part leads naturally to the next', 'Bored', 'Confused'], ans: 1 },
      ],
      growth: [
        { q: 'Classical oration: exordium → narratio → confirmatio → refutatio → peroratio. This moves the audience through:', opts: ['Boredom', 'Attention → context → proof → counterarguments → emotion and action', 'Random order', 'Confusion'], ans: 1 },
        { q: 'Starting in medias res (in the middle of action) works because:', opts: ['It\'s lazy', 'It hooks attention immediately — the audience wants to know how we got here', 'Convention', 'Nothing'], ans: 1 },
        { q: 'Problem-Solution structure is effective for:', opts: ['All topics', 'Policy arguments — first make the audience feel the problem, then offer relief', 'Stories only', 'Nothing'], ans: 1 },
        { q: 'Comparison structure works when:', opts: ['Always', 'You need to show why one option is better — placing them side by side', 'Only essays', 'Never'], ans: 1 },
        { q: 'Chronological structure is strongest for:', opts: ['Arguments', 'Narratives — when the order of events matters for understanding', 'Everything', 'Nothing'], ans: 1 },
        { q: 'A speech that circles back to its opening image at the end uses:', opts: ['Repetition', 'Ring composition — creating closure and resonance', 'Lazy writing', 'Nothing special'], ans: 1 },
        { q: 'The five-paragraph essay limits real rhetoric because:', opts: ['It doesn\'t', 'Real arguments don\'t always have exactly three equal points — structure should serve content, not constrain it', 'It\'s too short', 'It\'s too long'], ans: 1 },
        { q: 'King\'s "I Have a Dream" builds from:', opts: ['Dream → reality', 'Reality (the "check that bounced") → vision (the dream) → action — moving from what IS to what could BE', 'No structure', 'Random order'], ans: 1 },
        { q: 'This structure works because:', opts: ['It\'s traditional', 'The audience must feel the injustice before they can embrace the vision', 'King was talented', 'It\'s the only option'], ans: 1 },
        { q: 'Mastering arrangement means:', opts: ['Following formulas', 'Choosing the structure that best serves your specific argument for your specific audience', 'Memorizing templates', 'Being creative only'], ans: 1 },
      ],
      canopy: [
        { q: 'Biblical chiasm (ABCB\'A\') differs from linear structure by:', opts: ['Being random', 'Creating meaning through symmetry — the center reveals the thematic core', 'Being circular', 'Nothing'], ans: 1 },
        { q: 'This implies that in chiastic texts:', opts: ['The beginning matters most', 'The center of the structure is the interpretive key', 'The end matters most', 'Structure is irrelevant'], ans: 1 },
        { q: 'Classical arrangement assumes the audience is:', opts: ['Hostile', 'Moving through a psychological journey — and the speaker must guide them through it', 'Passive', 'Already convinced'], ans: 1 },
        { q: 'Talmudic sugya structure (statement → challenge → resolution → new challenge) differs from Western argument because:', opts: ['It\'s random', 'It preserves the process of inquiry rather than presenting only conclusions', 'It\'s less organized', 'No difference'], ans: 1 },
        { q: 'This structural difference embodies different values:', opts: ['Nothing philosophical', 'Western rhetoric values conclusion; Talmudic rhetoric values ongoing inquiry — form reflects epistemology', 'One is better', 'They\'re identical'], ans: 1 },
        { q: 'Digital media changes arrangement because:', opts: ['Nothing changes', 'Audiences scan rather than read linearly — the "inverted pyramid" and front-loaded key info become more important', 'Structure doesn\'t matter online', 'Everything is short'], ans: 1 },
        { q: 'When structure itself becomes the message (e.g., a speech that deliberately disorients to mirror its theme):', opts: ['It\'s bad writing', 'Form becomes content — the arrangement enacts the meaning', 'It\'s confusing', 'Only geniuses can do this'], ans: 1 },
        { q: 'Morrison\'s Beloved uses fragmented, non-linear structure to:', opts: ['Be difficult', 'Mirror the fragmented experience of trauma — arrangement as rhetorical act', 'Confuse readers', 'Follow fashion'], ans: 1 },
        { q: 'The relationship between Grammar (structure) and Rhetoric (arrangement):', opts: ['Unrelated', 'Grammar analyzes structure in others\' texts; Rhetoric teaches you to create effective structure in your own', 'Same thing', 'Grammar is better'], ans: 1 },
        { q: 'The deepest lesson of arrangement:', opts: ['Follow formulas', 'Structure is never neutral — how you organize ideas shapes how the audience receives them', 'Be creative', 'Structure doesn\'t matter'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Take any argument (your own or from this course) and arrange it two different ways: strongest point first vs strongest point last. Which feels more persuasive? Write a note explaining why.' },
      growth: { prompt: 'Outline a persuasive speech (real or hypothetical) using classical arrangement: Opening (hook), Context (background), Proof (your case), Counterargument (and response), Conclusion (call to action). Then write a paragraph on what each section accomplishes.' },
      canopy: { prompt: 'Compare two structural logics: the Western linear essay (thesis → support → conclusion) and the Talmudic sugya (statement → challenge → response → further challenge). What does each structure assume about how truth is reached? Which fits your own thinking? (250 words)' },
    },
    encounter: {
      text: '"We hold these truths... That to secure these rights, Governments are instituted... That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it... [list of grievances]... We, therefore... solemnly publish and declare, That these United Colonies are, and of Right ought to be Free and Independent States."',
      attribution: '— Declaration of Independence (structural outline)',
      questions: [
        { tier: 'seed', q: 'The Declaration follows a clear structure: principles → rights → grievances → declaration. Why this order?' },
        { tier: 'growth', q: 'Jefferson builds from universal principles to specific complaints to a dramatic conclusion. Each section earns the next. How does this arrangement make the conclusion feel inevitable rather than revolutionary?' },
        { tier: 'canopy', q: 'The Declaration is simultaneously a philosophical argument, a legal brief, and a political act. Write 200 words on how its arrangement serves all three purposes at once. Which structural choice is the most rhetorically brilliant?' },
      ]
    },
    bridge: 'Arrangement is the skeleton. But what gives prose its life? Unit 7: Style — the figures and flourishes that make language memorable.',
  },
  {
    id: 'r7', title: 'Style and the Figures', subtitle: 'Making language unforgettable',
    anchorTexts: 'Anaphora in King, antithesis in Dickens, chiasmus in JFK',
    learn: 'The rhetorical figures — metaphor, anaphora, antithesis, chiasmus, tricolon — aren\'t decorations. They\'re cognitive tools. "Ask not what your country can do for you — ask what you can do for your country" doesn\'t just sound good. The chiasmus (ABBA structure) makes you think differently by flipping the frame. Figures are technology for thought.',
    quiz: {
      seed: [
        { q: 'A metaphor is:', opts: ['A lie', 'Describing something as something else to reveal meaning ("Life is a journey")', 'A simile', 'Literal language'], ans: 1 },
        { q: 'Anaphora (repeating the same words at the start of sentences) creates:', opts: ['Boredom', 'Rhythm and emphasis — building power through repetition', 'Errors', 'Confusion'], ans: 1 },
        { q: '"It was the best of times, it was the worst of times." This uses:', opts: ['Metaphor', 'Antithesis — placing opposites side by side', 'Simile', 'Nothing special'], ans: 1 },
        { q: '"Ask not what your country can do for you — ask what you can do for your country." This uses:', opts: ['Repetition', 'Chiasmus — flipping the order (ABBA) to create new meaning', 'Antithesis only', 'Nothing special'], ans: 1 },
        { q: 'A tricolon is:', opts: ['Three columns', 'Three parallel phrases ("Life, liberty, and the pursuit of happiness")', 'A disease', 'A punctuation mark'], ans: 1 },
        { q: 'Figures of speech are:', opts: ['Just decoration', 'Tools that shape how the audience thinks and feels', 'Outdated', 'Only for poetry'], ans: 1 },
        { q: '"I have a dream..." repeated is:', opts: ['Lazy', 'Anaphora — each repetition builds emotional force', 'An error', 'Filler'], ans: 1 },
        { q: '"One small step for man, one giant leap for mankind." This works because:', opts: ['It\'s short', 'The contrast (small/giant, step/leap, man/mankind) creates a vivid sense of scale', 'Armstrong practiced', 'Nothing'], ans: 1 },
        { q: 'Alliteration (repeated initial sounds) creates:', opts: ['Nothing', 'Rhythm and memorability ("Peter Piper picked...")', 'Confusion', 'Errors'], ans: 1 },
        { q: 'The figures make language memorable because:', opts: ['They\'re fancy', 'Pattern, contrast, and surprise are how the brain encodes information', 'Tradition', 'Nothing real'], ans: 1 },
      ],
      growth: [
        { q: 'JFK\'s chiasmus works because:', opts: ['It sounds nice', 'Flipping the structure forces the audience to rethink their assumption — the reversal IS the argument', 'He was charismatic', 'It\'s short'], ans: 1 },
        { q: 'King uses anaphora because:', opts: ['He ran out of ideas', 'Repetition creates incantatory power — each "I have a dream" adds emotional weight and the audience leans in', 'It\'s required in speeches', 'Tradition'], ans: 1 },
        { q: 'Antithesis ("Not this, but that") is powerful because:', opts: ['Contrast is dramatic', 'By defining what something ISN\'T, you sharpen what it IS', 'It\'s simple', 'Nothing'], ans: 1 },
        { q: 'Hyperbole (deliberate exaggeration) is:', opts: ['Lying', 'A figure that emphasizes through overstatement — "I\'ve told you a million times"', 'Always wrong', 'Literal'], ans: 1 },
        { q: 'Litotes (understatement through negation) — "not bad" meaning good — works by:', opts: ['Being vague', 'Creating ironic emphasis — the restraint makes the point more forcefully', 'Being unclear', 'Nothing'], ans: 1 },
        { q: 'Rhetorical questions ("Shall we surrender?") work because:', opts: ['They want answers', 'The audience mentally answers, making them participants in the argument', 'They\'re polite', 'Nothing'], ans: 1 },
        { q: 'Asyndeton (dropping conjunctions: "I came, I saw, I conquered") creates:', opts: ['Errors', 'Speed, power, decisiveness', 'Confusion', 'Nothing'], ans: 1 },
        { q: 'Polysyndeton (adding conjunctions: "and...and...and") creates:', opts: ['Errors', 'Accumulation, overwhelming abundance, relentlessness', 'Boredom', 'Nothing'], ans: 1 },
        { q: 'Parallel structure ("government of the people, by the people, for the people") creates:', opts: ['Repetition', 'Rhythm, emphasis, and a sense of completeness — the parallel form implies parallel importance', 'Filler', 'Nothing'], ans: 1 },
        { q: 'The figures are "cognitive tools" because:', opts: ['They help you think', 'Each figure creates a specific mental operation — reversal, comparison, accumulation — that shapes understanding', 'They\'re intellectual', 'They\'re difficult'], ans: 1 },
      ],
      canopy: [
        { q: 'The classical figures were not considered ornamental but:', opts: ['Expensive', 'Structural — each figure was a way of thinking, a cognitive operation made visible in language', 'Religious', 'Unnecessary'], ans: 1 },
        { q: 'Metaphor isn\'t just comparison — Lakoff argues it structures thought itself:', opts: ['Exaggeration', '"Time IS money" isn\'t just a saying — it shapes how we think about, spend, save, and waste time', 'Academic theory', 'Metaphors are optional'], ans: 1 },
        { q: 'Biblical Hebrew poetry uses parallelism as its primary device, not rhyme. This means:', opts: ['It\'s less poetic', 'The meaning IS the structure — the relationship between parallel lines creates the poem\'s thought', 'It\'s primitive', 'Nothing special'], ans: 1 },
        { q: 'Hebrew parallelism types: synonymous (A = A\'), antithetic (A vs A\'), synthetic (A + A\'). These mirror:', opts: ['Grammar structures', 'Logical operations — equivalence, contrast, and expansion — the figures enact thinking', 'Nothing', 'Only style'], ans: 1 },
        { q: 'In Psalm 19: "The heavens declare the glory of God; the firmament shows His handiwork." This parallelism:', opts: ['Is redundant', 'Uses near-synonyms to create a richer picture through progressive specification', 'Wastes words', 'Is accidental'], ans: 1 },
        { q: 'The boundary between style and content dissolves when:', opts: ['Never', 'The way something is said becomes inseparable from what is said — form IS content', 'Always', 'Rarely'], ans: 1 },
        { q: 'The progymnasmata (classical exercises) trained students in figures because:', opts: ['Tradition', 'Mastering figures meant mastering ways of thinking — the exercises were cognitive training, not just writing practice', 'Busy work', 'Schools required it'], ans: 1 },
        { q: 'In the digital age, the most viral phrases use figures:', opts: ['Coincidence', '"Yes we can" (anaphora), "Make America Great Again" (implied antithesis) — figures create memorability', 'They don\'t', 'Only old speeches do'], ans: 1 },
        { q: 'When a writer avoids ALL figures, the prose becomes:', opts: ['Clear', 'Flat and forgettable — some degree of figuration is necessary for memorable communication', 'Perfect', 'More honest'], ans: 1 },
        { q: 'The deepest lesson of style:', opts: ['Memorize figures', 'Every stylistic choice is a thinking choice — how you say it shapes what the audience understands and remembers', 'Use all figures', 'Style over substance'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Write three sentences about something you believe in, each using a different technique: one with repetition (anaphora), one with contrast (antithesis), one with a comparison (metaphor). Read them aloud — which is most powerful?' },
      growth: { prompt: 'Find a famous speech and identify at least three rhetorical figures. For each, explain not just WHAT the figure is but WHY the speaker chose it — what cognitive or emotional work does it do? (200 words)' },
      canopy: { prompt: 'Write 250 words arguing that rhetorical figures are not ornamental but cognitive — that metaphor, antithesis, and chiasmus shape how we think, not just how we speak. Use at least one example from rhetoric and one from everyday language.' },
    },
    encounter: {
      text: '"Ask not what your country can do for you — ask what you can do for your country."',
      attribution: '— John F. Kennedy, Inaugural Address (1961)',
      questions: [
        { tier: 'seed', q: 'This sentence flips something around. What changes between the first half and the second? Why is the flip powerful?' },
        { tier: 'growth', q: 'This is a chiasmus (ABBA pattern): country→you becomes you→country. The reversal isn\'t just elegant — it changes the audience\'s frame of thinking. How does the STRUCTURE of the sentence carry the argument?' },
        { tier: 'canopy', q: 'Kennedy doesn\'t argue "you should serve your country." He enacts the shift through syntax — the chiasmus makes you experience the reversal, not just hear it. Write 200 words on how rhetorical figures can embody arguments rather than just illustrate them.' },
      ]
    },
    bridge: 'Style makes language memorable. But the strongest rhetoric does more than say well — it does. Unit 8: Rhetoric as action.',
  },
  {
    id: 'r8', title: 'Rhetoric as Action', subtitle: 'When words change the world',
    anchorTexts: 'Performative speech ("I do," "I declare"), declarations of independence, liturgy',
    learn: 'Some words don\'t just describe reality — they create it. "I do" at a wedding makes you married. "I declare independence" creates a nation. "You\'re fired" changes someone\'s employment. These are performative utterances — speech that acts. Understanding when rhetoric does something, not just says something, is essential for understanding power, law, and sacred language.',
    quiz: {
      seed: [
        { q: '"I promise" is:', opts: ['Describing a promise', 'MAKING a promise — the words ARE the action', 'Neither', 'Just words'], ans: 1 },
        { q: '"I do" at a wedding is:', opts: ['Describing your feelings', 'A performative — it creates the marriage', 'A fact', 'Optional'], ans: 1 },
        { q: '"You\'re fired" doesn\'t describe a situation, it:', opts: ['Complains', 'Creates one — the words change reality', 'Reports', 'Nothing'], ans: 1 },
        { q: 'Words that DO things (not just SAY things) are called:', opts: ['Magic', 'Performative utterances', 'Lies', 'Strong words'], ans: 1 },
        { q: '"I declare this meeting open" works because:', opts: ['The speaker is loud', 'The speaker has the authority to make it so — the words and the authority together create the action', 'Meetings open themselves', 'Nothing'], ans: 1 },
        { q: '"Let there be light" (Genesis) is an ultimate performative because:', opts: ['God is loud', 'Divine speech creates reality — the words ARE the creation', 'It\'s metaphorical', 'Nothing'], ans: 1 },
        { q: 'A judge saying "I sentence you to ten years" is:', opts: ['Describing the sentence', 'Imposing it — the words create the legal reality', 'An opinion', 'A suggestion'], ans: 1 },
        { q: 'Not everyone\'s words have performative power. It depends on:', opts: ['Volume', 'Authority and context — only certain people in certain roles can make words act', 'Vocabulary', 'Nothing'], ans: 1 },
        { q: 'A child saying "I declare war" doesn\'t start a war because:', opts: ['Children can\'t talk', 'They lack the authority — performative power requires institutional backing', 'It\'s a joke', 'Words don\'t matter'], ans: 1 },
        { q: 'Rhetoric as action means:', opts: ['Talking loudly', 'Understanding that some communication DOES things, not just SAYS things', 'Being aggressive', 'Nothing'], ans: 1 },
      ],
      growth: [
        { q: 'J.L. Austin coined "performative utterance" to show that:', opts: ['Language is active', 'Not all language describes reality — some language creates, changes, or constitutes reality', 'Philosophy is practical', 'Nothing new'], ans: 1 },
        { q: 'The Declaration of Independence is performative because:', opts: ['It describes independence', 'The act of declaring IS the creation of the new nation — the words do what they say', 'Jefferson was a good writer', 'Britain agreed'], ans: 1 },
        { q: 'For a performative to succeed, it needs:', opts: ['Good grammar', 'Appropriate authority, proper context, and genuine intention — "felicity conditions"', 'An audience', 'Volume'], ans: 1 },
        { q: 'A wedding performed by someone without authority is:', opts: ['Valid', 'Invalid — the performative fails because the authority condition isn\'t met', 'Romantic', 'Illegal only'], ans: 1 },
        { q: 'Apologies are performative when:', opts: ['Never', 'They actually change the relationship — saying "I\'m sorry" should transform the situation', 'Always', 'Only if sincere'], ans: 3 },
        { q: 'A "hollow" apology fails as a performative because:', opts: ['It\'s too short', 'The sincerity condition isn\'t met — the words are said but the act isn\'t genuinely performed', 'Grammar is wrong', 'Nothing is wrong'], ans: 1 },
        { q: 'In Jewish liturgy, blessings are performative:', opts: ['They\'re just words', 'Saying "Blessed are You" enacts a relationship with God — the prayer doesn\'t describe, it constitutes', 'Sometimes', 'Never'], ans: 1 },
        { q: 'Naming (giving a child a name) is performative because:', opts: ['It\'s tradition', 'The act of naming creates the identity — the child IS that name from the moment of naming', 'Names are labels', 'Nothing changes'], ans: 1 },
        { q: 'Understanding speech as action changes how we think about:', opts: ['Grammar', 'Power — who has the authority to make words act, and who doesn\'t', 'Nothing', 'Only law'], ans: 1 },
        { q: 'The deepest insight: language is not just a mirror of reality but:', opts: ['A mirror', 'A tool that shapes, creates, and transforms reality', 'Separate from reality', 'Only descriptive'], ans: 1 },
      ],
      canopy: [
        { q: 'Austin\'s discovery that ordinary language "does things" challenges:', opts: ['Nothing', 'The assumption that language\'s primary function is to describe — representation is only one function among many', 'Grammar', 'Poetry'], ans: 1 },
        { q: 'Genesis 1 presents creation through speech. This implies:', opts: ['God is a speaker', 'Language has ontological power — words and reality are not separate domains', 'Metaphor only', 'Nothing theological'], ans: 1 },
        { q: 'The parallel between divine speech (Genesis) and human performatives (law, liturgy) suggests:', opts: ['Humans are gods', 'Human speech participates, in limited ways, in the creative power of language — we too create reality through words', 'Nothing', 'Sacrilege'], ans: 1 },
        { q: 'Judith Butler\'s theory of performativity argues that identity itself is:', opts: ['Fixed', 'Constituted through repeated speech acts — we "perform" gender, race, and identity through ongoing language use', 'Biological only', 'Unchangeable'], ans: 1 },
        { q: 'This is relevant to rhetoric because:', opts: ['It\'s not', 'If identity is performed through language, then rhetoric isn\'t just about persuasion — it\'s about the construction of selves and worlds', 'Only in academia', 'Only for philosophy'], ans: 1 },
        { q: 'Sacred texts often use performative language ("Be fruitful and multiply") rather than descriptive because:', opts: ['They\'re commands', 'They aim to enact, not just describe — the words participate in what they call for', 'Convention', 'Nothing special'], ans: 1 },
        { q: 'The line between "describing" and "doing" in language is:', opts: ['Clear', 'Blurrier than we think — even "factual" statements can create social reality (e.g., "He\'s a criminal")', 'Nonexistent', 'Only academic'], ans: 1 },
        { q: 'Understanding rhetoric as action gives the rhetor:', opts: ['More power', 'Greater responsibility — if words can create reality, the ethical stakes of communication are enormous', 'No responsibility', 'Nothing new'], ans: 1 },
        { q: 'The trivium culminates here because:', opts: ['It\'s the last topic', 'Grammar reads, Logic thinks, Rhetoric acts — and "action" includes the performative creation of new realities through language', 'Convention', 'Nothing deep'], ans: 1 },
        { q: 'The ultimate lesson:', opts: ['Words are just words', 'Language is power — it can describe, persuade, and CREATE. Mastering rhetoric means taking responsibility for the worlds your words build.', 'Use big words', 'Avoid action'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'List five examples of words that DO things (promises, declarations, apologies, commands, etc.). For each, explain what the words create or change.' },
      growth: { prompt: 'Find an example of a failed performative — a promise that wasn\'t kept, an apology that felt hollow, a declaration that wasn\'t recognized. What went wrong? Which "felicity condition" (authority, sincerity, context) was missing? (150 words)' },
      canopy: { prompt: 'Compare "Let there be light" (Genesis 1) with "We hold these truths to be self-evident" (Declaration of Independence). Both are performative — they create through speech. Write 250 words on how divine and human performatives differ and what it means that both use the same mechanism: language as world-making.' },
    },
    encounter: {
      text: '"And God said, Let there be light: and there was light."',
      attribution: '— Genesis 1:3 (KJV)',
      questions: [
        { tier: 'seed', q: 'God doesn\'t make light with hands — He speaks it into existence. What does this tell us about the power of words?' },
        { tier: 'growth', q: 'This is the ultimate performative: speech that creates reality. How does this compare to human performatives like "I promise" or "I declare"? What\'s similar and what\'s different?' },
        { tier: 'canopy', q: 'If the Bible begins with a performative utterance — speech that creates — then language is presented as ontologically primary, not secondary to reality. Write 200 words on what this means for rhetoric: if the foundational text of Western civilization begins with the claim that words make worlds, what responsibility does that place on speakers?' },
      ]
    },
    bridge: 'Rhetoric can create. But can your audience fight back? Unit 9: the ethics and practice of dialogue.',
  },
  {
    id: 'r9', title: 'Dialogue and Disagreement', subtitle: 'Rhetoric that listens',
    anchorTexts: 'Socratic dialogue, Talmudic machloket, civil debate',
    learn: 'Not all rhetoric is one-directional. The highest form may be dialogue — where you speak AND listen, argue AND learn, persuade AND are open to being persuaded. Socrates didn\'t lecture; he asked questions. The Talmud preserves disagreements because both sides illuminate. Rhetoric that only speaks is half the art. Rhetoric that listens is whole.',
    quiz: {
      seed: [
        { q: 'Dialogue is different from a speech because:', opts: ['It\'s shorter', 'Both sides speak and listen', 'It\'s less important', 'No difference'], ans: 1 },
        { q: 'Socrates taught by:', opts: ['Lecturing', 'Asking questions that helped people discover answers themselves', 'Yelling', 'Writing books'], ans: 1 },
        { q: 'Listening is part of rhetoric because:', opts: ['It isn\'t', 'You can\'t persuade effectively if you don\'t understand your audience', 'Politeness', 'Teachers say so'], ans: 1 },
        { q: 'Disagreeing respectfully means:', opts: ['Agreeing', 'Attacking the argument, not the person, and remaining open to being wrong', 'Being quiet', 'Never disagreeing'], ans: 1 },
        { q: 'The Talmud preserves minority opinions because:', opts: ['Bad editing', 'Even rejected opinions illuminate truth and may be relevant later', 'Tradition', 'Printing space'], ans: 1 },
        { q: '"Steel-manning" means:', opts: ['Being strong', 'Building the strongest version of your opponent\'s argument before responding', 'Ignoring others', 'Winning'], ans: 1 },
        { q: '"Straw-manning" means:', opts: ['Being weak', 'Weakening your opponent\'s argument to make it easier to attack', 'Being honest', 'Nothing'], ans: 1 },
        { q: 'The goal of productive disagreement is:', opts: ['Winning', 'Understanding — both sides learning something, even if they don\'t agree', 'Silence', 'Agreement'], ans: 1 },
        { q: 'Being open to changing your mind is:', opts: ['Weakness', 'Intellectual strength — it means you care about truth more than being right', 'Impossible', 'Rare'], ans: 1 },
        { q: 'Dialogue fails when:', opts: ['People disagree', 'People stop listening and only try to win', 'It\'s long', 'Topics are hard'], ans: 1 },
      ],
      growth: [
        { q: 'Socratic method works by:', opts: ['Giving answers', 'Asking questions that expose contradictions in the other person\'s beliefs — leading them to revise through self-discovery', 'Tricking people', 'Being confusing'], ans: 1 },
        { q: 'The Socratic elenchus (refutation through questioning) respects the interlocutor because:', opts: ['It\'s gentle', 'It assumes they can reason and find truth themselves — it doesn\'t impose conclusions', 'It agrees with them', 'It doesn\'t respect them'], ans: 1 },
        { q: 'Talmudic machloket (disagreement) is considered "for the sake of heaven" when:', opts: ['The rabbis are nice', 'Both sides genuinely seek truth rather than victory — the disagreement serves understanding', 'They agree', 'It\'s about law only'], ans: 1 },
        { q: '"Elu v\'elu divrei Elohim chayyim" (these and these are words of the living God) means:', opts: ['Everyone is right', 'Opposing views can both be legitimate expressions of truth — disagreement can be permanent and productive', 'God contradicts himself', 'Nothing philosophical'], ans: 1 },
        { q: 'Active listening (paraphrasing, asking clarifying questions) serves rhetoric by:', opts: ['Wasting time', 'Ensuring you understand the other position before responding — preventing straw men', 'Being polite', 'Nothing'], ans: 1 },
        { q: 'Charitable interpretation (reading others\' arguments in their strongest form) is:', opts: ['Naive', 'Both morally right and strategically smart — you engage the real argument, not a distortion', 'Weak', 'Unnecessary'], ans: 1 },
        { q: 'Online discourse often fails at dialogue because:', opts: ['Text is hard', 'Short formats, anonymity, and algorithmic amplification of outrage reward performance over genuine exchange', 'People are mean', 'It\'s not rhetoric'], ans: 1 },
        { q: 'The ability to hold two opposing ideas simultaneously is:', opts: ['Confusion', 'A sign of intellectual maturity — Fitzgerald called it "the test of a first-rate intelligence"', 'Impossible', 'Weakness'], ans: 1 },
        { q: 'A person who never changes their mind is:', opts: ['Strong', 'Closed — they value consistency over truth', 'Admirable', 'Logical'], ans: 1 },
        { q: 'The ultimate goal of rhetorical dialogue:', opts: ['Winning', 'Both participants thinking better than either could alone', 'Agreement', 'Silence'], ans: 1 },
      ],
      canopy: [
        { q: 'Plato\'s dialogues are themselves a form of rhetoric. Their structure argues that:', opts: ['Plato was right', 'Truth emerges through conversation, not monologue — the dialogue form IS the philosophical argument', 'Socrates was smart', 'Writing is superior'], ans: 1 },
        { q: 'The Talmud as a text is permanently dialogical: it never resolves into a single voice. This implies:', opts: ['Failure to decide', 'Truth is larger than any single perspective — the conversation itself is the thing of value', 'Rabbis disagree', 'Nothing'], ans: 1 },
        { q: 'Buber\'s "I-Thou" vs "I-It" distinction applied to rhetoric:', opts: ['No application', 'Treating your audience as a "Thou" (a full person to be met) vs an "It" (a target to be manipulated) defines ethical rhetoric', 'Buber wasn\'t about rhetoric', 'Only religious'], ans: 1 },
        { q: 'Levinas: the face of the other demands ethical response. For rhetoric this means:', opts: ['Nothing', 'True communication requires acknowledging the other person as someone who can teach you, not just someone to persuade', 'Only philosophy', 'Being nice'], ans: 1 },
        { q: 'Habermas\'s "ideal speech situation" (no coercion, equal participation, truth-seeking) is:', opts: ['Achieved', 'An unreachable ideal that nonetheless orients genuine discourse — something to approach, not achieve', 'Irrelevant', 'Easy'], ans: 1 },
        { q: 'Disagreement is productive when it:', opts: ['Ends', 'Forces both parties to articulate, refine, and test their positions — making thinking sharper', 'Is avoided', 'Results in a winner'], ans: 1 },
        { q: 'The deepest rhetoric may be Socratic because:', opts: ['Socrates was wise', 'It doesn\'t impose truth but creates the conditions for others to discover it — liberation, not domination', 'It\'s old', 'Academics say so'], ans: 1 },
        { q: 'A culture that cannot disagree productively will:', opts: ['Be peaceful', 'Stagnate or fracture — productive disagreement is how communities think together', 'Agree on everything', 'Thrive'], ans: 1 },
        { q: 'The relationship between rhetoric and democracy:', opts: ['None', 'Democracy requires citizens who can speak, listen, disagree, and deliberate — rhetoric is the technology of self-governance', 'Only political', 'Democracy doesn\'t need rhetoric'], ans: 1 },
        { q: 'The lesson of this unit:', opts: ['Listen more', 'The highest rhetoric is not the speech that wins but the dialogue that transforms — where both sides think better together', 'Stop arguing', 'Always compromise'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'Find someone who disagrees with you about something (a friend, family member, or classmate). Ask them to explain their view. Write down their best argument in your own words. Then ask them: "Did I get that right?"' },
      growth: { prompt: 'Take a position you hold strongly. Write the strongest possible argument AGAINST your position (steel man). Then respond to it. Did building the steel man change how you think? (200 words)' },
      canopy: { prompt: 'The Talmud preserves disagreements rather than resolving them. Modern debates try to produce winners. Write 250 words on which model is better for finding truth — and when each is appropriate.' },
    },
    encounter: {
      text: '"Shammai says: make your Torah study fixed... Hillel says: be of the disciples of Aaron, loving peace and pursuing peace, loving your fellow creatures and bringing them close to the Torah."',
      attribution: '— Pirkei Avot 1:15 (adapted)',
      questions: [
        { tier: 'seed', q: 'Shammai and Hillel often disagree. Does the text tell you which one is right? What does it do instead?' },
        { tier: 'growth', q: 'The text preserves both views without resolving them. What does this choice say about how the editors understood truth — as something one person possesses, or as something that emerges between perspectives?' },
        { tier: 'canopy', q: 'Write 200 words on the Talmudic model of "disagreement for the sake of heaven." How does this compare to modern debate culture? What would it look like to adopt this approach in a classroom, workplace, or online forum?' },
      ]
    },
    bridge: 'Dialogue transforms both speakers. The final unit asks: now that you can read, think, and speak — what will you say? Unit 10: Rhetoric and the Good.',
  },
  {
    id: 'r10', title: 'Rhetoric and the Good', subtitle: 'The capstone — what is all this for?',
    anchorTexts: 'The trivium as a whole, your own voice',
    learn: 'The trivium ends here: with the question of purpose. Grammar gave you the ability to read closely. Logic gave you the ability to think rigorously. Rhetoric gives you the ability to communicate powerfully. But to what end? The liberal arts were called "liberal" because they were meant to liberate — to free the mind from ignorance and the will from manipulation. The final question is not "Can you persuade?" but "What will you use this for?"',
    quiz: {
      seed: [
        { q: '"Liberal" in "liberal arts" means:', opts: ['Political', 'Liberating — freeing the mind', 'Easy', 'Broad'], ans: 1 },
        { q: 'Grammar + Logic + Rhetoric together prepare you to:', opts: ['Pass tests', 'Read closely, think clearly, and communicate powerfully', 'Get a job', 'Nothing'], ans: 1 },
        { q: 'Skills without purpose are:', opts: ['Valuable', 'Tools without direction — powerful but potentially dangerous', 'Complete', 'Safe'], ans: 1 },
        { q: 'The question "What is all this for?" is:', opts: ['Unimportant', 'The most important question — the one that gives everything else meaning', 'Philosophical fluff', 'Unanswerable'], ans: 1 },
        { q: 'Rhetoric in the service of truth is:', opts: ['Rare', 'The highest use of communication — making true things beautiful and compelling', 'Impossible', 'Boring'], ans: 1 },
        { q: 'Rhetoric in the service of lies is:', opts: ['Effective', 'The most dangerous misuse of skill', 'Impossible', 'Acceptable'], ans: 1 },
        { q: 'The trivium was designed to produce:', opts: ['Workers', 'Free, thinking citizens capable of self-governance and the pursuit of wisdom', 'Academics', 'Writers'], ans: 1 },
        { q: 'Your voice — your way of reading, thinking, and speaking — is:', opts: ['Unimportant', 'Uniquely yours and carries responsibility', 'The same as everyone\'s', 'Complete now'], ans: 1 },
        { q: 'The most important thing about the trivium is:', opts: ['The content', 'The habits of mind — close attention, rigorous thinking, honest communication', 'The tests', 'The certificate'], ans: 1 },
        { q: 'After completing the trivium, you should:', opts: ['Stop learning', 'Keep reading, keep thinking, keep speaking — these arts are lifelong practices', 'Move to quadrivium', 'Nothing'], ans: 1 },
      ],
      growth: [
        { q: 'The trivium leads to the quadrivium (arithmetic, geometry, music, astronomy), which leads to:', opts: ['Nothing', 'Philosophy and theology — the trivium is preparation for the highest questions', 'More trivium', 'Employment'], ans: 1 },
        { q: 'Hugh of St. Victor\'s Didascalicon argues the liberal arts exist to:', opts: ['Educate', 'Restore the wholeness of human nature — broken by ignorance, repaired by learning', 'Create scholars', 'Fill time'], ans: 1 },
        { q: 'This is a deeply non-utilitarian view of education:', opts: ['It\'s wrong', 'Education isn\'t primarily for employment but for becoming fully human', 'It\'s outdated', 'It\'s impractical'], ans: 1 },
        { q: 'Rhetoric with wisdom asks not "Can I persuade?" but:', opts: ['How?', '"Should I? And if so, what is the truth I need to communicate?"', 'Why bother?', 'Who cares?'], ans: 1 },
        { q: 'A person who can read, think, and speak but chooses to use those skills to manipulate has:', opts: ['Mastered the trivium', 'Failed its deepest purpose — the skills were meant to serve truth, not power', 'Succeeded', 'No responsibility'], ans: 1 },
        { q: 'The Jewish concept of tikkun olam (repairing the world) suggests skills should be used for:', opts: ['Self-advancement', 'The good of the whole — the purpose of learning is to serve something larger than yourself', 'Nothing specific', 'Religious practice only'], ans: 1 },
        { q: 'Developing your "voice" means:', opts: ['Speaking loudly', 'Finding the intersection of what you know (Grammar), what you think (Logic), and how you choose to communicate (Rhetoric) — your unique contribution', 'Imitating others', 'Being original always'], ans: 1 },
        { q: 'The trivium is "trivial" (its Latin root meaning "three roads meeting at a crossroads") suggesting:', opts: ['It\'s unimportant', 'It\'s the starting point — the crossroads from which all further learning departs', 'It\'s basic', 'Only three things matter'], ans: 1 },
        { q: 'The habit of asking "Is this true? Is it well-reasoned? Is it communicated honestly?" is:', opts: ['Exhausting', 'The permanent gift of the trivium — these questions become instinctive', 'Unnecessary', 'Only for school'], ans: 1 },
        { q: 'The deepest purpose of the trivium:', opts: ['Academic preparation', 'The formation of a person who can pursue wisdom, serve truth, and contribute to the common good', 'Employment skills', 'Cultural literacy'], ans: 1 },
      ],
      canopy: [
        { q: 'The trivium as a system argues that:', opts: ['Three subjects are enough', 'Reading, thinking, and communicating are not separate skills but a unified practice — each depends on and enriches the others', 'Education should be sequential', 'Nothing philosophical'], ans: 1 },
        { q: 'The medieval placement of theology above the liberal arts implies:', opts: ['Religion is better', 'The liberal arts are instrumental — supremely valuable, but in service of something beyond themselves', 'The arts are inferior', 'Nothing'], ans: 1 },
        { q: 'Whether or not you accept a theological framework, the structural insight remains:', opts: ['Nothing', 'Skills are most fully realized when directed toward meaning and purpose beyond themselves', 'Only religious people benefit', 'The structure is obsolete'], ans: 1 },
        { q: 'In our era of information overload, the trivium\'s emphasis on:', opts: ['Speed', 'Close reading (Grammar), critical thinking (Logic), and honest communication (Rhetoric) is MORE relevant, not less', 'Quick answers', 'Efficiency'], ans: 1 },
        { q: 'The person the trivium aims to form is:', opts: ['An expert', 'A thoughtful, articulate, honest person capable of navigating complexity — in any field', 'A scholar', 'A speaker'], ans: 1 },
        { q: 'This is not the same as expertise because:', opts: ['It\'s less', 'Expertise is narrow; the trivium forms the general capacity for understanding that makes expertise meaningful', 'It\'s more', 'Expertise is trivium'], ans: 1 },
        { q: 'The prophetic tradition models the complete trivium:', opts: ['How?', 'Close reading of reality (Grammar), rigorous moral reasoning (Logic), and powerful public speech (Rhetoric) in service of justice', 'It doesn\'t', 'Only rhetoric'], ans: 1 },
        { q: '"To whom much is given, much is required" applies to the trivium because:', opts: ['It doesn\'t', 'The skills of reading, thinking, and communicating confer power — and power demands ethical responsibility', 'It\'s a quote', 'Only for the talented'], ans: 1 },
        { q: 'The trivium is "complete" and yet:', opts: ['Finished', 'Just beginning — the real work is the lifelong application of these capacities to the questions that matter', 'Over', 'Done'], ans: 1 },
        { q: 'The final word of the trivium:', opts: ['Goodbye', 'Go — read, think, speak, listen, argue, create, and use these liberating arts to become more fully human and to help others do the same', 'Study more', 'Test yourself'], ans: 1 },
      ],
    },
    workshop: {
      seed: { prompt: 'What do you want to use your ability to read, think, and communicate for? Write 3-4 sentences about what matters to you and how the skills of the trivium might help you pursue it.' },
      growth: { prompt: 'Write a one-paragraph "personal statement" of what you believe about learning. What is education FOR? Use what you\'ve learned in the trivium to articulate your answer with clarity, evidence, and conviction. (200 words)' },
      canopy: { prompt: 'Write 300 words on the relationship between skill and purpose. The trivium gives you extraordinary tools. What obligation, if any, comes with those tools? Draw on at least one thinker or tradition encountered in this course (Aristotle, King, the Talmud, Ecclesiastes, etc.).' },
    },
    encounter: {
      text: '"And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God."',
      attribution: '— Micah 6:8',
      questions: [
        { tier: 'seed', q: 'This verse says what matters most in three phrases. What are they? Why these three?' },
        { tier: 'growth', q: 'Micah reduces everything to three requirements: justice (action), mercy (feeling), humility (character). How do these map onto the trivium? Grammar as careful attention (humility), Logic as clear reasoning (justice), Rhetoric as compassionate communication (mercy)?' },
        { tier: 'canopy', q: 'The trivium began with reading words and ends with the question: what will you do? Write 250 words on the journey from Grammar (attending to the world) through Logic (thinking clearly about it) to Rhetoric (communicating in service of the good). What has changed in you?' },
      ]
    },
    bridge: 'The trivium is complete. Grammar reads. Logic thinks. Rhetoric speaks. Now: go.',
  },
];
